Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Employee</fullName>
        <active>true</active>
        <description>Used for employee contact records.</description>
        <label>Employee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Used for vendor contact records.</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Guarantor__c.object
<CustomObject>
    <description>The Guarantor object is used to store all guarantor contact information.</description>
    <label>Guarantor</label>
    <nameField>
        <label>Guarantor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Managers_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Manager Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Manager_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Identified</fullName>
                </value>
                <value>
                    <fullName>Change Implemented</fullName>
                </value>
                <value>
                    <fullName>No Change</fullName>
                </value>
                <value>
                    <fullName>Send a Thank You</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Area__c</fullName>
        <label>Service Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts Payable (Payments to Vendors)</fullName>
                </value>
                <value>
                    <fullName>Benefits &amp; Retirement</fullName>
                </value>
                <value>
                    <fullName>Capital Acquisition/Approval</fullName>
                </value>
                <value>
                    <fullName>Charge Capture</fullName>
                </value>
                <value>
                    <fullName>Contact Center</fullName>
                </value>
                <value>
                    <fullName>Disability Management</fullName>
                </value>
                <value>
                    <fullName>Employee Portal</fullName>
                </value>
                <value>
                    <fullName>Hiring</fullName>
                </value>
                <value>
                    <fullName>Job Descriptions &amp; Evaluations</fullName>
                </value>
                <value>
                    <fullName>Learning (HealthStream)</fullName>
                </value>
                <value>
                    <fullName>Patient Access - Pre-service</fullName>
                </value>
                <value>
                    <fullName>Payroll</fullName>
                </value>
                <value>
                    <fullName>Performance Review (PSDP)</fullName>
                </value>
                <value>
                    <fullName>Purchasing/Ordering</fullName>
                </value>
                <value>
                    <fullName>Supplies Distribution/Delivery</fullName>
                </value>
                <value>
                    <fullName>Travel and Expense Reimbursement</fullName>
                </value>
                <value>
                    <fullName>Tuition Reimbursement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkEmail__c</fullName>
        <label>WorkEmail</label>
        <type>Email</type>
    </fields>
    <label>Managers Feedback</label>
    <nameField>
        <displayFormat>MF-{0000}</displayFormat>
        <label>Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manager Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Patient__c.object
<CustomObject>
    <description>The Patient object is used to store all patient information.</description>
    <fields>
        <fullName>Patient_DotOne__c</fullName>
        <description>The Epic unique patient identifier called the &quot;.1&quot;</description>
        <externalId>true</externalId>
        <label>Patient_DotOne</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Patient_EPI_ID__c</fullName>
        <description>External ID used to match a patient record to the equivalent record in the Initiate MDM repository when updating and/or inserting.</description>
        <inlineHelpText>Patient EPI-ID from Initiate MDM.</inlineHelpText>
        <label>Patient EPI-ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_First_Name__c</fullName>
        <label>Patient First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Last_Name__c</fullName>
        <label>Patient Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Patient_Account__c.object
<CustomObject>
    <description>Patient Account allows a many-to-many relationship between Patient and Guarantor records.</description>
    <fields>
        <fullName>Patient_DotOne__c</fullName>
        <label>Patient DotOne</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Patient Account</label>
    <nameField>
        <label>Patient Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/VFC01_CustomConsole_CaseSplitTest.cls
/**  
*     Class Name: VFC01_CustomConsole_CaseSplitTest
*     Author: Offshore IDC
*     Date: 08-Jan-2016
*     Project Name: CRM - SFT - Sutter Health
*     Description: Test Class for VFC01_CustomConsole_CaseSplitTest Class. Related to REQ-3274.
*     
*     History
*     VERSION    AUTHOR         DATE           DETAIL     Description
*     1          Offshore IDC   08-Jan-2016   Test Class covers the scenario of 08-Jan-2016 - Case details has been divided into 2 sections i.e Open & Closed Cases.   
*     2          Offshore IDC   02-Feb-2016   Test class covers the scenario of vendor split page as per Req-3733.
*     --------  
**/
@isTest
private class VFC01_CustomConsole_CaseSplitTest {
     
    /*******************************************************************
    Purpose: Creates Account, Contact & Case record. Calls the method to test open cases functionality 
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testOpenCaseLstPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Employee').RecordTypeId;
            insert contactObj;
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;  
            consoleObj.caseLst();
            
            Case caseObj1 = new Case();
            caseObj1.Inquiry_Type__c = 'HR General Inquiry';
            caseObj1.Inquiry_Reason__c = 'HR Reporting';
            caseObj1.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('S3 Interaction Log').RecordTypeId;
            caseObj1.contactId =  contactObj.id;
            caseList.add(caseObj1);
            insert caseList;
            // Assert to check Case is inserted successfully
            system.assert(caseList.size()>0);
            consoleObj.caseLst();
        } catch(Exception ex) {}
    }
    
    /*******************************************************************
    Purpose: Creates Account, Contact & Manager feedback record. Calls the method to test Manager Feedback functionality 
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testManagerFeedbackPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Employee').RecordTypeId;
            insert contactObj;
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;  
            consoleObj.getManagerFeedback();
            
            Managers_Feedback__c managerFeedbackObj = new Managers_Feedback__c();
            managerFeedbackObj.Contact__c = contactObj.Id;
            managerFeedbackObj.Service_Area__c = 'Hiring';
            managerFeedbackObj.Subject__c = 'Test';
            //feedbackRec.Resolution__c = 'Hiring';
            managerFeedbackObj.WorkEmail__c = 'xyz123abc@fakeemailsacd.com';
            managerFeedbackObj.Comments__c = 'Test';
            managerFeedbackObj.Status__c = 'New'; 
            insert managerFeedbackObj;
            // Assert to check Manager Feedback is inserted successfully
            system.assert(managerFeedbackObj != NULL);
            consoleObj.getManagerFeedback();
        } catch(Exception ex) {}
    }
     
    /*******************************************************************
    Purpose: Creates Account, Contact & Case record. Calls the method to test Closed cases functionality 
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testClosedEmployeeFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Employee').RecordTypeId;
            insert contactObj; 
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;
            consoleObj.caseLst(); 
            
            Case caseObj1 = new Case();
            caseObj1.Inquiry_Type__c = 'HR General Inquiry';
            caseObj1.Inquiry_Reason__c = 'HR Reporting';
            caseObj1.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('S3 Interaction Log').RecordTypeId;
            caseObj1.contactId =  contactObj.id;
            caseObj1.Status = 'Closed';
            caseObj1.Close_Reason__c = 'Cancelled';
            caseList.add(caseObj1);
            insert caseList;
            // Assert to check Case is inserted successfully
            system.assert(caseList.size()>0);
            consoleObj.caseLst();
        } catch(Exception ex) {}
     }
     /*******************************************************************
    Purpose: Creates Account, employee Contact record. Calls the method to test negative scenario where no case is associated to employee contact. 
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
     static testMethod void testEmployeeNegativeFunctionality() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Employee').RecordTypeId;
            insert contactObj; 
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;
            consoleObj.caseLst();
          
            
            // Assert to check no case is attached to the employee record
            Integer size = 0;
            system.assertEquals(caseList.size(), size);
            consoleObj.caseLst();
         
        } catch(Exception ex) {}
     }
    /*******************************************************************
    Purpose: Creates Account, Contact & Patient record. Calls the method to test patient functionality
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testPatientFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  NULL;
            consoleObj.getPatientPage();
            
            Patient__c patientObj = new Patient__c();
            patientObj.Patient_First_Name__c = 'TestFName';
            patientObj.Patient_Last_Name__c = 'TestLName';
            patientObj.Patient_EPI_ID__c = AP01_TestDataTokens.PATIENT_EPI_ID;
            patientObj.Patient_DotOne__c = AP01_TestDataTokens.PATIENT_DOTONE;
            insert patientObj; 
            // Assert to check Patient is inserted successfully
            system.assert(patientObj != NULL);
            consoleObj.linkId =  patientObj.Id;
            consoleObj.getPatientPage();
        } catch(Exception ex) {}
    }
    
    /*******************************************************************
    Purpose: Creates Account, Contact, Patient, guarantor & Patient Account record. Calls the method to test patient account functionality   
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testPatientAccountFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            
            Patient__c patientObj = new Patient__c();
            patientObj.Patient_First_Name__c = 'TestFName';
            patientObj.Patient_Last_Name__c = 'TestLName';
            patientObj.Patient_EPI_ID__c = AP01_TestDataTokens.PATIENT_EPI_ID;
            patientObj.Patient_DotOne__c = AP01_TestDataTokens.PATIENT_DOTONE;
            insert patientObj; 
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  patientObj.id;
            consoleObj.getPatientAccountPage();
            
            //Create Guarantor 
            Guarantor__c guarantor1 = AP01_TestDataUtility.createGuarantor();
            
            Patient_Account__c patAccount1 = AP01_TestDataUtility.createPatientAccount(guarantor1, patientObj);
            // Assert to check Patient is inserted successfully
            system.assert(patientObj != NULL);
            consoleObj.getPatientAccountPage();
        } catch(Exception ex) {}
    }
     
    /*******************************************************************
    Purpose: Creates Account, Contactrecord. Calls the method to test employee page functionality   
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testemployeeFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Employee').RecordTypeId;
            insert contactObj;  
            // Assert to check Employee is inserted successfully
            system.assert(contactObj != NULL);
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;
            consoleObj.getEmployeePage();
        
        } catch(Exception ex) {}
    }
     
    /*******************************************************************
    Purpose: Patient & Case. Calls the method to test open Cases attached to patient functionality   
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testOpenPatientFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();        
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  NULL;
            consoleObj.casePatientLst();
            
            Patient__c patientObj = new Patient__c();
            patientObj.Patient_First_Name__c = 'TestFName';
            patientObj.Patient_Last_Name__c = 'TestLName';
            patientObj.Patient_EPI_ID__c = AP01_TestDataTokens.PATIENT_EPI_ID;
            patientObj.Patient_DotOne__c = AP01_TestDataTokens.PATIENT_DOTONE;
            insert patientObj; 
            
            Case caseObj1 = new Case();
            caseObj1.Inquiry_Type__c = 'HR General Inquiry';
            caseObj1.Inquiry_Reason__c = 'HR Reporting';
            caseObj1.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('S3 Interaction Log').RecordTypeId;
            caseObj1.Patient__c =  patientObj.id;
            caseList.add(caseObj1);
            insert caseList;
            
            // Assert to check Case is inserted successfully
            system.assert(caseList.size()>0);
            
            consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  patientObj.id;
            consoleObj.casePatientLst();
        } catch(Exception ex) {}
     }
     
    /*******************************************************************
    Purpose: Patient & Case. Calls the method to test Closed Cases attached to patient functionality   
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testClosedPatientFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  NULL;
            consoleObj.casePatientLst();
            Patient__c patientObj = new Patient__c();
            patientObj.Patient_First_Name__c = 'TestFName';
            patientObj.Patient_Last_Name__c = 'TestLName';
            patientObj.Patient_EPI_ID__c = AP01_TestDataTokens.PATIENT_EPI_ID;
            patientObj.Patient_DotOne__c = AP01_TestDataTokens.PATIENT_DOTONE;
            insert patientObj; 
            
            Case caseObj1 = new Case();
            caseObj1.Inquiry_Type__c = 'HR General Inquiry';
            caseObj1.Inquiry_Reason__c = 'HR Reporting';
            caseObj1.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('S3 Interaction Log').RecordTypeId;
            caseObj1.Patient__c =  patientObj.id;
            caseObj1.Status = 'Closed';
            caseObj1.Close_Reason__c = 'Cancelled';
            caseList.add(caseObj1);
            insert caseList;
            // Assert to check Case is inserted successfully
            system.assert(caseList.size()>0);
            consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  patientObj.id;
            consoleObj.casePatientLst();
        } catch(Exception ex) {}
    }
     /*******************************************************************
    Purpose: Creates Patient record. Calls the method to test negative scenario where no case is associated to patient. 
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
     static testMethod void testPatientNegativeFunctionality() {
        try {
            Patient__c patientObj = new Patient__c();
            patientObj.Patient_First_Name__c = 'TestFName';
            patientObj.Patient_Last_Name__c = 'TestLName';
            patientObj.Patient_EPI_ID__c = AP01_TestDataTokens.PATIENT_EPI_ID;
            patientObj.Patient_DotOne__c = AP01_TestDataTokens.PATIENT_DOTONE;
            insert patientObj; 
            
            List<Case> caseList = new List<Case>();
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  patientObj.id;
            
            consoleObj.casePatientLst(); 
            
            // Assert to check no case is attached to the employee record
            Integer size = 0;
            system.assertEquals(caseList.size(), size);
            consoleObj.casePatientLst();
            
        } catch(Exception ex) {}
     }
    /*******************************************************************
    Purpose: Req-3733 - Creates Account and vendor Contact record. Calls the method to test vendor page functionality.   
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testVendorFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Vendor').RecordTypeId;
            insert contactObj;  
            // Assert to check Vendor is inserted successfully
            system.assert(contactObj != NULL);
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;
            consoleObj.getVendorPage();
            
        } catch(Exception ex) {}
    }
    /*******************************************************************
    Purpose: Req-3733 - Creates Account, vendor Contact & Case record. Calls the method to test open cases functionality for Vendor.
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testVendorOpenCaseLstPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Vendor').RecordTypeId;
            insert contactObj;
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;  
            consoleObj.caseLst();
            
            Case caseObj1 = new Case();
            caseObj1.Inquiry_Type__c = 'HR General Inquiry';
            caseObj1.Inquiry_Reason__c = 'HR Reporting';
            caseObj1.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('S3 Interaction Log').RecordTypeId;
            caseObj1.contactId =  contactObj.id;
            caseList.add(caseObj1);
            insert caseList;
            // Assert to check Case is inserted successfully
            system.assert(caseList.size()>0);
            consoleObj.caseLst();
        } catch(Exception ex) {}
    }
    /*******************************************************************
    Purpose: Req-3733 - Creates Account, vendor Contact & Case record. Calls the method to test Closed cases functionality for Vendor.
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
    static testMethod void testClosedVendorFunctionalityPositiveAndNegative() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Vendor').RecordTypeId;
            insert contactObj; 
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;
            consoleObj.caseLst(); 
            
            Case caseObj1 = new Case();
            caseObj1.Inquiry_Type__c = 'HR General Inquiry';
            caseObj1.Inquiry_Reason__c = 'HR Reporting';
            caseObj1.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('S3 Interaction Log').RecordTypeId;
            caseObj1.contactId =  contactObj.id;
            caseObj1.Status = 'Closed';
            caseObj1.Close_Reason__c = 'Cancelled';
            caseList.add(caseObj1);
            insert caseList;
            // Assert to check Case is inserted successfully
            system.assert(caseList.size()>0);
            consoleObj.caseLst();
        } catch(Exception ex) {}
     }
     /*******************************************************************
    Purpose: Creates Account, Contact record for vendor. Calls the method to test negative scenario where no case is associated to vendor contact. 
    Parameters: [NA]
    Returns: [NA]
    Throws [Exceptions]: [NA]
    ********************************************************************/
     static testMethod void testVendorNegativeFunctionality() {
        try {
            List<Case> caseList = new List<Case>();
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName ='TestContact';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Vendor').RecordTypeId;
            insert contactObj; 
            
            VFC01_CustomConsole consoleObj = new VFC01_CustomConsole();
            consoleObj.linkId =  contactObj.id;
            consoleObj.caseLst();
            
            
            // Assert to check no case is attached to the vendor record
            Integer size = 0;
            system.assertEquals(caseList.size(), size);
            consoleObj.caseLst();
           
        } catch(Exception ex) {}
     }
}