Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Record type for S3 Providers</description>
        <label>S3 Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_External_ID1__c</fullName>
        <description>External ID used to match a contact record to its equivalent record in a source system when updating and/or inserting.</description>
        <externalId>true</externalId>
        <label>Contact External ID 1</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Communication Preferences – EHR</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Basket</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Address__c</fullName>
        <label>Provider Correspondence Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_City__c</fullName>
        <label>Provider Correspondence City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Fax_Number__c</fullName>
        <label>Provider Correspondence Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_PostalCode__c</fullName>
        <label>Provider Correspondence PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_State__c</fullName>
        <label>Provider Correspondence State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Title__c</fullName>
        <label>Provider Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Used for member contact records.</description>
        <label>Member</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for provider contact records.</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Communication Preferences – EHR</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Basket</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_LastName__c</fullName>
        <formula>Contact_Id__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider LastName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Title__c</fullName>
        <label>Provider Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone__c</fullName>
        <label>Primary Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status field created as part of REQ 3611 PDV Call Center</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Validated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Validation-Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tech_Phone_Number__c</fullName>
        <description>used to store phone number without special characters.</description>
        <label>Tech Phone Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validation_Source_Channel__c</fullName>
        <label>Validation Source Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/CreatedDate__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This field is using in oltp field for copying PCP data from contact object to PCP object req no 3236</description>
    <fields>
        <fullName>Created_date__c</fullName>
        <label>Created date</label>
        <type>Date</type>
    </fields>
    <label>Created Date</label>
</CustomObject>

Sutter Health/src/objects/CS_ManageProfile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting containing Profile Names</description>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <description>Profile Name Strings</description>
        <label>Profile Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CS_ManageProfile</label>
</CustomObject>

Sutter Health/src/objects/PDICallCampaignEmail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to control Email field on agent console.</description>
    <label>PDICallCampaignEmail</label>
</CustomObject>

Sutter Health/src/objects/PDIProviderSearch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Provider Search Flag to display provider Search Information</description>
    <label>PDI Provider Search</label>
</CustomObject>

Sutter Health/src/objects/ProvidersByPhoneNumber__c.object
<CustomObject>
    <description>Used to store Providers common phone numbers.</description>
    <fields>
        <fullName>Tech_Phone_Number__c</fullName>
        <description>used to store phone number</description>
        <label>Tech Phone Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Providers By Phone Number</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers By Phone Number</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Preferred Communication Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Basket</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Address__c</fullName>
        <label>Provider Correspondence Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_City__c</fullName>
        <label>Provider Correspondence City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Phone__c</fullName>
        <description>Provider Correspondence Phone</description>
        <label>Provider Correspondence Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_PostalCode__c</fullName>
        <label>Provider Correspondence PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_State__c</fullName>
        <label>Provider Correspondence State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sutter Health/src/classes/ProviderSummaryTriggerBkupTest.cls
/**********************************************************************
Name: ProviderSummaryTriggerBkupTest
Copyright © 2015 IDC Offshore
======================================================
======================================================
Purpose:
This is the test class for Provider Summary trigger 
======================================================
======================================================
History
-------
VERSION  AUTHOR        DATE        DETAIL                 Description
1.0      IDC Offshore  10/6/2015  Development complete   This class is defined to test Provider Summary trigger for all scenarios
***********************************************************************/


@isTest
public class ProviderSummaryTriggerBkupTest {
    
    /*******************************************************************
Purpose: method to create test data used by all test methods
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    
    @testsetup
    static void createTestData()
    {
        
        /** Creating Custom Setting data to be used in the code of various helper classes like ManageContactDatabase,ManageCommunityUsers etc. **/
        CreatedDate__c obj =new CreatedDate__c();
        obj.Created_date__c = date.today();
        obj.name ='CopyPcpDate';
        insert obj;
        
        CS_ManageProfile__c CSMCommunities_Portal = new CS_ManageProfile__c(Name = 'Communities_Portal', Profile_Name__c='Community Portal');
        CS_ManageProfile__c CSMCommunities_Provider = new CS_ManageProfile__c(Name = 'Communities_Provider', Profile_Name__c='Community Portal Manager');
        CS_ManageProfile__c CSMCommunity_Portal_Manager = new CS_ManageProfile__c(Name = 'Community_Portal_Manager', Profile_Name__c='Community Portal Manager');
        Insert CSMCommunities_Portal;
        Insert CSMCommunities_Provider;
        Insert CSMCommunity_Portal_Manager;
        
        /** Fetching the profile id of system Administrator for creating test data **/
        Id profileId = [select id from Profile where name='System Administrator'].id;
        Group objPublicGrp_Queue,objPublicGrp_Queue_Ng;
        QueueSobject objQueueSobject,objQueueSobject_Ng;
        User objUser = [select id from user where profileid=:profileId and isActive=true limit 1];
        
        System.runAs(objUser){
            /** Creating a public Group **/     
            Group objPublicGrp = new Group();
            objPublicGrp.name='test';
            insert objPublicGrp;
            
            /** Creating a Group member and assigning it to the above created Group **/
            GroupMember objGrpMember =new GroupMember();
            objGrpMember.userorgroupid=userinfo.getuserid();
            objGrpMember.groupid=objPublicGrp.id;
            insert objGrpMember;
            
            /** Creating a Queue for Positive test case**/
            objPublicGrp_Queue = new group();
            objPublicGrp_Queue.name='test2';
            objPublicGrp_Queue.type='Queue';
            insert objPublicGrp_Queue;
            
        }
        
        System.runAs(objUser){
            
            /** Creating a QueueSobject to give permission to queue created above of SOC Queue object **/
            objQueueSobject =new queuesobject();
            objQueueSobject.sobjecttype='Contact_Validation_Summary__c';
            objQueueSobject.QueueId=objPublicGrp_Queue.id;
            insert objQueueSobject;
            
        }
        
        /** Creating Account record **/
        Account accObj = new Account();
        accObj.name = 'Test Account';
        insert accObj;
        
        /** Fetching the Provider Recordtype of Contact **/
        RecordType rtObj = new RecordType();
        rtObj = [SELECT id, name FROM recordtype WHERE name='Provider' and SObjectType='Contact' limit 1];
        
        /** Creating List of Contacts to insert Contacts **/
        list<contact> conList = new list<contact>();
        
        conList.add(new contact(
            accountId = accObj.id,
            lastName = 'Provider',
            firstName = 'Test',
            Provider_Name__c = 'Test Provider',
            Provider_Title__c = 'Mr.',
            recordTypeId = rtObj.id,
            email = 'test@test.com',
            Provider_Correspondence_Address__c = '123',
            Provider_Correspondence_City__c = 'CA',
            Provider_Correspondence_State__c = 'CA',
            Provider_Correspondence_PostalCode__c = '12345',
            Provider_Correspondence_Phone__c = '2345678901',
            Provider_Correspondence_Fax_Number__c = '2345678901',
            MobilePhone = '2345678901',
            Contact_External_ID1__c = '1234'
        ));
        
        conList.add(new contact(
            accountId = accObj.id,
            Provider_Name__c = 'Test Provider',
            Provider_Title__c = 'Mr.',
            lastName = 'Provider',
            firstName = 'Test',
            recordTypeId = rtObj.id,
            Provider_Correspondence_Address__c = '123',
            Provider_Correspondence_City__c = 'CA',
            Provider_Correspondence_State__c = 'CA',
            Provider_Correspondence_PostalCode__c = '12345',
            Provider_Correspondence_Phone__c = '2345678901',
            Provider_Correspondence_Fax_Number__c = '2345678901',
            MobilePhone = '2345678901',
            Contact_External_ID1__c = '12345'
        ));
        
        insert conList;   
        
        /*********************************************************************** 
Verifying the values of custom Settings and contacts using system.assert() 
Expected Result: values should not be null for the custom Setting records and contact records
Actual Result: values should not be null for the custom Setting records and contact records
***********************************************************************/
        system.assert(CSMCommunities_Portal!=null);
        system.assert(CSMCommunities_Provider!=null);
        system.assert(CSMCommunity_Portal_Manager!=null);
        system.assert(conList[1]!=null);    
    }
    
    /*******************************************************************
Purpose: method to create contact validation summary and check the logic written in ProviderSummaryTriggerBkup(trigger)  
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    
    public static testMethod void providerSummaryTrigger_Test(){
        
        /** Fetching the queue created above, in test data method**/
        Group objPublicGrp_Queue = [select id from Group where type='Queue' and name='test2'];
        
        list<contact> conList = [select id from Contact where Contact_External_ID1__c like '%123%'];
        
        Test.startTest();   
        
        /** Deleting the existing Summary record for the Contact to cover all scenarios and test the logic **/
        List<Contact_Validation_Summary__c> cvsObject = [select id from Contact_Validation_Summary__c where contact_id__c=:conlist[0].id];
        delete cvsObject;        
        
        /** Creating a new Summary Record to cover the insertion scenario **/
        Contact_Validation_Summary__c cvsObjectSecondary = new Contact_Validation_Summary__c();
        cvsObjectSecondary.Contact_Id__c = [select id from contact where Contact_External_ID1__c = '1234'].id;
        cvsObjectSecondary.Preferred_Communication_Method__c= 'email';
        cvsObjectSecondary.Address_Type__c = 'Secondary';
        cvsObjectSecondary.Serial_Number__c = null;
        cvsObjectSecondary.Validation_Source_Channel__c = 'test1';
        cvsObjectSecondary.ownerid = objPublicGrp_Queue.id;
        insert cvsObjectSecondary;
        System.assert(cvsObjectSecondary.Id != null);
        
        /** Updating the Summary record to cover updation scenario of owner change **/
        cvsObjectSecondary.Validation_Source_Channel__c = 'test2';
        cvsObjectSecondary.Serial_Number__c = null;
        cvsObjectSecondary.ownerid= userinfo.getuserid();
        update cvsObjectSecondary;
        System.assertEquals('Secondary', cvsObjectSecondary.Address_Type__c);
        /*********************************************************************** 
Verifying the value using system.assert() 
Expected Result: Serial number on Summary should be null
Actual Result: Serial number on Summary should be null
***********************************************************************/
        system.assertEquals(cvsObjectSecondary.Serial_Number__c ,null);
        
        /** Creating  a new Summary record for the Contact to cover insertion logic for all conditions **/
        Contact_Validation_Summary__c cvsObjSecondary = new Contact_Validation_Summary__c();
        cvsObjSecondary.Contact_Id__c = conlist[0].id;
        cvsObjSecondary.Preferred_Communication_Method__c= 'email';
        cvsObjSecondary.Address_Type__c = 'Secondary';
        cvsObjSecondary.Serial_Number__c = null;
        insert cvsObjSecondary;
        System.assert(cvsObjSecondary.Id != null);
        Contact_Validation_Summary__c cvsObj = new Contact_Validation_Summary__c();
        cvsobj = [SELECT id FROM Contact_Validation_Summary__c WHERE contact_id__c = :conlist[0].id limit 1];
        cvsObj.Preferred_Communication_Method__c= 'email';
        update cvsObj;
        System.assert(cvsObj.Id != null);
        Test.stopTest();  
        
        
        
    }
    
    /*******************************************************************
Purpose: method to create contact validation summary and check the logic written in ProviderSummaryTriggerBkup(trigger) for bulk scenarios 
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    
    public static testMethod void providerSummaryTrigger_BulkTest(){
        
        List<Contact_Validation_Summary__c> lstSummariesIns =new List<Contact_Validation_Summary__c>();
        List<Contact_Validation_Summary__c> lstsummariesUpd =new List<Contact_Validation_Summary__c>();
        
        
        /** Fetching the queue created above, in test data method**/
        Group objPublicGrp_Queue = [select id from Group where type='Queue' and name='test2'];
        
        list<contact> conList = [select id from Contact where Contact_External_ID1__c like '%123%'];
        
        Test.startTest();   
        
        /** Deleting the existing Summary record for the Contact to cover all scenarios and test the logic **/
        List<Contact_Validation_Summary__c> cvsObject = [select id from Contact_Validation_Summary__c where contact_id__c=:conlist[0].id];
        delete cvsObject;        
        
        /** Creating  new Summary Records to cover the insertion scenario **/
        for(Integer i=1;i<=200;i++){
            Contact_Validation_Summary__c cvsObjectSecondary = new Contact_Validation_Summary__c();
            cvsObjectSecondary.Contact_Id__c = conList[0].id;
            cvsObjectSecondary.Preferred_Communication_Method__c= 'email';
            cvsObjectSecondary.Address_Type__c = 'Secondary';
            cvsObjectSecondary.Serial_Number__c = null;
            cvsObjectSecondary.Validation_Source_Channel__c = 'test1';
            cvsObjectSecondary.ownerid = objPublicGrp_Queue.id;
            lstSummariesIns.add(cvsObjectSecondary);
        }
        
        insert lstSummariesIns;
        System.assert(lstSummariesIns.size() > 0);
        for(Contact_Validation_Summary__c cvsObjectSecondary:lstSummariesIns){
            
            /** Updating the Summary record to cover updation scenario of owner change **/
            cvsObjectSecondary.Validation_Source_Channel__c = 'test2';
            cvsObjectSecondary.Serial_Number__c = null;
            cvsObjectSecondary.ownerid= userinfo.getuserid();
            lstsummariesUpd.add(cvsObjectSecondary);
        }
        update lstsummariesUpd;
        System.assert(!lstsummariesUpd.isEmpty());
        /*********************************************************************** 
Verifying the value using system.assert() 
Expected Result: Serial number on Summary should be null
Actual Result: Serial number on Summary should be null
***********************************************************************/
        Contact_Validation_Summary__c objSummary = lstsummariesUpd[0];
        system.assertEquals(objSummary.Serial_Number__c ,null);
        
        /** Creating  a new Summary record for the Contact to cover insertion logic for all conditions **/
        Contact_Validation_Summary__c cvsObjSecondary = new Contact_Validation_Summary__c();
        cvsObjSecondary.Contact_Id__c = conlist[0].id;
        cvsObjSecondary.Preferred_Communication_Method__c= 'email';
        cvsObjSecondary.Address_Type__c = 'Secondary';
        cvsObjSecondary.Serial_Number__c = null;
        insert cvsObjSecondary;
        System.assert(cvsObjSecondary.Id != null);
        Contact_Validation_Summary__c cvsObj = new Contact_Validation_Summary__c();
        cvsobj = [SELECT id FROM Contact_Validation_Summary__c WHERE contact_id__c = :conlist[0].id limit 1];
        cvsObj.Preferred_Communication_Method__c= 'email';
        update cvsObj;
        System.assert(cvsObj.Id != null);
        Test.stopTest();  
        
        
        
    }
    
    /*******************************************************************
Purpose: Negative test method to create contact validation summary and check the logic written in ProviderSummaryTriggerBkup(trigger)  by not populating the contact lookup and providing data not processed by the trigger
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    
    public static testMethod void providerSummaryTrigger_NegativeTest(){
        
        /** Fetching the queue created above, in test data method**/
        Group objPublicGrp_Queue = [select id from Group where type='Queue' and name='test2'];
        
        list<contact> conList = [select id from Contact where Contact_External_ID1__c like '%123%'];
        
        Test.startTest();   
        
        /** Deleting the existing Summary record for the Contact to cover all scenarios and test the logic **/
        List<Contact_Validation_Summary__c> cvsObject = [select id from Contact_Validation_Summary__c where contact_id__c=:conlist[0].id];
        delete cvsObject;        
        
        /** Creating a new Summary Record to cover the insertion scenario **/
        Contact_Validation_Summary__c cvsObjectSecondary = new Contact_Validation_Summary__c();
        cvsObjectSecondary.Preferred_Communication_Method__c= 'email';
        cvsObjectSecondary.Address_Type__c = 'Secondary';
        cvsObjectSecondary.Serial_Number__c = null;
        cvsObjectSecondary.Validation_Source_Channel__c = 'test1';
        cvsObjectSecondary.ownerid = objPublicGrp_Queue.id;
        insert cvsObjectSecondary;
        System.assert(cvsObjectSecondary.Id != null);
        /** Updating the Summary record to cover updation scenario of owner change **/
        cvsObjectSecondary.Validation_Source_Channel__c = 'test2';
        cvsObjectSecondary.Serial_Number__c = null;
        cvsObjectSecondary.ownerid= userinfo.getuserid();
        update cvsObjectSecondary;
        System.assert(cvsObjectSecondary.Id != null);
        /*********************************************************************** 
Verifying the value using system.assert() 
Expected Result: Serial number on Summary should be null
Actual Result: Serial number on Summary should be null
***********************************************************************/
        system.assertEquals(cvsObjectSecondary.Serial_Number__c ,null);
        
        Test.stopTest();  
        
    }
    
    /*******************************************************************
Purpose: method to test providers by phone number helper class
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    public static testMethod void providersByPhoneNumberHelper_Test(){
        CreatedDate__c createdDate = Util01_PDIUtilTestData.insertCreatedDateCustSetting();
        PDIProviderSearch__c providerSearch = Util01_PDIUtilTestData.insertProviderSearchSetting();
        PDICallCampaignEmail__c callCampaign = Util01_PDIUtilTestData.insertCallCampaignSetting();
        List<Contact> cList = Util01_PDIUtilTestData.CreateDupPhoneContacts();
        
        List<Contact> cListToUpdate = new List<Contact>();
        for(Contact c: cList){
            if(c.LastName == 'Test0' || c.LastName == 'Test1'){
                cListToUpdate.add(c);
            }
        }
        insert cListToUpdate;
        
        List<ProvidersByPhoneNumber__c> phoneList = new List<ProvidersByPhoneNumber__c>();
        phoneList = [Select Tech_Phone_Number__c from ProvidersByPhoneNumber__c Limit 1];
        
        List<contact_validation_summary__c> sList = new List<contact_validation_summary__c>();
        sList = [Select Id, Tech_Phone_Number__c, Provider_LastName__c from contact_validation_summary__c Limit 1];
        contact_validation_summary__c sum = sList[0];
        sum.Secure_Phone__c = '9767564456';
        sum.Tech_Phone_Number__c = '9767564456';
        
        Test.startTest();
        update sum;
        System.assert(sum.Id != null);
        Test.stopTest();
    }
    /*******************************************************************
Purpose: method to test providers by phone number helper class
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    public static testMethod void providersByPhoneNumberHelperAccepted_Test(){
        CreatedDate__c createdDate = Util01_PDIUtilTestData.insertCreatedDateCustSetting();
        PDIProviderSearch__c providerSearch = Util01_PDIUtilTestData.insertProviderSearchSetting();
        PDICallCampaignEmail__c callCampaign = Util01_PDIUtilTestData.insertCallCampaignSetting();
        List<Contact> cList = Util01_PDIUtilTestData.CreateDupPhoneContacts();
        
        List<Contact> cListToUpdate = new List<Contact>();
        for(Contact c: cList){
            if(c.LastName == 'Test0' || c.LastName == 'Test1'){
                cListToUpdate.add(c);
            }
        }
        insert cListToUpdate;
        System.assert(!cListToUpdate.isEmpty());
        List<ProvidersByPhoneNumber__c> phoneList = new List<ProvidersByPhoneNumber__c>();
        phoneList = [Select Tech_Phone_Number__c from ProvidersByPhoneNumber__c Limit 1];
        
        List<contact_validation_summary__c> sList = new List<contact_validation_summary__c>();
        List<contact_validation_summary__c> sumList = new List<contact_validation_summary__c>();
        sList = [Select Id, Tech_Phone_Number__c, Provider_LastName__c from contact_validation_summary__c Limit 2];
        for(contact_validation_summary__c sum: sList){
            if(sum.Provider_LastName__c == 'Test0'){
                sum.Secure_Phone__c = '9676561568';
                sum.Tech_Phone_Number__c = '9676561568'; 
                sum.Status__c = 'Accepted';
            }
            else if(sum.Provider_LastName__c == 'Test1'){
                sum.Secure_Phone__c = '9767364456';
                sum.Tech_Phone_Number__c = '9767364456'; 
                sum.Status__c = 'Accepted';
            }
            sumList.add(sum);
        }
        Test.startTest();
        update sumList;
        System.assert(sumList != null);
        Test.stopTest();
    }
    /*******************************************************************
Purpose: method to test providers by phone number helper class
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    public static testMethod void providersByPhoneNumberHelperValidated_Test(){
        CreatedDate__c createdDate = Util01_PDIUtilTestData.insertCreatedDateCustSetting();
        PDIProviderSearch__c providerSearch = Util01_PDIUtilTestData.insertProviderSearchSetting();
        PDICallCampaignEmail__c callCampaign = Util01_PDIUtilTestData.insertCallCampaignSetting();
        List<Contact> cList = Util01_PDIUtilTestData.CreateDupPhoneContacts();
        
        List<Contact> cListToUpdate = new List<Contact>();
        for(Contact c: cList){
            if(c.LastName == 'Test0' || c.LastName == 'Test1'){
                cListToUpdate.add(c);
            }
        }
        insert cListToUpdate;
        
        List<ProvidersByPhoneNumber__c> phoneList = new List<ProvidersByPhoneNumber__c>();
        phoneList = [Select Tech_Phone_Number__c from ProvidersByPhoneNumber__c Limit 1];
        ProvidersByPhoneNumber__c ph = phoneList[0];        
        List<contact_validation_summary__c> sList = new List<contact_validation_summary__c>();
        List<contact_validation_summary__c> sumList = new List<contact_validation_summary__c>();
        
        sList = [Select Id, Tech_Phone_Number__c, Provider_LastName__c from contact_validation_summary__c Limit 2];
        for(contact_validation_summary__c sum: sList){
            if(sum.Provider_LastName__c == 'Test0'){
                sum.Secure_Phone__c = '9676561568';
                sum.Tech_Phone_Number__c = '9676561568'; 
                sum.Status__c = 'Validated';
            }
            else if(sum.Provider_LastName__c == 'Test1'){
                sum.Secure_Phone__c = '9767364456';
                sum.Tech_Phone_Number__c = '9767364456'; 
                sum.Status__c = 'Validated';
            }
            sumList.add(sum);
        }
        
        Test.startTest();
        update sumList;
        System.assert(sumList!= null);
        Test.stopTest();
    }
    /*******************************************************************
Purpose: method to test providers by phone number helper class
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    public static testMethod void providersByPhoneNumberHelperPhoneChange_Test(){
        CreatedDate__c createdDate = Util01_PDIUtilTestData.insertCreatedDateCustSetting();
        PDIProviderSearch__c providerSearch = Util01_PDIUtilTestData.insertProviderSearchSetting();
        PDICallCampaignEmail__c callCampaign = Util01_PDIUtilTestData.insertCallCampaignSetting();
        List<Contact> cList = Util01_PDIUtilTestData.CreateDupPhoneContacts();
        
        List<Contact> cListToUpdate = new List<Contact>();
        for(Contact c: cList){
            if(c.LastName == 'Test0' || c.LastName == 'Test1'){
                cListToUpdate.add(c);
            }
        }
        insert cListToUpdate;
        
        List<ProvidersByPhoneNumber__c> phoneList = new List<ProvidersByPhoneNumber__c>();
        phoneList = [Select Tech_Phone_Number__c from ProvidersByPhoneNumber__c Limit 1];
        
        List<contact_validation_summary__c> sList = new List<contact_validation_summary__c>();
        List<contact_validation_summary__c> sumList = new List<contact_validation_summary__c>();
        sList = [Select Id, Tech_Phone_Number__c, Provider_LastName__c from contact_validation_summary__c Limit 2];
        for(contact_validation_summary__c sum: sList){
            if(sum.Provider_LastName__c == 'Test0'){
                sum.Secure_Phone__c = '19767564456';
                sum.Tech_Phone_Number__c = '19767564456'; 
            }
            else if(sum.Provider_LastName__c == 'Test1'){
                sum.Secure_Phone__c = '9767364456';
                sum.Tech_Phone_Number__c = '9767364456'; 
                sum.Status__c = 'Accepted';
            }
            sumList.add(sum);
        }
        Test.startTest();
        update sumList;
        System.assert(!sumList.isEmpty());
        Test.stopTest();
    }
}