Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Broker_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker Rep</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.Field- Account Broker Rep</errorMessage>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SHMMN, System Administrator, Integration</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>contains</operation>
                <value>SHMMN Broker, SHP Sales Broker Contact</value>
            </filterItems>
            <filterItems>
                <field>Contact.Archive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SHP,Integration</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employers</relationshipLabel>
        <relationshipName>Employers</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broker1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a Broker</inlineHelpText>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4)</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.Field- Broker</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>SHP Sales Broker,SHP Sales Broker Read Only, SHMMN Broker</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>Contracted, Prospect, Active</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SHMMN, System Administrator, SHP</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Rep1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a Broker Rep</inlineHelpText>
        <label>Broker Rep</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria. Field- Broker Rep</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Broker1__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Broker_Agent_Status__c</field>
                <operation>equals</operation>
                <value>a,Active, Prospect, Contracted</value>
            </filterItems>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>equals</operation>
                <value>Broker Rep, Agent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Archive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SHMMN, System Administrator, SHP</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>contains</operation>
                <value>SHMMN Broker, SHP Sales Broker Contact,SHP Sales Broker Contact Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Rep__c</fullName>
        <formula>Account.Broker_Rep__r.FirstName &amp; &quot; &quot; &amp; Account.Broker_Rep__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <formula>Account.Broker__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latest_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will be true only if the Opportunity is Latest Modified with Latest Plan End Date and Effective Date.</description>
        <label>Latest Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideBrokerAndBrokerRep__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check &quot;OverrideBrokerAndBrokerRep&quot; field , if &quot;Broker&quot; &amp; &quot;Broker Rep&quot; field is changed On Opportunity record and want to apply these changed values on Account record.</inlineHelpText>
        <label>OverrideBrokerAndBrokerRep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Effective_Date__c</fullName>
        <label>Plan Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_end_date__c</fullName>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/SelectLatestOpportunity.cls
/**    
 *     Class Name  : SelectLatestOpportunity
 *     Author      : IDC Offshore  
 *     Date        : 10-Jul-2015  
 *     Project Name: CRM - SFT - Sutter Health  
 *     Description : This class is a helper class for the setting the latest Updated and Inserted Opportunity 
                     boolean true on Opportunity Record for reporting purpose.
 **/
public class SelectLatestOpportunity {
/**
    * @author IDC Team
    * @date 10/07/2015
    * @description -- This method is used to Mark the checkbox Latest Updated Opportunity of Account 
                      so that it can be selected for the Reporting Purpose.
    * @Requirement : Req-3392 Sales Report
    */
   public static void selectLatestUpdatedOpportunity( List <Opportunity> newOpportunityList) {
       
       
        if( checkRecursive.runOnce() ) {
            Set <Id> AccountIdList = new Set<Id>();
            Set <Id> AccountIdSet = new Set <Id>();
            List <Opportunity> opportunityToupdate = new List<Opportunity>();
            
        /**
        *@Description: For loop to collect Corresponding AccountId of Opportunities in List.
        **/
            for( Opportunity opnew: newOpportunityList ) {
                if( opnew.AccountId != null ) {
                    AccountIdList.add( opnew.AccountId );
                }
            }
        /**
        *@Description: Select the Latest Updatet Opportunity for Particular Account and set its boolean true.
        **/            
            if(!(AccountIdList.isEmpty())) {
                for( Account acnt:[ SELECT Id,Broker__c,Broker_Rep__c , (SELECT Id,Name, Plan_end_date__c,OverrideBrokerAndBrokerRep__c,Broker1__c,Broker_Rep1__c ,Latest_Opportunity__c,Plan_Effective_Date__c , LastModifiedDate From Opportunities ORDER BY Plan_Effective_Date__c DESC NULLS LAST,Plan_end_date__c DESC NULLS LAST, LastModifiedDate DESC NULLS LAST Limit 1 ) FROM Account WHERE ID IN :AccountIdList]) {
                    if( acnt.Opportunities != null && !(acnt.Opportunities.isEmpty())) {
                        if( acnt.Opportunities[0].Latest_Opportunity__c == false ) {
                            acnt.Opportunities[0].Latest_Opportunity__c = true;
                            opportunityToupdate.add(acnt.Opportunities[0]);
                            AccountIdSet.add(acnt.Id);
                        }
                    }
                }
            }
            
        /**
        *@Description: Set the Previous Updated Opportunitie's boolean to false.
        **/         
            if(!(AccountIdSet.isEmpty())) {
                for(Opportunity oppy: [ SELECT Id,Latest_Opportunity__c FROM Opportunity WHERE AccountId IN :AccountIdSet AND Latest_Opportunity__c = true ]) {
                        oppy.Latest_Opportunity__c = false;
                        opportunityToupdate.add(oppy);
                    }
                }
                    
            if(!(opportunityToupdate.isEmpty())) {
                try {
                    system.debug('@@@Opportunity'+opportunityToupdate);
                    update opportunityToupdate;
                } Catch ( Exception ex ) {
                    Utility.handleExceptionFromCode(ex.getMessage() + '\r\n' + ex.getStackTraceString() + '\r\n' + ex.getTypeName() + '\r\n' + System.now() + '\r\n' + '--------------');
                }
            }
        }
    }
}