Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Employer_Group_Data__c.object
<CustomObject>
    <description>This object is created for SCN and develop Req -3268
 It split into three parts
1.Sold case Notifaction
2. Medical Plan
3.Non standard medical plan</description>
    <fields>
        <fullName>Cloned_from__c</fullName>
        <inlineHelpText>Please do not change this field.</inlineHelpText>
        <label>Cloned from</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to implement the Lookup filter on Contact. It will be autopopulated with the Opportunity&apos;s Account Name. DO NOT Put on page layout</description>
        <inlineHelpText>Please do not change the Opportunity Account Name value</inlineHelpText>
        <label>Opportunity Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sold Case Notification</relationshipLabel>
        <relationshipName>Sold_Case_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sold Case Notification</relationshipLabel>
        <relationshipName>Sold_Case_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_Case_Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Case Notification</label>
        <referenceTo>Employer_Group_Data__c</referenceTo>
        <relationshipLabel>Sold Case Notification</relationshipLabel>
        <relationshipName>Sold_Case_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Underwriting Review</fullName>
                </value>
                <value>
                    <fullName>Rejected by Underwriting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Enrollment QA Pass</fullName>
                </value>
                <value>
                    <fullName>Enrollment QA Fail</fullName>
                </value>
                <value>
                    <fullName>Submitted for QA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sold Case Notification</label>
    <nameField>
        <displayFormat>SCN-{00000}</displayFormat>
        <label>Sold Case Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sold Case Notification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Status__c</fullName>
        <description>Status of the Opportunity</description>
        <inlineHelpText>Select an Opportunity Status</inlineHelpText>
        <label>PPO Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Underwriting Decision</fullName>
                </value>
                <value>
                    <fullName>Underwriting - Mid/Large Group</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opp_Renewed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Req 3268  -- Checked means the renewal opportunity has been created for this.</description>
        <label>Renewal Opportunity Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_end_date__c</fullName>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Team__c</fullName>
        <label>Sales Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RGA</fullName>
                </value>
                <value>
                    <fullName>PBJ</fullName>
                </value>
                <value>
                    <fullName>M2N</fullName>
                </value>
                <value>
                    <fullName>BAY</fullName>
                </value>
                <value>
                    <fullName>SHP</fullName>
                </value>
                <value>
                    <fullName>TSS</fullName>
                </value>
                <value>
                    <fullName>SHMMN</fullName>
                </value>
                <value>
                    <fullName>Amy Schenone</fullName>
                </value>
                <value>
                    <fullName>Gary Kaye</fullName>
                </value>
                <value>
                    <fullName>Kim McAndrew</fullName>
                </value>
                <value>
                    <fullName>Sondra Maas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/SCN_CustomTrackfieldPageController_Test.cls
/*_______________________________________________________________________________________________________________________________________________________________
 * 
 * Class Name   : SCN_CustomTrackfieldPageController
 * Created by   : Deloitte 
 * Date         : 16/03/2017
 * User Story   : SFSHP-5
 * Description  : The below class is the test class for SCN_CustomTrackfieldPageController
 * 
 * Change Log
 * _______________________________________________________________________________________________________________________________________________________________
 * Name         Date        Userstory       Description
 * _______________________________________________________________________________________________________________________________________________________________
 * 
 * _______________________________________________________________________________________________________________________________________________________________
 * ______________________________________________________________________________________________________________________________________________________________*/
@isTest
private class SCN_CustomTrackfieldPageController_Test 
{
    static testMethod void Method_1()
    {
        Account Acc_1 = new Account(Name='Acc_1',Status__c= 'Contracted',NumberOfEmployees = 300);
        
        insert Acc_1;
        Opportunity Opp_1 = new Opportunity(Name = 'Opp_1',Type = 'New Business',AccountId = Acc_1.Id,StageName = 'Closed Won',Amount = 450,
                                            CloseDate = Date.today()+25,Plan_end_date__c = Date.today()+110,Current_Status__c = 'Information Requested',Opp_Renewed__c =false,
                                            RecordTypeID = System.label.SHP_Sales_Opportunity_Id,Sales_Team__c = 'TSS');
                                                       
        insert Opp_1;
        Employer_Group_Data__c SCN_1 = new Employer_Group_Data__c(Opportunity__c = Opp_1.Id,Stage__c = 'Completed',Opportunity_Account_Name__c = Acc_1.Id,Group_Type__c = 'Small',
                                                                 County__c = 'Canada');
                                                                    
        insert SCN_1;
        Employer_Group_Data__c SCN_2 = SCN_1.clone();
        SCN_2.Cloned_from__c = [select Name from Employer_Group_Data__c where ID =: SCN_1.ID].Name;
        SCN_2.Phone_Number__c = '1234';
        SCN_2.Group_Type__c = 'Individual';
        SCN_2.County__c = null;
        insert SCN_2;
        
        system.debug('### SCN_2 : '+SCN_2);
        system.debug('### SCN_2 : '+SCN_2.Cloned_from__c);
        system.debug('### SCN_2 : '+SCN_2.Sold_Case_Notification__c);
        ApexPages.StandardController SC = new ApexPages.StandardController(SCN_2);
        SCN_CustomTrackfieldPageController S = new SCN_CustomTrackfieldPageController(SC);
    }
}