Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CVR</fullName>
                </value>
                <value>
                    <fullName>EBR</fullName>
                </value>
                <value>
                    <fullName>PCR</fullName>
                </value>
                <value>
                    <fullName>SSR</fullName>
                </value>
                <value>
                    <fullName>WBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Account_Employee_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employee Distribution</relationshipLabel>
        <relationshipName>Account_Employee_Distributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>County_Percent__c</fullName>
        <label>County Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>San Joaquin</fullName>
                </value>
                <value>
                    <fullName>Stanislaus</fullName>
                </value>
                <value>
                    <fullName>Merced</fullName>
                </value>
                <value>
                    <fullName>Alameda</fullName>
                </value>
                <value>
                    <fullName>Contra Costa</fullName>
                </value>
                <value>
                    <fullName>San Mateo</fullName>
                </value>
                <value>
                    <fullName>Santa Clara</fullName>
                </value>
                <value>
                    <fullName>Santa Cruz</fullName>
                </value>
                <value>
                    <fullName>El Dorado</fullName>
                </value>
                <value>
                    <fullName>Placer</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Solano</fullName>
                </value>
                <value>
                    <fullName>Sutter</fullName>
                </value>
                <value>
                    <fullName>Yolo</fullName>
                </value>
                <value>
                    <fullName>Amador</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>Sonoma</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>Marin</fullName>
                </value>
                <value>
                    <fullName>Napa</fullName>
                </value>
                <value>
                    <fullName>Lake</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SSR</fullName>
                </value>
                <value>
                    <fullName>CVR</fullName>
                </value>
                <value>
                    <fullName>EBR</fullName>
                </value>
                <value>
                    <fullName>PCR</fullName>
                </value>
                <value>
                    <fullName>WBR</fullName>
                </value>
                <value>
                    <fullName>OOSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Employee Distribution</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>ED Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Distribution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sutter Health/src/classes/EmployeeDistribution_Test.cls
@isTest
public class EmployeeDistribution_Test{

    static testMethod void insertDuplicateEmpDist()
    {
		String errorMessage;
		Boolean isError = false;
		
    	try
			{
				Account acc = AP01_TestDataUtility.createSalesEmployerAccount();
				
				Account_Employee_Distribution__c empDist = AP01_TestDataUtility.createEmpDist(acc);
				
				Account_Employee_Distribution__c emp = new Account_Employee_Distribution__c();
				
				emp.Account__c = acc.id;
				emp.Region__c = 'SSR';
				emp.County__c = 'El Dorado';
				emp.County_Percent__c = 2;
				
				insert emp;
				
			} catch(Exception ex)
			{
				errorMessage = ex.getMessage();
				system.debug('@@Error Message : '+ ex.getMessage());
			}
		
		if(errorMessage.contains('Record already exists with same Region and County'))
		{
			isError = true;
		}
		
		system.assertEquals(isError, true);
    }
	
	static testMethod void updateDuplicateEmpDist()
    {
		String errorMessage;
		Boolean isError = false;
		
    	try
			{
				Account acc = AP01_TestDataUtility.createSalesEmployerAccount();
				
				Account_Employee_Distribution__c empDist = AP01_TestDataUtility.createEmpDist(acc);
				
				Account_Employee_Distribution__c emp = new Account_Employee_Distribution__c();
				
				emp.Account__c = acc.id;
				emp.Region__c = 'SSR';
				emp.County__c = 'Placer';
				emp.County_Percent__c = 2;
				
				insert emp;
				
				emp.County__c = 'El Dorado';
				update emp;
				
			} catch(Exception ex)
			{
				errorMessage = ex.getMessage();
				system.debug('@@Error Message : '+ ex.getMessage());
			}
		
		if(errorMessage.contains('Record already exists with same Region and County'))
		{
			isError = true;
		}
		
		system.assertEquals(isError, true);
    }
}