Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Record type for S3 Providers</description>
        <label>S3 Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Employee</fullName>
        <active>true</active>
        <description>Used for employee contact records.</description>
        <label>Employee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for provider contact records.</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/MU_Object__c.object
<CustomObject>
    <description>MU Object : Proxy object for Case records</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>MU Objects</relationshipLabel>
        <relationshipName>MU_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>MU comments proxy field</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Escalation_Status__c</fullName>
        <label>Escalation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cannot send documents to Provider</fullName>
                </value>
                <value>
                    <fullName>Send Documents To Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Proxy field for Case Status field on SOC Case layout</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Cannot Reach</fullName>
                </value>
                <value>
                    <fullName>Closed (Closed)</fullName>
                </value>
                <value>
                    <fullName>Escalate to Meaningful Use</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MU Object</label>
    <nameField>
        <displayFormat>MU-{000000}</displayFormat>
        <label>MU Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MU Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/TRG_MU_Object_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TRG_MU_Object_Test {

    static testMethod void createTestData(){
    
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('S3 Employee').getRecordTypeId();
        insert acc;
        // Assert to check Account is created successfully
        system.assert(acc.id!=null);
        
        Contact con = new Contact();
        con.LastName = 'Test LastName';
        con.RecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
        con.AccountId = acc.id;
        insert con;
        // Assert to check Contact is created successfully
        system.assert(con.id!=null);
        
        Case newCase = new Case();
        newCase.RecordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Summary of Care').getRecordTypeId();
        //newCase.name = 'test case';
        newCase.ContactId = con.id;
        insert newCase;
        // Assert to check Case is created  successfully
        system.assert(newCase.id!=null);
        
        MU_Object__c mu = new MU_Object__c();
        mu.Status__c = 'In Progress';
        mu.Comments__c = 'Test Comments';
        mu.Escalation_Status__c = 'Cannot send documents to Provider';
        mu.Case__c = newCase.id;
        insert mu;
        // Assert to check MU_Object__c is created  successfully
        system.assert(mu.id!=null);
    }
}