Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CVR</fullName>
                </value>
                <value>
                    <fullName>EBR</fullName>
                </value>
                <value>
                    <fullName>PCR</fullName>
                </value>
                <value>
                    <fullName>SSR</fullName>
                </value>
                <value>
                    <fullName>WBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Census__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_Zip__c</fullName>
        <label>Employee Zip</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format_Match_Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Format Match Boolean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Censuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>To show whether the census record is errored or success.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Errored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SHP Census</label>
    <nameField>
        <displayFormat>Census-{000000}</displayFormat>
        <label>Census Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHP Censuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Status__c</fullName>
        <description>Status of the Opportunity</description>
        <inlineHelpText>Select an Opportunity Status</inlineHelpText>
        <label>PPO Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Underwriting Decision</fullName>
                </value>
                <value>
                    <fullName>Underwriting - Mid/Large Group</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text(Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Zip_Code_Master__c.object
<CustomObject>
    <fields>
        <fullName>County_1__c</fullName>
        <label>County 1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>IF(AND(ISBLANK( County_1__c) ,  ISBLANK(County_2__c) ,  ISBLANK(County_3__c )),null,
  IF(AND(ISBLANK( County_1__c) ,  ISBLANK(County_2__c)), County_3__c ,
    IF(AND(ISBLANK( County_1__c) ,  ISBLANK(County_3__c)), County_2__c ,
      IF(AND(ISBLANK( County_2__c) ,  ISBLANK(County_3__c)), County_1__c ,
        IF( ISBLANK( County_1__c ) ,  County_2__c  &amp; &apos; / &apos;  &amp; County_3__c  ,  
         IF( ISBLANK( County_2__c ) ,  County_1__c &amp; &apos; / &apos;  &amp;County_3__c ,  
          IF( ISBLANK( County_3__c ) ,  County_1__c &amp; &apos; / &apos;  &amp;County_2__c ,  
             County_1__c &amp; &apos; / &apos;  &amp; County_2__c &amp; &apos; / &apos;  &amp;County_3__c 
            ) 
           )
          )
         ) 
        )
       )
      )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_code__c</fullName>
        <label>Zip code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Zip Code Master</label>
    <nameField>
        <displayFormat>Z-{0000}</displayFormat>
        <label>Zip Code Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zip Codes Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/SHP_updateRegionOnCensus_Test.cls
/* 
     Class Name: SHP_updateRegionOnCensus_Test 
     Author: Haritha
     Date: 20-Apr-2016
     Description: Test class for SHP_updateRegionOnCensus Trigger.

*/
@isTest 

private class  SHP_updateRegionOnCensus_Test{
 
 private static Account acc;
 private static Opportunity opp;
 private static Census__c census , census1;
 private static   Zip_Code_Master__c zmaster , zmaster1;
 private static Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHP Sales Employer').getRecordTypeId();
 
 /*Method to Set up Test data*/
 
 public static TestMethod void setupTestData(){
    
    //Insert Account
    acc = new Account();
    acc.Name = 'Test Account';
    acc.RecordTypeId = accRecordTypeId;
    acc.NumberOfEmployees = 100;
    acc.Industry = 'Test Industry';
    insert acc;
    
    //Insert Opportunity
    opp = new Opportunity();
    opp.Name = 'Test Opportunity';
    opp.AccountId = acc.id;
    opp.type = 'Test type';
    opp.CloseDate = Date.Today();
    opp.StageName = 'Pending Broker';
    opp.Current_Status__c = 'No';
    insert opp;
    
    //Insert Zip Code master record
    zmaster = new Zip_Code_Master__c();
    zmaster.Zip_code__c = '94577'  ;
    zmaster.Region__c = 'East Bay';
    zmaster.County_1__c = 'Alameda' ;
  
    insert zmaster;
    
    //Insert SHP Census record
    census = new Census__c();
    census.Format_Match_Boolean__c = true;
    census.DOB__c = Date.today().addDays(-15);
    census.Opportunity__c = opp.id;
    census.Employee_Zip__c = '94577';
    
    insert census;
    
    //Update Census record
    
    census.Status__c = 'Successful';
    
    update census;
    
 }
 
 /* Test method to test the Region & County fields update on census for Valid Zip given */
 
 public static testMethod void TestRegionUpdate() 
 {
 
  Test.startTest();
  setupTestData();
  zmaster1 =[ Select id, Region__c, County__c, Zip_code__c from Zip_Code_Master__c where Zip_code__c = :census.Employee_Zip__c];
  census1 = [ Select id, Region__c, County__c,Employee_Zip__c from Census__c ];
  
  system.assertEquals(zmaster1.Region__c,census1 .Region__c);
  system.assertEquals(zmaster1.County__c,census1 .County__c);
  Test.stopTest(); 
  
 }
 
/* Test method to test the Region & County fields update on census for Invalid Zips given */

 public static testMethod void TestRegionUpdate1() 
 {
 
  Test.startTest();
  setupTestData();
  census.Employee_Zip__c = '77777';
  update census;
  
  census1 = [ Select id, Region__c, County__c,Employee_Zip__c from Census__c ];
  system.assertEquals(Label.SHP_Region_Value,census1.Region__c);
  system.assertEquals(Label.SHP_Region_Value,census1.County__c);
  Test.stopTest(); 
  
 } 
 
 /* Test method to test the Region & County fields update on census when updated in Zip code master */ 
 public static testMethod void TestRegionUpdate2() 
 {
 
  Test.startTest();
  setupTestData();
  
  zmaster.Zip_code__c = '94577';
  zmaster.Region__c = 'Bay';
  zmaster.County_1__c = 'Ala' ;
  update zmaster;
  
  census.Employee_Zip__c = '94577';
  //census.Zip_Code_Master__c = zmaster.id;
  update census;
  
  zmaster1 =[ Select id, Region__c, County__c, Zip_code__c from Zip_Code_Master__c where Zip_code__c = :census.Employee_Zip__c]; 
  census1 = [ Select id, Region__c, County__c,Employee_Zip__c from Census__c ];
  
  system.assertEquals(zmaster1.Zip_code__c,census1 .Employee_Zip__c);
  system.assertEquals(zmaster1.Region__c,census1 .Region__c);
  system.assertEquals(zmaster1.County__c,census1 .County__c);
  
  Test.stopTest(); 
  }
  
}