Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <label>Employer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calpers</fullName>
                </value>
                <value>
                    <fullName>Jumbo (&gt;1000)</fullName>
                </value>
                <value>
                    <fullName>Key Accounts</fullName>
                </value>
                <value>
                    <fullName>Labor and Trust</fullName>
                </value>
                <value>
                    <fullName>Large Group (251-1000)</fullName>
                </value>
                <value>
                    <fullName>Large Mid-Market Group (101 - 250)</fullName>
                </value>
                <value>
                    <fullName>Mid-Market Group (51-250)</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Small Group (1 - 50)</fullName>
                </value>
                <value>
                    <fullName>Small Group (2-50)</fullName>
                </value>
                <value>
                    <fullName>Small Mid-Market Group (51 - 100)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Association__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Plan_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Plan Metadata</label>
        <referenceTo>Benefit_Plan_Metadata__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Benefit Plan Association</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Metadata__c.object
<CustomObject>
    <label>Benefit Plan Metadata</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Document_Generation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>Text(Account__r.Employer_Type__c)</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expedite Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Document Generation Requests</relationshipLabel>
        <relationshipName>Document_Generation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Approved_Date__c</fullName>
        <label>Request Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Created_Date__c</fullName>
        <formula>CreatedDate</formula>
        <label>Request Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Due_Date__c</fullName>
        <label>Request Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <label>Request Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Documents Generated</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>has_Custom_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <label>has Custom Plans?</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Generation Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>Document Generation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Generation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>TEXT(Account.Employer_Type__c)</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/SF_P2A_Market_Segments_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HR_SF-P2A Market Segments Mapping</label>
</CustomObject>

Sutter Health/src/objects/SHP_Benefit_Grid__c.object
<CustomObject>
    <description>This Object is Used to capture the information related to Benefit Grid Data.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/DocGenRequest_Trigger_Test.cls
/* 
     Class Name: DocGenRequest_Trigger_Test 
     Author: IDC Offshore
     Date: 06-Dec-2016
     Description: Test class for DocGenRequest_Trigger Trigger.
*/
@isTest 
private class DocGenRequest_Trigger_Test {   
  
    private static Document_Generation_Request__c dgr,dgr1,dgr2;
    private static Account acc;
    private static Opportunity opp,opp1;
    private static Benefit_Plan_Association__c bpa;
    private static Benefit_Plan_Metadata__c bpm;
    private static SHP_Benefit_Grid__c grid;
    private static Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHP Sales Employer').getRecordTypeId();
  private static Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SHP Sales Opportunity').getRecordTypeId();
  
    private static testMethod void testController(){
        
        List<SF_P2A_Market_Segments_Mapping__c> p2aList = HighRoads_TestDataUtility.insertP2AMarketSegmentsCS();
        insert p2aList;
        
        acc = new Account();
        acc.Name = 'TestAcc1';
        acc.RecordTypeId = accRecordTypeId;
        acc.NumberOfEmployees = 50;
        acc.Industry = 'Hospitaity';
        acc.Employer_Type__c = 'Labor and Trust';
        insert acc;
        
        opp = new Opportunity();
        opp.Name = 'TestOpp1';
        opp.RecordTypeId = oppRecordTypeId;
        opp.AccountId = acc.id;
        opp.type = 'New Business';
        opp.CloseDate = Date.Today();
        opp.StageName = 'Closed Won';
        insert opp;
        
        dgr = new Document_Generation_Request__c();
    dgr.Opportunity__c =  opp.id;      
    dgr.Status__c = System.label.HR141_Draft; 
        dgr.Request_Status__c = System.label.HR141_Draft; 
        dgr.has_Custom_Plans__c = true;
        dgr.Expedite__c = false;
        insert dgr;
    
      Test.startTest();
    
             // BusinessHours busHours=[select id from BusinessHours where Name =:System.label.HR138_SHPBusinessHours limit 1];
          dgr.Status__c = System.label.HR139_OnHold;
          dgr.Request_Status__c = System.label.HR140_Approved;
          update dgr;
          dgr1 = [Select id, Request_Due_Date__c, Request_Approved_Date__c from Document_Generation_Request__c where Opportunity__c = :dgr.Opportunity__c];
          system.assertEquals(NULL,dgr1.Request_Due_Date__c);
          system.assertEquals(System.today(),dgr1.Request_Approved_Date__c);
          dgr.has_Custom_Plans__c = false;
            dgr.Expedite__c = false;
      dgr.Status__c = System.label.HR141_Draft;
          update dgr;
          /*dgr1 = [Select id, Request_Due_Date__c, Request_Created_Date__c from Document_Generation_Request__c where Opportunity__c = :dgr.Opportunity__c];
          system.assertEquals(Date.valueOf(BusinessHours.add(busHours.id,dgr1.Request_Created_Date__c,97200000)),dgr1.Request_Due_Date__c);*/
            dgr.Expedite__c = true;
          update dgr;
            dgr.Expedite__c = false;
          update dgr;
            
            dgr.Status__c = System.label.HR139_OnHold;
            dgr.Expedite__c = true;
          update dgr;
          system.assertEquals(NULL,dgr1.Request_Due_Date__c);
      dgr.Status__c = System.label.HR141_Draft;
          update dgr;
        
        Test.stopTest();
    }
}