Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <label>Employer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calpers</fullName>
                </value>
                <value>
                    <fullName>Jumbo (&gt;1000)</fullName>
                </value>
                <value>
                    <fullName>Key Accounts</fullName>
                </value>
                <value>
                    <fullName>Labor and Trust</fullName>
                </value>
                <value>
                    <fullName>Large Group (251-1000)</fullName>
                </value>
                <value>
                    <fullName>Large Mid-Market Group (101 - 250)</fullName>
                </value>
                <value>
                    <fullName>Mid-Market Group (51-250)</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Small Group (1 - 50)</fullName>
                </value>
                <value>
                    <fullName>Small Group (2-50)</fullName>
                </value>
                <value>
                    <fullName>Small Mid-Market Group (51 - 100)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Association__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Plan_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Plan Metadata</label>
        <referenceTo>Benefit_Plan_Metadata__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medical_or_Rider__c</fullName>
        <formula>IF(Raider_ID__c &lt;&gt; NULL,Raider_ID__r.Medical_OR_Rider__c,Benefit_Plan_Metadata__r.Medical_OR_Rider__c)</formula>
        <label>Medical or Rider</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <formula>Benefit_Plan_Metadata__r.Plan_Type__c</formula>
        <label>Plan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Year__c</fullName>
        <formula>IF( Raider_ID__c &lt;&gt; NULL , Raider_ID__r.Plan_Year__c, Benefit_Plan_Metadata__r.Plan_Year__c )</formula>
        <label>Plan Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <formula>IF(Raider_ID__c &lt;&gt; NULL,Raider_ID__r.Product_Class__c,Benefit_Plan_Metadata__r.Product_Class__c)</formula>
        <label>Product Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rider Plan Name</label>
        <referenceTo>Benefit_Plan_Metadata__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations (Raider ID)</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <label>Opportunity Benefit Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Benefit Plan Association</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Plan_ID__c</fullName>
        <label>Benefit Plan ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_OR_Rider__c</fullName>
        <label>Medical OR Rider</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Year__c</fullName>
        <label>Plan Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <label>Product Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <label>Version Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Benefit Plan Metadata</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Document_Generation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>Text(Account__r.Employer_Type__c)</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expedite Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Document Generation Requests</relationshipLabel>
        <relationshipName>Document_Generation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plans__c</fullName>
        <label>Plans</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <label>Request Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Documents Generated</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>has_Custom_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <label>has Custom Plans?</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Generation Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>Document Generation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Generation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Status__c</fullName>
        <description>Status of the Opportunity</description>
        <inlineHelpText>Select an Opportunity Status</inlineHelpText>
        <label>PPO Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Underwriting Decision</fullName>
                </value>
                <value>
                    <fullName>Underwriting - Mid/Large Group</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>TEXT(Account.Employer_Type__c)</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Year__c</fullName>
        <formula>TEXT(YEAR( Plan_Effective_Date__c ))</formula>
        <label>Plan Year</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/SF_P2A_Market_Segments_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HR_SF-P2A Market Segments Mapping</label>
</CustomObject>

Sutter Health/src/classes/HighRoads_OpporutnityHelperTest.cls
/* 
Class Name: HighRoads_OpporutnityHelperTest 
     Author: Deloitte
     Date: 19-4-2017
     Description: Test class for HighRoads_OpportunityHelper class.
*/
@isTest
private class HighRoads_OpporutnityHelperTest {
    @testSetup
    static void testData() {
        
        
        List<SF_P2A_Market_Segments_Mapping__c> p2aList = HighRoads_TestDataUtility.insertP2AMarketSegmentsCS();
        insert p2aList;
        
        //    New Collaboration Group
        CollaborationGroup chattergroup = new CollaborationGroup(Name = 'Test - ' + System.label.HR179_SHPBPAGroup, CollaborationType = 'Public');
        insert chatterGroup;
        
        
        
        //    New Account 
        Account accountS3BPA_Small_Group = new Account();
        accountS3BPA_Small_Group.RecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get('SHP Sales Employer').RecordTypeId; 
        accountS3BPA_Small_Group.Name = 'Account Small Group';
        accountS3BPA_Small_Group.Employer_Type__c = 'Small Group (1 - 50)';
        accountS3BPA_Small_Group.Status__c = 'Prospect';
        accountS3BPA_Small_Group.Industry = 'Healthcare';
        accountS3BPA_Small_Group.NumberOfEmployees = 12;
        insert accountS3BPA_Small_Group;
        
        // Verify the Account has been inserted successfully
        System.assertNotEquals(accountS3BPA_Small_Group.Id, NULL);
        
        //    New Opportunity 
        Opportunity oppS3BPA_Small_Group1 = new Opportunity();
        oppS3BPA_Small_Group1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SHP Sales Opportunity').getRecordTypeId();
        oppS3BPA_Small_Group1.Name = 'Opportunity Small Group 1';
        oppS3BPA_Small_Group1.Type = 'Existing Business';
        oppS3BPA_Small_Group1.AccountId = accountS3BPA_Small_Group.Id;
        oppS3BPA_Small_Group1.StageName =  'Pending Broker';
        oppS3BPA_Small_Group1.Current_Status__c = 'No';
        oppS3BPA_Small_Group1.CloseDate = date.parse('7/25/2016');
        insert oppS3BPA_Small_Group1;

        //   New Rider Plan
        Benefit_Plan_Metadata__c bpm4 = new Benefit_Plan_Metadata__c();
        bpm4.Name = 'XA03 - 2016';
        bpm4.Medical_OR_Rider__c = 'Rider';
        bpm4.Product_Class__c = 'Acupuncture and Chiro';
        bpm4.Effective_Date__c = Date.parse('1/1/2016');
        bpm4.End_Date__c = Date.parse('12/31/2016');
        bpm4.Market_Segment__c = 'Large Group';
        bpm4.Plan_Type__c = 'Standard';
        bpm4.Benefit_Plan_ID__c = 'XA03';
        bpm4.Plan_Status__c = 'Available for Sale - Approved';
        bpm4.Plan_Year__c = '2016';
        Insert bpm4;

        /*Associating the Benefit Plans to Opportunity record */
        Benefit_Plan_Association__c bpa = new Benefit_Plan_Association__c();
        bpa.Benefit_Plan_Metadata__c = bpm4.id;
        bpa.Raider_Id__c = bpm4.Id;
        bpa.Version_Number__c = 1;
        bpa.Opportunity__c = oppS3BPA_Small_Group1.id;
        insert bpa;
        
        Document_Generation_Request__c dgr = new Document_Generation_Request__c();
        dgr.Opportunity__c =  oppS3BPA_Small_Group1.id;      
        dgr.Status__c = System.label.HR141_Draft; 
        dgr.Request_Status__c = System.label.HR141_Draft; 
        dgr.has_Custom_Plans__c = true;
        dgr.Expedite__c = false;
        dgr.Plans__c = 'Test Plan';
        insert dgr;
    }
    
    @isTest
    static void method1() {

        Test.startTest();
        Opportunity oppS3BPA_Small_Group2 = [Select Id, StageName, RecordTypeId From Opportunity limit 1];
        oppS3BPA_Small_Group2.StageName = 'Closed Won';
        update oppS3BPA_Small_Group2;
        
        Opportunity oppS3BPA_Small_Group3 = [Select Id, StageName, RecordTypeId From Opportunity Where Id =: oppS3BPA_Small_Group2.Id];
        system.assertEquals(oppS3BPA_Small_Group3.StageName, 'Closed Won');
        oppS3BPA_Small_Group3.StageName = 'Pending Broker';
        update oppS3BPA_Small_Group3;
        Test.stopTest();
    }
}