Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <label>Employer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calpers</fullName>
                </value>
                <value>
                    <fullName>Jumbo (&gt;1000)</fullName>
                </value>
                <value>
                    <fullName>Key Accounts</fullName>
                </value>
                <value>
                    <fullName>Labor and Trust</fullName>
                </value>
                <value>
                    <fullName>Large Group (251-1000)</fullName>
                </value>
                <value>
                    <fullName>Large Mid-Market Group (101 - 250)</fullName>
                </value>
                <value>
                    <fullName>Mid-Market Group (51-250)</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Small Group (1 - 50)</fullName>
                </value>
                <value>
                    <fullName>Small Group (2-50)</fullName>
                </value>
                <value>
                    <fullName>Small Mid-Market Group (51 - 100)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Association__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Plan_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Plan Metadata</label>
        <referenceTo>Benefit_Plan_Metadata__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medical_or_Rider__c</fullName>
        <formula>IF(Raider_ID__c &lt;&gt; NULL,Raider_ID__r.Medical_OR_Rider__c,Benefit_Plan_Metadata__r.Medical_OR_Rider__c)</formula>
        <label>Medical or Rider</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <formula>IF( Raider_ID__r.Plan_Name__c != NULL, Benefit_Plan_Metadata__r.Plan_Name__c  &amp; &quot;/&quot;  &amp;  Raider_ID__r.Plan_Name__c , Benefit_Plan_Metadata__r.Plan_Name__c)</formula>
        <label>Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <formula>Benefit_Plan_Metadata__r.Plan_Type__c</formula>
        <label>Plan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <formula>IF(Raider_ID__c &lt;&gt; NULL,Raider_ID__r.Product_Class__c,Benefit_Plan_Metadata__r.Product_Class__c)</formula>
        <label>Product Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <label>Opportunity Benefit Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Benefit Plan Association</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Grid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Grid</label>
        <referenceTo>SHP_Benefit_Grid__c</referenceTo>
        <relationshipLabel>Benefit Plan Metadata</relationshipLabel>
        <relationshipName>Benefit_Plan_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Plan_ID__c</fullName>
        <label>Benefit Plan ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_OR_Rider__c</fullName>
        <label>Medical OR Rider</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <label>Product Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <label>Version Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Benefit Plan Metadata</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Incumbent_Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>Opportunity__r.Employer_Type__c</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incumbent_Carrier__c</fullName>
        <description>Req 3389</description>
        <label>Incumbent Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AETNA</fullName>
                </value>
                <value>
                    <fullName>ANTHEM</fullName>
                </value>
                <value>
                    <fullName>BLUE SHIELD</fullName>
                </value>
                <value>
                    <fullName>CAL CHOICE</fullName>
                </value>
                <value>
                    <fullName>CALPERS</fullName>
                </value>
                <value>
                    <fullName>CHINESE COMMUNITY HEALTH PLAN</fullName>
                </value>
                <value>
                    <fullName>CIGNA</fullName>
                </value>
                <value>
                    <fullName>HEALTH NET</fullName>
                </value>
                <value>
                    <fullName>SELF FUNDED</fullName>
                </value>
                <value>
                    <fullName>UNITED</fullName>
                </value>
                <value>
                    <fullName>WHA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>KAISER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_of_Quotes_Requested__c</fullName>
        <label># of Quotes Requested</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RFP Form/Incumbent Carriers</relationshipLabel>
        <relationshipName>Incumbent_Carriers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Market_Check__c</fullName>
        <defaultValue>&quot;Renewal&quot;</defaultValue>
        <label>Reason for Market Check</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Instuctions__c</fullName>
        <label>Special Instuctions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted to Underwriting</fullName>
                </value>
                <value>
                    <fullName>Approved by Underwriting</fullName>
                </value>
                <value>
                    <fullName>Rejected by Underwriting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategy_Statement__c</fullName>
        <label>Strategy Statement</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tiered_Rates__c</fullName>
        <label>Tiered Rates</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RFP Form/Incumbent Carrier</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Incumbent Carrier No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFP Form/Incumbent Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>TEXT(Account.Employer_Type__c)</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/SF_P2A_Market_Segments_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HR_SF-P2A Market Segments Mapping</label>
</CustomObject>

Sutter Health/src/objects/SHP_Benefit_Grid__c.object
<CustomObject>
    <description>This Object is Used to capture the information related to Benefit Grid Data.</description>
    <fields>
        <fullName>Benefit_Plan_ID__c</fullName>
        <label>Benefit Plan ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Acupuncture Only</fullName>
                </value>
                <value>
                    <fullName>Chiropractic Only</fullName>
                </value>
                <value>
                    <fullName>Acupuncture and Chiro</fullName>
                </value>
                <value>
                    <fullName>Infertility</fullName>
                </value>
                <value>
                    <fullName>Orthotics and Special Footwear</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHP_Benefit_Plan_Year__c</fullName>
        <description>Req number 3391  added benefit plan for 2016</description>
        <label>Benefit Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <recordTypes>
        <fullName>Medical</fullName>
        <active>true</active>
        <description>This record type is used to create/update Medical Plans</description>
        <label>Medical</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/RFPForm_Test.cls
/* 
     Class Name: RFPForm_Test 
     Author: IDC Offshore
     Date: 06-Dec-2016
     Description: Test class for RFPForm Trigger.
*/
@isTest
private class RFPForm_Test {
    private static Account acc;
    private static Opportunity opp;
    private static Incumbent_Carrier__c rfp;
    private static Benefit_Plan_Association__c bpa;
    private static Benefit_Plan_Metadata__c bpm;
    private static SHP_Benefit_Grid__c grid;
    private static Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHP Sales Employer').getRecordTypeId();
	private static Id incRecordTypeId = Schema.SObjectType.Incumbent_Carrier__c.getRecordTypeInfosByName().get('RFP Form').getRecordTypeId();
    private static Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SHP Sales Opportunity').getRecordTypeId();
	
    /*Method to Set up Test data*/
    private static testMethod void setUpTestData(){
        
        List<SF_P2A_Market_Segments_Mapping__c> listp2amarketseg = HighRoads_TestDataUtility.insertP2AMarketSegmentsCS();
        insert listp2amarketseg;
        
        acc = new Account();
        acc.Name = 'TestAcc1';
        acc.RecordTypeId = accRecordTypeId;
        acc.NumberOfEmployees = 50;
        acc.Industry = 'Hospitaity';
        acc.Employer_Type__c = 'Labor and Trust';
        insert acc;
        
        opp = new Opportunity();
        opp.Name = 'TestOpp1';
        opp.RecordTypeId = oppRecordTypeId;
        opp.AccountId = acc.id;
        opp.type = 'New Business';
        opp.CloseDate = Date.Today();
        opp.StageName = 'Pending Broker';
        insert opp;
        
        grid = new SHP_Benefit_Grid__c();
        grid.Benefit_Plan_ID__c = 'HE02';
        grid.Market_Segment__c = 'Large Group';
        grid.SHP_Benefit_Plan_Year__c = '2016';
        grid.Plan_Name__c = 'HE02-2016';
        insert grid;
        
        bpm = new Benefit_Plan_Metadata__c();
        bpm.Name = 'HE02';
        bpm.Medical_OR_Rider__c = 'Medical';
        bpm.Product_Class__c = 'Medical';
        bpm.Effective_Date__c = Date.today();
        bpm.Market_Segment__c = 'Large Group';
        bpm.Plan_Type__c = 'Standard';
        bpm.Benefit_Plan_ID__c = 'HE02';
        bpm.Benefit_Grid__c = grid.id;
        insert bpm;
        
        bpa = new Benefit_Plan_Association__c();
        bpa.Benefit_Plan_Metadata__c = bpm.id;
        bpa.Version_Number__c = 1;
        bpa.Opportunity__c = opp.id;
        insert bpa;
    }
    
    /* Test method to test if Plans in related Opportunity are Copied to RFP When RFP is inserted, 
	System throws exceptions when  mandatory Fields are not Entered during RFP Submission
	& Quote Creation after RFP is approved*/
    private static testMethod void testRFPSubmissionApproval(){
    	Test.startTest(); 
        setUpTestData();
        
            rfp = new Incumbent_Carrier__c();
            rfp.RecordtypeId = incRecordTypeId;
            rfp.Opportunity__c = opp.id;
        	rfp.Stage__c = 'Draft';
            insert rfp;
        	
            try{
            	rfp.Reason_for_Market_Check__c = '';
                rfp.Stage__c = 'Submitted to Underwriting';
                
                RFP_IncumbentCarrierTriggerHelper.isBeforeUpdate = true;
        		update rfp;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Please enter # Of Quotes Requested before Submitting for approval') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        
        	try{
            	rfp.No_of_Quotes_Requested__c = 12;
                rfp.Stage__c = 'Submitted to Underwriting';
                RFP_IncumbentCarrierTriggerHelper.isBeforeUpdate = true;
        		update rfp;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Please enter Reason for Market Check before Submitting for approval') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        
        	try{
            	rfp.Reason_for_Market_Check__c = 'Test Reason';
                rfp.Stage__c = 'Submitted to Underwriting';
                RFP_IncumbentCarrierTriggerHelper.isBeforeUpdate = true;
        		update rfp;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Please enter Tiered Rates before Submitting for approval') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        
        	try{
            	rfp.Tiered_Rates__c = '23';
                rfp.Stage__c = 'Submitted to Underwriting';
                RFP_IncumbentCarrierTriggerHelper.isBeforeUpdate = true;
        		update rfp;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Please provide Strategy Statement before Submitting for approval') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        	
        	try{
            	rfp.Strategy_Statement__c = 'Test Statement';
                rfp.Stage__c = 'Submitted to Underwriting';
                RFP_IncumbentCarrierTriggerHelper.isBeforeUpdate = true;
        		update rfp;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('Please provide Special Instructions before Submitting for approval') ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        	RFP_IncumbentCarrierTriggerHelper.isBeforeUpdate = true;
        	rfp.Special_Instuctions__c = 'Test Instructions';
        	rfp.Stage__c = 'Submitted to Underwriting';
        	update rfp;
        	RFP_IncumbentCarrierTriggerHelper.isBeforeUpdate = true;
        	RFP_IncumbentCarrierTriggerHelper.isAfterUpdate = true;
            rfp.Stage__c = 'Approved by Underwriting';
        	update rfp;
        
        Test.stopTest();
    }
}