Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <label>Employer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calpers</fullName>
                </value>
                <value>
                    <fullName>Jumbo (&gt;1000)</fullName>
                </value>
                <value>
                    <fullName>Key Accounts</fullName>
                </value>
                <value>
                    <fullName>Labor and Trust</fullName>
                </value>
                <value>
                    <fullName>Large Group (251-1000)</fullName>
                </value>
                <value>
                    <fullName>Large Mid-Market Group (101 - 250)</fullName>
                </value>
                <value>
                    <fullName>Mid-Market Group (51-250)</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Small Group (1 - 50)</fullName>
                </value>
                <value>
                    <fullName>Small Group (2-50)</fullName>
                </value>
                <value>
                    <fullName>Small Mid-Market Group (51 - 100)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Incumbent_Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>Opportunity__r.Employer_Type__c</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incumbent_Carrier__c</fullName>
        <description>Req 3389</description>
        <label>Incumbent Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AETNA</fullName>
                </value>
                <value>
                    <fullName>ANTHEM</fullName>
                </value>
                <value>
                    <fullName>BLUE SHIELD</fullName>
                </value>
                <value>
                    <fullName>CAL CHOICE</fullName>
                </value>
                <value>
                    <fullName>CALPERS</fullName>
                </value>
                <value>
                    <fullName>CHINESE COMMUNITY HEALTH PLAN</fullName>
                </value>
                <value>
                    <fullName>CIGNA</fullName>
                </value>
                <value>
                    <fullName>HEALTH NET</fullName>
                </value>
                <value>
                    <fullName>SELF FUNDED</fullName>
                </value>
                <value>
                    <fullName>UNITED</fullName>
                </value>
                <value>
                    <fullName>WHA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>KAISER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RFP Form/Incumbent Carrier</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Incumbent Carrier No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFP Form/Incumbent Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/SHMMN_Incumbent_Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>SHMMN Employer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SHMMN Incumbent Carrier</relationshipLabel>
        <relationshipName>SHMMN_Incumbent_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contain__c</fullName>
        <label>%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Incumbent_Carrier__c</fullName>
        <label>Incumbent Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aetna</fullName>
                </value>
                <value>
                    <fullName>Anthem</fullName>
                </value>
                <value>
                    <fullName>Blue Shield</fullName>
                </value>
                <value>
                    <fullName>Cal Choice</fullName>
                </value>
                <value>
                    <fullName>Calpers</fullName>
                </value>
                <value>
                    <fullName>Chinese Community Health Plan</fullName>
                </value>
                <value>
                    <fullName>Cigna</fullName>
                </value>
                <value>
                    <fullName>Health Net</fullName>
                </value>
                <value>
                    <fullName>Kaiser</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Self Funded</fullName>
                </value>
                <value>
                    <fullName>Shp</fullName>
                </value>
                <value>
                    <fullName>United Health Care</fullName>
                </value>
                <value>
                    <fullName>Wha</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Product__c</fullName>
        <label>Sub Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>HSA</fullName>
                </value>
                <value>
                    <fullName>Indemnity</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SHMMN Incumbent Carrier</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>SHMMN Incumbent Carrier Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHMMN Incumbent Carrier</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/SHMMN_SHMMNIncumebnt.cls
/*************************************************************************************************************
*     Class Name  : SHMMN_SHMMNIncumebnt                                                                                                                               
*     Author      : IDC Offshore                                                                                                                                            
*     Date        : 21-Apr-2016                                                                                                                                             
*     Project Name: CRM - SFT - Sutter Health                                                                                                                                        
*     Description : Controller class for creating incumbent carrier on SHMMN Employer Account.   
**************************************************************************************************************/
public without sharing class SHMMN_SHMMNIncumebnt {
    
    public Account shmmnAccount{get;set;}
    public SHMMN_Incumbent_Carrier__c extcont;
    public Integer incumbentCount =3;
    public List<incumbentWrapper> incumbentList {get;set;}
    public List<SHMMN_Incumbent_Carrier__c > incumbentInsertList {get;set;}
    public PageReference newPage {get;set;}
    public List<SHMMN_Incumbent_Carrier__c> incumbentCreatedList {get;set;}
    public boolean showMsg {get;set;}   
    public static final string SUBPROD_MSG = 'Sub-Product is mandatory if Incumbent Carrier is selected.';  
    /****************************************************************************************************************************************************************************
*   @author ......: IDC Offshore                                                                                                                                        
*   @date ........: 21-Apr-2016                                                                                                                                           
*   @description .: This the constructor method provided by extension controller.                                                                                       
*   @param........: Standard Controller                                                                                                                                            
*   @return ......: [NA]                                                                                                                                               
*************************************************************************************************************************************************************************/
    public SHMMN_SHMMNIncumebnt(ApexPages.StandardController stdController) 
    {
        this.extcont= (SHMMN_Incumbent_Carrier__c )stdController.getRecord();
        incumbentInsertList = new List<SHMMN_Incumbent_Carrier__c >();
        incumbentCreatedList = new List<SHMMN_Incumbent_Carrier__c >();
        
        shmmnAccount=[SELECT Id,Name, Employer_Type__c, Status__c, NumberOfEmployees from account where id =: extcont.Account__c limit 1];
        incumbentCreatedList = [SELECT ID, Name, Incumbent_Carrier__c, Sub_Product__c, Contain__c from SHMMN_Incumbent_Carrier__c where Account__c =: shmmnAccount.id limit 50000];
        incumbentList = new List<incumbentWrapper>();
        if(incumbentCreatedList.size() >0)
        {
            for(SHMMN_Incumbent_Carrier__c sic: incumbentCreatedList)
            {
                incumbentWrapper incwrap = new incumbentWrapper( shmmnAccount, sic);
                incumbentList.add(incwrap );       
            }
        }
        else  {
            for(integer k =0; k <incumbentCount ; k++)
            {
                incumbentWrapper incwrap = new incumbentWrapper( shmmnAccount);
                incumbentList.add(incwrap );       
            }
        }
    }
    /****************************************************************************************************************************************************************************
*   @author ......: IDC Offshore                                                                                                                                        
*   @date ........: 21-Apr-2016                                                                                                                                           
*   @description .: Method to decrease list of incumbent carrier.                                                                                       
*   @param........: [NA]                                                                                                                                            
*   @return ......: [NA]                                                                                                                                               
*************************************************************************************************************************************************************************/
    public Void decreaseList()
    {
        
            Integer incumbentSize = incumbentList.size();
            if(incumbentCreatedList.size() >0 && incumbentSize > incumbentCreatedList.size())
            {
                incumbentList.remove(incumbentSize-1);
            }
            else if(incumbentSize>1 && incumbentCreatedList.size() == 0)
                incumbentList.remove(incumbentSize-1);
        
    }
    /****************************************************************************************************************************************************************************
*   @author ......: IDC Offshore                                                                                                                                        
*   @date ........: 21-Apr-2016                                                                                                                                           
*   @description .: Method to increase list of incumbent carrier.                                                                                       
*   @param........: [NA]                                                                                                                                            
*   @return ......: [NA]                                                                                                                                               
*************************************************************************************************************************************************************************/    
    public Void increaseList()
    {
        
            incumbentWrapper incwrap = new incumbentWrapper( shmmnAccount);
            incumbentList.add(incwrap ); 
        
    }
    /****************************************************************************************************************************************************************************
*   @author ......: IDC Offshore                                                                                                                                        
*   @date ........: 21-Apr-2016                                                                                                                                           
*   @description .: Method to save the list of incumbent carrier.                                                                                       
*   @param........: [NA]                                                                                                                                            
*   @return ......: PageReference to return to account detail page.                                                                                                              
*************************************************************************************************************************************************************************/ 
    public PageReference saveIncumbentCarriers() {
        try{
            incumbentInsertList.clear();
            Decimal sum=0;
            Map<String,String> mergeIncumbent = new Map<String, String>();
            for(incumbentWrapper ins: incumbentList)
            {
                if(ins.obj.Incumbent_Carrier__c != null )
                {
                incumbentInsertList.add(ins.obj);
                }
                else if (ins.obj.id != null)
                incumbentInsertList.add(ins.obj);
                if(ins.obj.Contain__c != null)
                sum= sum + ins.obj.Contain__c;
                if(ins.obj.Incumbent_Carrier__c != null)
                {
                if(ins.obj.Sub_Product__c != null)
                {
                String dupCheck = ins.obj.Incumbent_Carrier__c + ins.obj.Sub_Product__c;
                mergeIncumbent.put(dupCheck, System.Label.CL_79_SM_DupCheck);
                showMsg = true;
                }
                else if (ins.obj.Sub_Product__c == null)
                {
                 showMsg = false;   
                }
                }
            }
            
            if(mergeIncumbent.size() != incumbentInsertList.size())
            {
                if(showMsg == false)
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,SUBPROD_MSG);
                ApexPages.addMessage(myMsg);
            }
                if(showMsg == true)
                {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,System.Label.CL_74_SM_IncumbentDupErrorMsg);
                ApexPages.addMessage(myMsg);
                newPage = null;
                }
            }
            else if(sum > 100.00)
            { 
                
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,System.Label.CL_68_SM_Morethan100);
                ApexPages.addMessage(myMsg);
                newPage = null;
                
            }   
            else if(sum <= 100.00)
            {
                upsert incumbentInsertList;
                newPage = new PageReference (System.Label.CL_32_SM_Slash + shmmnAccount.id);
            }
            return newPage ;
        }catch(Exception e){
            
            ApexPages.addMessages(e);
            return null;
        }
    }
    /****************************************************************************************************************************************************************************
*   @author ......: IDC Offshore                                                                                                                                        
*   @date ........: 21-Apr-2016                                                                                                                                           
*   @description .: Wrapper class for SHMMN Incumbent Carrier                                                                                       
*   @param........: [NA]                                                                                                                                            
*   @return ......: [NA]                                                                                                             
*************************************************************************************************************************************************************************/     
    public class incumbentWrapper
    {
        public SHMMN_Incumbent_Carrier__c obj{get;set;}
        
        public incumbentWrapper(Account acc )
        {
            obj= new SHMMN_Incumbent_Carrier__c ();
            obj.Account__c=acc.id;
        }
        public incumbentWrapper(Account acc, SHMMN_Incumbent_Carrier__c sic )
        {
            obj= sic;
            obj.Account__c=acc.id;
        }
        
    }
}