Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Employer_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Historical Read-Only Employer Activities</relationshipLabel>
        <relationshipName>Employer_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>SHMMN</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Employer_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Employer Activity</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employer Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employer Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/ShareEmployerActivity_Test.cls
/**********************************************************************
  Name: ShareEmployerActivity_Test
  Copyright © 2015 IDC Offshore
  ======================================================
  ======================================================
  Purpose:
  This is the test class for ShareEmployerActivity trigger            
  ======================================================
  ======================================================
  History
  -------
  VERSION  AUTHOR        DATE        DETAIL                 Description
  1.0     IDC Offshore 05/04/2015 Development complete   This class is defined to test functionality of ShareEmployerActivity trigger.  
  ***********************************************************************/
@isTest
Private class ShareEmployerActivity_Test 
{
  /*******************************************************************
    Purpose: method to share Employer Agreement on insert of record
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/
  static testmethod void shareEmpActInsert_Test()
  {  
     Id profileId = [SELECT Id FROM Profile WHERE Name like 'SHMMN%' limit 1].Id;
     Id uRole =  [SELECT Id FROM UserRole WHERE Name='SHMMN'].Id;           
     User SHMMNUser = new User(Alias = 'standt', Email='SHMMNuser@testmethod.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = profileId, UserRoleId = uRole, TimeZoneSidKey='America/Los_Angeles', UserName='SHMMNuser@testmethod4.com');
     insert SHMMNUser ;
     // Assert to check user is inserted successfully.
     System.assert(SHMMNUser.id!=null);
     User tempSHMMNUser = new User(Alias = 'standt', Email='SHMMNuser@testmethod.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = profileId, UserRoleId = uRole, TimeZoneSidKey='America/Los_Angeles', UserName='SHMMNuser@testmethod3.com');
     insert tempSHMMNUser ;
     // Assert to check user is inserted successfully.
     System.assert(tempSHMMNUser.id!=null);
     
     Id recType = Schema.SObjectType.Employer_Activity__c.getRecordTypeInfosByName().get('Annual Action Plan').getRecordTypeId();
     Id accRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account acc = new Account();
     Employer_Activity__c empAct = new Employer_Activity__c();
     System.runAs(SHMMNUser)
     {
         acc.Name = 'Test Account';
         acc.RecordTypeId = accRecType;
         insert acc;
         // Assert to check account is created successfully
         System.assert(acc.id!=null);
         
         empAct.Account_Name__c = acc.id;
         empAct.Start_Date__c = date.newInstance(2016,04,05);
         empAct.Due_Date__c = date.newInstance(2016,04,05);
         empAct.Assigned_To__c = tempSHMMNUser.id;
         empAct.Status__c = 'In Progress';
         empAct.RecordTypeId = recType;
         insert empAct; 
     }
     List<Employer_Activity__Share> shares = [select id from Employer_Activity__Share where ParentId = :empAct.id and RowCause = 'Manual'];
     //Assert to check record is shared with user through apex sharing
     System.assertEquals(shares.size(),1);
         
  }
  /*******************************************************************
    Purpose: method to share Employer Agreement on update of record
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/
  static testmethod void shareEmpActUpdate_Test()
  {  
     Id profileId = [SELECT Id FROM Profile WHERE Name like 'SHMMN%' limit 1].Id;
     Id uRole =  [SELECT Id FROM UserRole WHERE Name='SHMMN'].Id;           
     User SHMMNUser = new User(Alias = 'standt', Email='SHMMNuser@testmethod.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = profileId, UserRoleId = uRole, TimeZoneSidKey='America/Los_Angeles', UserName='SHMMNuser@testmethod4.com');
     insert SHMMNUser ;
     // Assert to check user is inserted successfully.
     System.assert(SHMMNUser.id!=null);
     User tempSHMMNUser = new User(Alias = 'standt', Email='SHMMNuser@testmethod.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = profileId, UserRoleId = uRole, TimeZoneSidKey='America/Los_Angeles', UserName='SHMMNuser@testmethod5.com');
     insert tempSHMMNUser ;
     // Assert to check user is inserted successfully.
     System.assert(tempSHMMNUser.id!=null);
     
     Id recType = Schema.SObjectType.Employer_Activity__c.getRecordTypeInfosByName().get('Annual Action Plan').getRecordTypeId();
     Id accRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account acc = new Account();
     Employer_Activity__c empAct = new Employer_Activity__c();
     System.runAs(SHMMNUser)
     {
         acc.Name = 'Test Account';
         acc.RecordTypeId = accRecType;
         insert acc;
         // Assert to check account is created successfully
         System.assert(acc.id!=null);
         
         empAct.Account_Name__c = acc.id;
         empAct.Start_Date__c = date.newInstance(2016,04,05);
         empAct.Due_Date__c = date.newInstance(2016,04,05);
         empAct.Assigned_To__c = SHMMNUser.id;
         empAct.Status__c = 'In Progress';
         empAct.RecordTypeId = recType;
         insert empAct; 
         
         empAct.Assigned_To__c = tempSHMMNUser.id;
         update empAct;
         
     }
     List<Employer_Activity__Share> shares = [select id from Employer_Activity__Share where ParentId = :empAct.id and RowCause = 'Manual'];
     //Assert to check record is shared with user assigned through apex sharing
     System.assertEquals(shares.size(),1);
         
  }
  /*******************************************************************
    Purpose: method to check sharing is removed from user on removing from Assigned To
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/
  static testmethod void shareEmpActNegative_Test()
  {  
     Id profileId = [SELECT Id FROM Profile WHERE Name like 'SHMMN%' limit 1].Id;
     Id uRole =  [SELECT Id FROM UserRole WHERE Name='SHMMN'].Id;           
     User SHMMNUser = new User(Alias = 'standt', Email='SHMMNuser@testmethod.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = profileId, UserRoleId = uRole, TimeZoneSidKey='America/Los_Angeles', UserName='SHMMNuser@testmethod4.com');
     insert SHMMNUser ;
     // Assert to check user is inserted successfully.
     System.assert(SHMMNUser.id!=null);
     User tempSHMMNUser = new User(Alias = 'standt', Email='SHMMNuser@testmethod.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = profileId, UserRoleId = uRole, TimeZoneSidKey='America/Los_Angeles', UserName='SHMMNuser@testmethod5.com');
     insert tempSHMMNUser ;
     // Assert to check user is inserted successfully.
     System.assert(tempSHMMNUser.id!=null);
     
     Id recType = Schema.SObjectType.Employer_Activity__c.getRecordTypeInfosByName().get('Annual Action Plan').getRecordTypeId();
     Id accRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account acc = new Account();
     Employer_Activity__c empAct = new Employer_Activity__c();
     System.runAs(SHMMNUser)
     {
         acc.Name = 'Test Account';
         acc.RecordTypeId = accRecType;
         insert acc;
         // Assert to check account is created successfully
         System.assert(acc.id!=null);
         
         empAct.Account_Name__c = acc.id;
         empAct.Start_Date__c = date.newInstance(2016,04,05);
         empAct.Due_Date__c = date.newInstance(2016,04,05);
         empAct.Assigned_To__c = SHMMNUser.id;
         empAct.Status__c = 'In Progress';
         empAct.RecordTypeId = recType;
         insert empAct; 
         
         empAct.Assigned_To__c = tempSHMMNUser.id;
         update empAct;
         
         empAct.Assigned_To__c = SHMMNUser.id;
         update empAct;
     }
     List<Employer_Activity__Share> shares = [select id from Employer_Activity__Share where ParentId = :empAct.id and RowCause = 'Manual'];
     //Assert to check no record is shared with user through apex sharing
     System.assertEquals(shares.size(),0);
         
  }
}