Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>HealthRules_ID__c</fullName>
        <externalId>true</externalId>
        <label>HealthRules HCC ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Record type for S3 Providers</description>
        <label>S3 Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HealthRules_ID__c</fullName>
        <externalId>true</externalId>
        <label>HealthRules HCC ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <label>Member ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Member_Subscriber_Relationship__c</fullName>
        <label>Member Subscriber Relationship</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_NPI__c</fullName>
        <label>Provider NPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_TIN_Address__c</fullName>
        <label>Provider TIN Address</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Used for member contact records.</description>
        <label>Member</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for provider contact records.</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Correspondence__c.object
<CustomObject>
    <description>Correspondence</description>
    <fields>
        <fullName>Address_same_as_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Address same as Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <label>Closed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriber Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Correspondences</relationshipLabel>
        <relationshipName>Correspondences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correspondence_Type__c</fullName>
        <label>Correspondence Definition</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Member_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Age 26 Dependent Termination Letter</fullName>
                </value>
                <value>
                    <fullName>Certificate of Creditable Coverage</fullName>
                </value>
                <value>
                    <fullName>Coordination of Benefits Form</fullName>
                </value>
                <value>
                    <fullName>Disabled Dependent Certification Form</fullName>
                </value>
                <value>
                    <fullName>Enrollment Forms</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Acupuncture</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Acupuncture and Chiropractic</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - All</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Chiropractic</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Dental</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Infertility</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Medical</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Orthotics and Prosthetics</fullName>
                </value>
                <value>
                    <fullName>Evidence of Coverage - Vision</fullName>
                </value>
                <value>
                    <fullName>Explanation of Benefits - Out of Area Only</fullName>
                </value>
                <value>
                    <fullName>Group Subscriber Termination Letter</fullName>
                </value>
                <value>
                    <fullName>ID Cards – All Members</fullName>
                </value>
                <value>
                    <fullName>Member ID Card</fullName>
                </value>
                <value>
                    <fullName>Member Renewal Letter with ID Cards</fullName>
                </value>
                <value>
                    <fullName>New Member Welcome Letter with ID Cards</fullName>
                </value>
                <value>
                    <fullName>Premium Bill</fullName>
                </value>
                <value>
                    <fullName>Provider Directory</fullName>
                </value>
                <value>
                    <fullName>Other - Please Specify in Comments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Sent_To_Vendor__c</fullName>
        <label>Date Sent to Print Vendor</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fax_Number__c</fullName>
        <label>Fax Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <label>Correspondence Recipient Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_To_Sub__c</fullName>
        <label>Relationship to Subscriber</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
                <value>
                    <fullName>Doctor&apos;s Office Representative</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Self</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Subscriber</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Correspondences</relationshipLabel>
        <relationshipName>Correspondences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_of_Correspondence__c</fullName>
        <label>Vehicle of Correspondence</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Correspondence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Correspondence_Comments__c.object
<CustomObject>
    <description>Correspondence Comments</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Correspondence__c</fullName>
        <label>Correspondence</label>
        <referenceTo>Correspondence__c</referenceTo>
        <relationshipLabel>Correspondence Comments</relationshipLabel>
        <relationshipName>Correspondence_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Correspondence Comments</label>
    <nameField>
        <displayFormat>CRC-{00000}</displayFormat>
        <label>Correspondence Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sutter Health/src/classes/CorresponenceTest.cls
@isTest
private class CorresponenceTest {

    
    private static testMethod void testMethod1() {
        try {
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.LastName = 'Test C1';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj.Member_ID__c = 'M123456-01';
            contactObj.Member_Subscriber_Relationship__c  = 'Self';
            contactObj.mailingstreet = 'Test Street';
            contactObj.mailingcity = 'Test Street';
            contactObj.mailingstate = 'Test Street';
            contactObj.mailingcountry = 'Test Street';
            contactObj.MailingPostalCode= 'Test Street';
            insert contactObj;
            
            // Assert to check Contact is inserted successfully
            system.assert(contactObj.id!=null);
            
            Contact contactObj1 = new Contact();
            contactObj1.LastName = 'Test C2';
            contactObj1.AccountId = accObj.Id;
            contactObj1.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj1.Member_ID__c = 'M123456-02';
            contactObj1.Member_Subscriber_Relationship__c  = 'Spouse';
            insert contactObj1;
            // Assert to check Contact is inserted successfully
            system.assert(contactObj1.id!=null);
            
            Contact contactObj2 = new Contact();
            contactObj2.LastName = 'Test C3';
            contactObj2.AccountId = accObj.Id;
            contactObj2.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('SHP Provider').RecordTypeId;
            contactObj2.Supplier_NPI__c = '3222244';
            contactObj2.Supplier_TIN_Address__c = '1200 Creek side\n\nFolsom, CA 95600-1000';
            insert contactObj2;
            // Assert to check Contact is inserted successfully
            system.assert(contactObj2.id!=null);
            
            Contact contactObj3 = new Contact();
            contactObj3.LastName = 'Test C4';
            contactObj3.AccountId = accObj.Id;
            contactObj3.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('SHP Sales Broker Contact Read Only').RecordTypeId;
            contactObj3.HealthRules_ID__c = '442211';
            contactObj3.mailingstreet = 'Test Street';
            contactObj3.mailingcity = 'Test Street';
            contactObj3.mailingstate = 'Test Street';
            contactObj3.mailingcountry = 'Test Street';
            contactObj3.MailingPostalCode= 'Test Street';
            insert contactObj3;
            // Assert to check Contact is inserted successfully
            system.assert(contactObj3.id!=null);
            
            Contact contactObj4 = new Contact();
            contactObj4.LastName = 'Test C5';
            contactObj4.AccountId = accObj.Id;
            contactObj4.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('SHP Sales Employer Contact Read Only').RecordTypeId;
            contactObj4.HealthRules_ID__c = '442213';
            contactObj4.mailingstreet = 'Test Street';
            contactObj4.mailingcity = 'Test Street';
            contactObj4.mailingstate = 'Test Street';
            contactObj4.mailingcountry = 'Test Street';
            contactObj4.MailingPostalCode= 'Test Street';
            insert contactObj4;
            // Assert to check Contact is inserted successfully
            system.assert(contactObj4.id!=null);
            
            Case caseObj =  new Case();
            caseObj.contactId = contactObj.Id;
            caseObj.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('Correspondence').RecordTypeId;
            caseObj.subject = 'Test Case';
            insert caseObj;
            
            // Assert to check Case is inserted successfully
            system.assert(caseObj.id!=null);
            
            
            Test.StartTest();
            ApexPages.currentPage().getParameters().put('ServiceId',caseObj.Id);
            ApexPages.currentPage().getParameters().put('ContactId',contactObj.Id);
            CorrespondenceCls correspondenceClsObj= new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c()));
            correspondenceClsObj.isDefault = true;
            correspondenceClsObj.onDefaultCHKBoxClick();
            correspondenceClsObj.isDefault = false;
            correspondenceClsObj.onDefaultCHKBoxClick();
            correspondenceClsObj.correspondenceObj.Vehicle_of_Correspondence__c = 'Mail';
            correspondenceClsObj.onVehicleOfCoorespondenceChange();
            
            ApexPages.currentPage().getParameters().put('ContactId',contactObj2.Id);
            CorrespondenceCls correspondenceClsObj1 = new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c()));
            correspondenceClsObj1.isDefault = true;
            correspondenceClsObj1.onDefaultCHKBoxClick();
            correspondenceClsObj1.isDefault = false;
            correspondenceClsObj1.onDefaultCHKBoxClick();
            correspondenceClsObj1.correspondenceObj.Vehicle_of_Correspondence__c = 'Mail';
            correspondenceClsObj1.onVehicleOfCoorespondenceChange();
            
            ApexPages.currentPage().getParameters().put('ContactId',contactObj3.Id);
            CorrespondenceCls correspondenceClsObj2 = new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c()));
            
            
            
            ApexPages.currentPage().getParameters().put('ContactId',contactObj4.Id);
            CorrespondenceCls correspondenceClsObj3 = new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c()));
            correspondenceClsObj1.cancel();
            Test.StopTest();
        } catch(Exception ex) {}
    }
    
    private static testMethod void testMethod2() {
        try {
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            // Assert to check Account is inserted successfully
            system.assert(accObj.id!=null);
            
            Contact contactObj = new Contact();
            contactObj.LastName = 'Test C1';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj.Member_ID__c = 'M123456-01';
            contactObj.Member_Subscriber_Relationship__c  = 'Self';
            contactObj.mailingstreet = 'Test Street';
            contactObj.mailingcity = 'Test Street';
            contactObj.mailingstate = 'Test Street';
            contactObj.mailingcountry = 'Test Street';
            contactObj.MailingPostalCode= 'Test Street';
            insert contactObj;
            // Assert to check Contact is inserted successfully
            system.assert(contactObj.id!=null);
            
            Contact contactObj1 = new Contact();
            contactObj1.LastName = 'Test C2';
            contactObj1.AccountId = accObj.Id;
            contactObj1.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj1.Member_ID__c = 'M123456-02';
            contactObj1.Member_Subscriber_Relationship__c  = 'Spouse';
            insert contactObj1;
           // Assert to check Contact is inserted successfully
            system.assert(contactObj1.id!=null);
            
            Contact contactObj2 = new Contact();
            contactObj2.LastName = 'Test C3';
            contactObj2.AccountId = accObj.Id;
            contactObj2.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('SHP Provider').RecordTypeId;
            contactObj2.Supplier_NPI__c = '3222244';
            contactObj2.Supplier_TIN_Address__c = '1200 Creek side\n\nFolsom, CA 95600-1000';
            insert contactObj2;
            //  Assert to check Contact is inserted successfully
            system.assert(contactObj2.id!=null);
            
            Case caseObj =  new Case();
            caseObj.contactId = contactObj.Id;
            caseObj.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('Correspondence').RecordTypeId;
            caseObj.subject = 'Test Case';
            insert caseObj;
            // Assert to check Account is Created successfully
            system.assert(caseObj.id!=null);
            
            Correspondence__c corresObj = new Correspondence__c();
            corresObj.Contact__c = contactObj.Id;
            corresObj.Street__c = 'Test 1';
            corresObj.City__c = 'Test 1';
            corresObj.State__c = 'Test 1';
            corresObj.Country__c  = 'Test 1';
            corresObj.ZipCode__c= 'Test 1';
            corresObj.Member_Type__c = 'Member';
            corresObj.Correspondence_Type__c = '';
            corresObj.Date_Sent_To_Vendor__c = System.today();
            corresObj.service_Request__c = caseObj.Id;
            corresObj.Relationship_To_Sub__c = 'Self';
            corresObj.Fax_Number__c = '222211';
            corresObj.Address_same_as_Default__c = true;
            corresObj.Vehicle_of_Correspondence__c= 'Email;Fax;';
            corresObj.Email_Id__c = 'Testrecord@test.com';
            corresObj.Status__c = 'New';
            corresObj.Comments__c = 'TestComment';
            insert corresObj;
            // Assert to check Correspondence record  is Created successfully
            system.assert(corresObj.id!=null);
            
            Correspondence__c corresObj1 = new Correspondence__c();
            corresObj1.Contact__c = contactObj2.Id;
            corresObj1.Street__c = 'Test 1';
            corresObj1.City__c = 'Test 1';
            corresObj1.State__c = 'Test 1';
            corresObj1.Country__c  = 'Test 1';
            corresObj1.ZipCode__c= 'Test 1';
            corresObj1.Member_Type__c = 'Member';
            corresObj1.Correspondence_Type__c = '';
            corresObj1.Date_Sent_To_Vendor__c = System.today();
            corresObj1.service_Request__c = caseObj.Id;
            corresObj1.Relationship_To_Sub__c = 'Self';
            corresObj1.Fax_Number__c = '222211';
            corresObj1.Address_same_as_Default__c = true;
            corresObj1.Vehicle_of_Correspondence__c= 'Email;Fax;';
            corresObj1.Email_Id__c = 'Testrecord@test.com';
            corresObj1.Status__c = 'New';
            corresObj1.Comments__c = 'TestComment';
            insert corresObj1;
            // Assert to check Correspondence record  is Created successfully
            system.assert(corresObj1.id!=null);
            
            Correspondence_Comments__c correscommentsObj1 = new Correspondence_Comments__c();
            correscommentsObj1.Comments__c = 'TestComment';
            correscommentsObj1.Correspondence__c=corresObj1.Id;
            insert correscommentsObj1;
            // Assert to check Correspondence Comment is Created successfully
            system.assert(correscommentsObj1.id!=null);
            
            Test.StartTest();
            ApexPages.currentPage().getParameters().put('corresid',corresObj1.Id);
            CorrespondenceCls correspondenceClsObj= new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c(id=corresObj.id)));
            correspondenceClsObj.isDefault = true;
            correspondenceClsObj.onDefaultCHKBoxClick();
            correspondenceClsObj.isDefault = false;
            correspondenceClsObj.onDefaultCHKBoxClick();
            correspondenceClsObj.correspondenceObj.Vehicle_of_Correspondence__c = 'Mail';
            correspondenceClsObj.onVehicleOfCoorespondenceChange();
            
            
            CorrespondenceCls correspondenceClsObj1 = new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c(id=corresObj1.id)));
            correspondenceClsObj1.isDefault = true;
            correspondenceClsObj1.onDefaultCHKBoxClick();
            correspondenceClsObj1.isDefault = false;
            correspondenceClsObj1.onDefaultCHKBoxClick();
            correspondenceClsObj1.correspondenceObj.Vehicle_of_Correspondence__c = 'Mail';
            correspondenceClsObj1.onVehicleOfCoorespondenceChange();
            
            Test.StopTest();
        } catch(Exception ex) {}
    }
    
    
    private static testMethod void testMethod3() {
        try {
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            // Assert to check Account  is Created successfully
            system.assert(accObj.id!=null);
            
            Contact contactObj = new Contact();
            contactObj.LastName = 'Test C2';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj.Member_ID__c = 'M123456-01';
            contactObj.Member_Subscriber_Relationship__c  = 'Self';
            contactObj.mailingstreet = 'Test Street';
            contactObj.mailingcity = 'Test Street';
            contactObj.mailingstate = 'Test Street';
            contactObj.mailingcountry = 'Test Street';
            contactObj.MailingPostalCode= 'Test Street';
            insert contactObj;
            // Assert to check Contact is Created successfully
            system.assert(contactObj.id!=null);
            
            Contact contactObj1 = new Contact();
            contactObj1.LastName = 'Test C3';
            contactObj1.AccountId = accObj.Id;
            contactObj1.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj1.Member_ID__c = 'M123456-02';
            contactObj1.Member_Subscriber_Relationship__c  = 'Spouse';
            insert contactObj1;
            // Assert to check Contact is Created successfully
            system.assert(contactObj1.id!=null);
            
            Contact contactObj2 = new Contact();
            contactObj2.LastName = 'Test C4';
            contactObj2.AccountId = accObj.Id;
            contactObj2.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('SHP Provider').RecordTypeId;
            contactObj2.Supplier_NPI__c = '3222244';
            contactObj2.Supplier_TIN_Address__c = '1200 Creek side\n\nFolsom, CA 95600-1000';
            insert contactObj2;
            // Assert to check Contact is Created successfully
            system.assert(contactObj2.id!=null);
            
            Case caseObj =  new Case();
            caseObj.contactId = contactObj.Id;
            caseObj.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('Correspondence').RecordTypeId;
            caseObj.subject = 'Test Case';
            insert caseObj;
            // Assert to check Contact is Created successfully
            system.assert(caseObj.id!=null);

            Correspondence__c corresObj1 = new Correspondence__c();
            corresObj1.Contact__c = contactObj2.Id;
            corresObj1.Street__c = 'Test 1';
            corresObj1.City__c = 'Test 1';
            corresObj1.State__c = 'Test 1';
            corresObj1.Country__c  = 'Test 1';
            corresObj1.ZipCode__c= 'Test 1';
            corresObj1.Member_Type__c = 'Member';
            corresObj1.Correspondence_Type__c = '';
            corresObj1.Date_Sent_To_Vendor__c = System.today();
            corresObj1.service_Request__c = caseObj.Id;
            corresObj1.Relationship_To_Sub__c = 'Self';
            corresObj1.Fax_Number__c = '222211';
            corresObj1.Address_same_as_Default__c = true;
            corresObj1.Vehicle_of_Correspondence__c= 'Email;Fax;';
            corresObj1.Email_Id__c = 'Testrecord@test.com';
            corresObj1.Status__c = 'New';
            corresObj1.Comments__c = 'TestComment';
            insert corresObj1;
            // Assert to check Correspondence is Created successfully
            system.assert(caseObj.id!=null);
            
            Blob b = Blob.valueOf('Test Data');  
            Attachment attachment = new Attachment();  
            attachment.ParentId = caseObj.id;  
            attachment.Name = 'Test Attachment for Parent';  
            attachment.Body = b; 
            insert(attachment);
            // Assert to check attachment is Created successfully
            system.assert(caseObj.id!=null);
            
            Test.StartTest();
            CorrespondenceCls correspondenceClsObj= new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c()));
            correspondenceClsObj.saveCorrespondence();
            
            correspondenceClsObj.correspondenceObj.Vehicle_of_Correspondence__c = 'Email';
            correspondenceClsObj.correspondenceObj.Email_Id__c = 'Testrecord@test.com';
            correspondenceClsObj.correspondenceObj.Status__c = 'Pending';
            
            correspondenceClsObj.saveCorrespondence();
            correspondenceClsObj.correspondenceObj.Status__c = 'Closed';
            correspondenceClsObj.correspondenceObj.Service_Request__c = caseObj.id;
            correspondenceClsObj.correspondenceObj.Contact__c = contactObj.id;
            correspondenceClsObj.saveCorrespondence();
            correspondenceClsObj.attachment.OwnerId = Userinfo.getUserId();
            correspondenceClsObj.attachment.ParentId = caseObj.id ;
            correspondenceClsObj.attachment.body=Blob.valueOf('Unit Test Attachment Body');
            
            correspondenceClsObj.upload();
                        
            correspondenceClsObj= new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c(id=correspondenceClsObj.correspondenceObj.id)));
            Test.StopTest();
        } catch(Exception ex) {}
    }
    
    
    private static testMethod void testMethod4() {
        try {
            Account accObj = new Account();
            accObj.Name = 'Test Account';
            insert accObj;
            //Assert to check Account is created  successfully
            system.assert(accObj.id!=null);
            
            Contact contactObj = new Contact();
            contactObj.LastName = 'Test C2';
            contactObj.AccountId = accObj.Id;
            contactObj.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj.Member_ID__c = 'M123456-01';
            contactObj.Member_Subscriber_Relationship__c  = 'Self';
            contactObj.mailingstreet = 'Test Street';
            contactObj.mailingcity = 'Test Street';
            contactObj.mailingstate = 'Test Street';
            contactObj.mailingcountry = 'Test Street';
            contactObj.MailingPostalCode= 'Test Street';
            insert contactObj;
           //Assert to check Contact  is created  successfully
            system.assert(contactObj.id!=null); 
            
            Contact contactObj1 = new Contact();
            contactObj1.LastName = 'Test C3';
            contactObj1.AccountId = accObj.Id;
            contactObj1.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Member').RecordTypeId;
            contactObj1.Member_ID__c = 'M123456-02';
            contactObj1.Member_Subscriber_Relationship__c  = 'Spouse';
            insert contactObj1;
             //Assert to check Contact  is created  successfully
            system.assert(contactObj1.id!=null); 
            
            
            Contact contactObj2 = new Contact();
            contactObj2.LastName = 'Test C4';
            contactObj2.AccountId = accObj.Id;
            contactObj2.RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('SHP Provider').RecordTypeId;
            contactObj2.Supplier_NPI__c = '3222244';
            contactObj2.Supplier_TIN_Address__c = '1200 Creek side\n\nFolsom, CA 95600-1000';
            insert contactObj2;
            //Assert to check Contact  is created  successfully
            system.assert(contactObj2.id!=null);
            
            Case caseObj =  new Case();
            caseObj.contactId = contactObj.Id;
            caseObj.RecordTypeId = Schema.SObjectType.Case.RecordTypeInfosByName.get('Correspondence').RecordTypeId;
            caseObj.subject = 'Test Case';
            insert caseObj;
            //Assert to check Case  is created  successfully
            system.assert(caseObj.id!=null);
            
            Correspondence__c corresObj = new Correspondence__c();
            corresObj.Contact__c = contactObj.Id;
            corresObj.Street__c = 'Test 1';
            corresObj.City__c = 'Test 1';
            corresObj.State__c = 'Test 1';
            corresObj.Country__c  = 'Test 1';
            corresObj.ZipCode__c= 'Test 1';
            corresObj.Member_Type__c = 'Member';
            corresObj.Correspondence_Type__c = '';
            corresObj.Date_Sent_To_Vendor__c = System.today();
            corresObj.service_Request__c = caseObj.Id;
            corresObj.Relationship_To_Sub__c = 'Self';
            corresObj.Fax_Number__c = '222211';
            corresObj.Address_same_as_Default__c = true;
            corresObj.Vehicle_of_Correspondence__c= 'Email;Fax;';
            corresObj.Email_Id__c = 'Testrecord@test.com';
            corresObj.Status__c = 'New';
            corresObj.Comments__c = 'TestComment';
            insert corresObj;
            //Assert to check Correspondence  is created  successfully
            system.assert(corresObj.id!=null);
            
            Correspondence_Comments__c correscommentsObj = new Correspondence_Comments__c();
            correscommentsObj.Comments__c = corresObj.Comments__c;
            correscommentsObj.Correspondence__c = corresObj.id;
            insert correscommentsObj;
            //Assert to check Correspondence  comment is created  successfully
            system.assert(correscommentsObj.id!=null);
            
            Correspondence__c corresObj1 = new Correspondence__c();
            corresObj1.Contact__c = contactObj2.Id;
            corresObj1.Street__c = 'Test 1';
            corresObj1.City__c = 'Test 1';
            corresObj1.State__c = 'Test 1';
            corresObj1.Country__c  = 'Test 1';
            corresObj1.ZipCode__c= 'Test 1';
            corresObj1.Member_Type__c = 'Member';
            corresObj1.Correspondence_Type__c = '';
            corresObj1.Date_Sent_To_Vendor__c = System.today();
            corresObj1.service_Request__c = caseObj.Id;
            corresObj1.Relationship_To_Sub__c = 'Self';
            corresObj1.Fax_Number__c = '222211';
            corresObj1.Address_same_as_Default__c = true;
            corresObj1.Vehicle_of_Correspondence__c= 'Email;Fax;';
            corresObj1.Email_Id__c = 'Testrecord@test.com';
            corresObj1.Status__c = 'New';
            corresObj1.Comments__c = 'TestComment';
            insert corresObj1;
            //Assert to check Correspondence  is created  successfully
            system.assert(corresObj.id!=null);
            
            Correspondence_Comments__c correscommentsObj1 = new Correspondence_Comments__c();
            correscommentsObj1.Comments__c = corresObj1.Comments__c;
            correscommentsObj1.Correspondence__c = corresObj1.id;
            insert correscommentsObj1;
           //Assert to check Correspondence  comment is created  successfully
            system.assert(correscommentsObj.id!=null);
            
            Test.StartTest();
            ApexPages.currentPage().getParameters().put('ServiceId',caseObj.Id);
            ApexPages.currentPage().getParameters().put('id',corresObj1.Id);
            CorrespondenceCls correspondenceClsObj= new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c()));
            
            correspondenceClsObj.correspondenceObj.Vehicle_of_Correspondence__c = 'Email';
            correspondenceClsObj.correspondenceObj.Email_Id__c = 'Testrecord@test.com';
            correspondenceClsObj.correspondenceObj.Status__c = Label.CL05_Closed;
            correspondenceClsObj.correspondenceObj.Closed_Date__c = System.now();
            correspondenceClsObj.correspondenceObj.City__c ='';
            correspondenceClsObj.correspondenceObj.State__c = '';
            correspondenceClsObj.correspondenceObj.ZipCode__c = '';
            correspondenceClsObj.correspondenceObj.Street__c = '';
            correspondenceClsObj.correspondenceObj.Comments__c = 'Test Comment';
            
           
            system.debug('@@corres Id after save : '+ correspondenceClsObj.correspondenceObj.id);
            correspondenceClsObj.correspondenceObj.Status__c = 'Closed';
            correspondenceClsObj.correspondenceObj.Service_Request__c = caseObj.id;
            correspondenceClsObj.correspondenceObj.Contact__c = contactObj.id;
            System.currentPageReference().getParameters().put('corresid', correspondenceClsObj.correspondenceObj.id);
            System.currentPageReference().getParameters().put('serviceId', caseObj.Id);
            correspondenceClsObj.saveCorrespondence();
             Test.setCurrentPageReference(new PageReference('Page.Correspondence')); 
            System.currentPageReference().getParameters().put('corresid', correspondenceClsObj.correspondenceObj.id);
            correspondenceClsObj.getAttachment();
            correspondenceClsObj.attachment.OwnerId = Userinfo.getUserId();
            correspondenceClsObj.attachment.ParentId = correspondenceClsObj.correspondenceObj.id ;
            correspondenceClsObj.attachment.body=Blob.valueOf('Unit Test Attachment Body');
                       
            
            correspondenceClsObj.upload();
                        
            //correspondenceClsObj= new CorrespondenceCls(new ApexPages.StandardController(new Correspondence__c(id=correspondenceClsObj.correspondenceObj.id)));
            Test.StopTest();
        } catch(Exception ex) {}
    }
}