Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <label>Employer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calpers</fullName>
                </value>
                <value>
                    <fullName>Jumbo (&gt;1000)</fullName>
                </value>
                <value>
                    <fullName>Key Accounts</fullName>
                </value>
                <value>
                    <fullName>Labor and Trust</fullName>
                </value>
                <value>
                    <fullName>Large Group (251-1000)</fullName>
                </value>
                <value>
                    <fullName>Large Mid-Market Group (101 - 250)</fullName>
                </value>
                <value>
                    <fullName>Mid-Market Group (51-250)</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Small Group (1 - 50)</fullName>
                </value>
                <value>
                    <fullName>Small Group (2-50)</fullName>
                </value>
                <value>
                    <fullName>Small Mid-Market Group (51 - 100)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Association__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Plan_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Plan Metadata</label>
        <referenceTo>Benefit_Plan_Metadata__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFP_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFP Form</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Incumbent_Carrier__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>RFP_Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Incumbent_Carrier__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Sign_Off__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Sign Off</label>
        <referenceTo>Sold_Sign_Off__c</referenceTo>
        <relationshipLabel>Benefit Plan Associations</relationshipLabel>
        <relationshipName>Benefit_Plan_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Benefit Plan Association</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Benefit_Plan_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Grid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Grid</label>
        <referenceTo>SHP_Benefit_Grid__c</referenceTo>
        <relationshipLabel>Benefit Plan Metadata</relationshipLabel>
        <relationshipName>Benefit_Plan_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Plan_ID__c</fullName>
        <label>Benefit Plan ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Plan Metadata</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Plan Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Incumbent_Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>Opportunity__r.Employer_Type__c</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incumbent_Carrier__c</fullName>
        <description>Req 3389</description>
        <label>Incumbent Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AETNA</fullName>
                </value>
                <value>
                    <fullName>ANTHEM</fullName>
                </value>
                <value>
                    <fullName>BLUE SHIELD</fullName>
                </value>
                <value>
                    <fullName>CAL CHOICE</fullName>
                </value>
                <value>
                    <fullName>CALPERS</fullName>
                </value>
                <value>
                    <fullName>CHINESE COMMUNITY HEALTH PLAN</fullName>
                </value>
                <value>
                    <fullName>CIGNA</fullName>
                </value>
                <value>
                    <fullName>HEALTH NET</fullName>
                </value>
                <value>
                    <fullName>SELF FUNDED</fullName>
                </value>
                <value>
                    <fullName>UNITED</fullName>
                </value>
                <value>
                    <fullName>WHA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>KAISER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RFP Form/Incumbent Carriers</relationshipLabel>
        <relationshipName>Incumbent_Carriers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFP Form/Incumbent Carrier</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Incumbent Carrier No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFP Form/Incumbent Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>TEXT(Account.Employer_Type__c)</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>RFP_Form__r.Employer_Type__c</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFP_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RFP Form</label>
        <referenceTo>Incumbent_Carrier__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SHP Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SHP Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Rates__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFP_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFP Form</label>
        <referenceTo>Incumbent_Carrier__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Sign_Off__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Sign Off</label>
        <referenceTo>Sold_Sign_Off__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rates</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/SHP_Benefit_Grid__c.object
<CustomObject>
    <description>This Object is Used to capture the information related to Benefit Grid Data.</description>
    <fields>
        <fullName>Benefit_Plan_ID__c</fullName>
        <label>Benefit Plan ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHP_Benefit_Plan_Year__c</fullName>
        <description>Req number 3391  added benefit plan for 2016</description>
        <label>Benefit Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <recordTypes>
        <fullName>Medical</fullName>
        <active>true</active>
        <description>This record type is used to create/update Medical Plans</description>
        <label>Medical</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Sold_Sign_Off__c.object
<CustomObject>
    <fields>
        <fullName>Employer_Type__c</fullName>
        <formula>Quote__r.Employer_Type__c</formula>
        <label>Employer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sold Sign Offs</relationshipLabel>
        <relationshipName>Sold_Sign_Offs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFP_Form__c</fullName>
        <formula>Quote__r.RFP_Form__r.Name</formula>
        <label>RFP Form</label>
        <type>Text</type>
    </fields>
    <label>Sold Sign Off</label>
    <nameField>
        <displayFormat>SSO-{000000}</displayFormat>
        <label>Sold Sign Off  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sold Sign Offs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/SSOTrigger_Test.cls
/* 
     Class Name: SSOTrigger_Test 
     Author: IDC Offshore
     Date: 06-Dec-2016
     Description: Test class for SoldSignOff Trigger.
*/
@isTest
private class SSOTrigger_Test {
    private static Account acc;
    private static Opportunity opp;
    private static Incumbent_Carrier__c rfp;
    private static Proposal__c quote;
    private static Sold_Sign_Off__c sso;
    private static Rates__c rate;
    private static Rate_Card__c ratecard;
    private static Benefit_Plan_Association__c bpa;
    private static Benefit_Plan_Metadata__c bpm;
    private static SHP_Benefit_Grid__c grid;
    private static Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHP Sales Employer').getRecordTypeId();
    private static Id incRecordTypeId = Schema.SObjectType.Incumbent_Carrier__c.getRecordTypeInfosByName().get('RFP Form').getRecordTypeId();
    private static Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('SHP Sales Opportunity').getRecordTypeId();
    
    /*Method to Set up Test data*/
    private static testMethod void setUpTestData(){
        
        List<SF_P2A_Market_Segments_Mapping__c> listp2amarketseg = HighRoads_TestDataUtility.insertP2AMarketSegmentsCS();
        insert listp2amarketseg;
        
        acc = new Account();
        acc.Name = 'TestAcc1';
        acc.RecordTypeId = accRecordTypeId;
        acc.NumberOfEmployees = 50;
        acc.Industry = 'Hospitaity';
        acc.Employer_Type__c = 'Labor and Trust';
        insert acc;
        
        opp = new Opportunity();
        opp.Name = 'TestOpp1';
        opp.RecordTypeId = oppRecordTypeId;
        opp.AccountId = acc.id;
        opp.type = 'New Business';
        opp.CloseDate = Date.Today()+30;
        opp.StageName = 'Pending Broker';
        insert opp;
        
        rfp = new Incumbent_Carrier__c();
        rfp.RecordtypeId = incRecordTypeId;
        rfp.Opportunity__c = opp.id;
        insert rfp;
        
        quote = new Proposal__c();
        quote.Opportunity_ID__c = opp.id;
        quote.RFP_Form__c = rfp.id;
        insert quote;
        
        grid = new SHP_Benefit_Grid__c();
        grid.Benefit_Plan_ID__c = 'HE02';
        grid.Market_Segment__c = 'Large Group';
        grid.SHP_Benefit_Plan_Year__c = '2016';
        grid.Plan_Name__c = 'HE02-2016';
        insert grid;
        
        bpm = new Benefit_Plan_Metadata__c();
        bpm.Name = 'HE02';
        bpm.Medical_OR_Rider__c = 'Medical';
        bpm.Product_Class__c = 'Medical';
        bpm.Effective_Date__c = Date.today();
        bpm.Market_Segment__c = 'Large Group';
        bpm.Plan_Type__c = 'Standard';
        bpm.Benefit_Plan_ID__c = 'HE02';
        bpm.Benefit_Grid__c = grid.id;
        bpm.Plan_Name__c = 'HE02-2016';
        insert bpm;
        
        bpa = new Benefit_Plan_Association__c();
        bpa.Benefit_Plan_Metadata__c = bpm.id;
        bpa.Version_Number__c = 1;
        bpa.Name = 'HE02-2016';
        bpa.Proposal__c = quote.id;
        insert bpa;
    }
    
    /* Test method to test if Plans in related Quote are Copied to SSO When SSO is inserted, Custom validations and creation of SCN when SSO is approved*/
    private static testMethod void testSSOApproval(){
        Test.startTest(); 
        setUpTestData();
            sso = new Sold_Sign_Off__c();
            sso.Opportunity_ID__c = opp.id;
            sso.Quote__c = quote.id;
            sso.Stage__c = 'Draft';
            sso.SSO_RSO_Due_Date__c = Date.today()+30;
            insert sso;
            
            rate = new Rates__c();
            rate.Sold_Sign_Off__c = sso.id;
            rate.Tier_2_EE__c = '12';
            rate.Plan_Name__c = 'HE02-2016'; 
            insert rate;
        
            ratecard = new Rate_Card__c();
            insert ratecard;
        
            bpa.SSO_Rate_Card__c = ratecard.id;
            update bpa;
        
            rate.Rate_Card_ID__c = ratecard.id;
            update rate;
            
            try{
                sso.Stage__c = 'Submitted to Underwriting';
                update sso;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.HR215_SSOAttachmentMandatoryBeforeSubmitting) ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
        
            Blob b = Blob.valueOf('test data');
            Attachment attachment = new Attachment(); 
            attachment.ParentId = sso.id; 
            attachment.Name = 'Test Attachment for Parent'; 
            attachment.Body = b;   
            insert(attachment);
        
            sso.Stage__c = 'Submitted to Underwriting';
            update sso;
        
            try{
                sso.Stage__c = 'Approved by Underwriting';
                update sso;
            }catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.HR190_SCNForClosedWonOpp) ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
            
            opp.StageName = 'Closed Won';
            update opp;
        	HighRoads_SoldSignOffTriggerHelper.isBeforeUpdate = true;
        	HighRoads_DocGenRequest.isOpportunityAfterUpdate = true;
            sso.Stage__c = 'Approved by Underwriting';
            update sso;
        
        
        Test.stopTest();
    }
}