Sutter Health/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>SHP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>SHMMN Broker</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Un Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Broker_Agent_Status__c</fullName>
        <label>Broker Agent Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Contracted</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Broker Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Broker Rep</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>Staff Contact</fullName>
                </value>
                <value>
                    <fullName>Other Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Employer_Group_Data__c.object
<CustomObject>
    <description>This object is created for SCN and develop Req -3268
 It split into three parts
1.Sold case Notifaction
2. Medical Plan
3.Non standard medical plan</description>
    <fields>
        <fullName>BillingContact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity_Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sold Case Notification (Contact)</relationshipLabel>
        <relationshipName>Sold_Case_Notification3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EDI_Vendor_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Req-3384</description>
        <label>EDI Vendor Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Archive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sold Case Notification (Contact)</relationshipLabel>
        <relationshipName>Sold_Case_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HREmployer_Portal_Name1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HR Employer Portal Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity_Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sold Case Notification (Contact)</relationshipLabel>
        <relationshipName>Sold_Case_Notification4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HREmployer_Portal_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HR Employer Portal Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity_Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sold Case Notification (Contact)</relationshipLabel>
        <relationshipName>Sold_Case_Notification5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HREnrollment_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HREnrollment Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity_Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sold Case Notification (Contact)</relationshipLabel>
        <relationshipName>Sold_Case_Notification2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_accumulators_previous_Carrier__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member Accumulators Previous  Carrier?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to implement the Lookup filter on Contact. It will be autopopulated with the Opportunity&apos;s Account Name. DO NOT Put on page layout</description>
        <inlineHelpText>Please do not change the Opportunity Account Name value</inlineHelpText>
        <label>Opportunity Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sold Case Notification</relationshipLabel>
        <relationshipName>Sold_Case_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sold Case Notification</relationshipLabel>
        <relationshipName>Sold_Case_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Underwriting Review</fullName>
                </value>
                <value>
                    <fullName>Rejected by Underwriting</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Enrollment QA Pass</fullName>
                </value>
                <value>
                    <fullName>Enrollment QA Fail</fullName>
                </value>
                <value>
                    <fullName>Submitted for QA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sold Case Notification</label>
    <nameField>
        <displayFormat>SCN-{00000}</displayFormat>
        <label>Sold Case Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sold Case Notification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broker1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a Broker</inlineHelpText>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4)</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.Field- Broker</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>SHP Sales Broker,SHP Sales Broker Read Only, SHMMN Broker</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>Contracted, Prospect, Active</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SHMMN, System Administrator, SHP</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Rep1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a Broker Rep</inlineHelpText>
        <label>Broker Rep</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria. Field- Broker Rep</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Broker1__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Broker_Agent_Status__c</field>
                <operation>equals</operation>
                <value>a,Active, Prospect, Contracted</value>
            </filterItems>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>equals</operation>
                <value>Broker Rep, Agent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Archive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SHMMN, System Administrator, SHP</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>contains</operation>
                <value>SHMMN Broker, SHP Sales Broker Contact,SHP Sales Broker Contact Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <description>Status of the Opportunity</description>
        <inlineHelpText>Select an Opportunity Status</inlineHelpText>
        <label>PPO Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote Review</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>Underwriting Decision</fullName>
                </value>
                <value>
                    <fullName>Underwriting - Mid/Large Group</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opp_Renewed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Req 3268  -- Checked means the renewal opportunity has been created for this.</description>
        <label>Renewal Opportunity Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_end_date__c</fullName>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Team__c</fullName>
        <label>Sales Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RGA</fullName>
                </value>
                <value>
                    <fullName>PBJ</fullName>
                </value>
                <value>
                    <fullName>M2N</fullName>
                </value>
                <value>
                    <fullName>BAY</fullName>
                </value>
                <value>
                    <fullName>SHP</fullName>
                </value>
                <value>
                    <fullName>TSS</fullName>
                </value>
                <value>
                    <fullName>SHMMN</fullName>
                </value>
                <value>
                    <fullName>Amy Schenone</fullName>
                </value>
                <value>
                    <fullName>Gary Kaye</fullName>
                </value>
                <value>
                    <fullName>Kim McAndrew</fullName>
                </value>
                <value>
                    <fullName>Sondra Maas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/RenewOpportunity_Batch_test.cls
/**********************************************************************
 Name: RenewOpportunity_Batch_test
 Copyright © 2015 IDC Offshore
 ======================================================
 ======================================================
 Purpose:
 This is the test class for Renew Opportunity Batch class.
 ======================================================
 ======================================================
 History
 -------
 VERSION  AUTHOR        DATE        DETAIL                 Description
 1.0      IDC Offshore  2/9/2015  Development complete   This class is defined to test Renew Opportunity Batch class.
 2.0      IDC Offshore  12/18/2015  Class Optimisation   Incorporated changes to implement best test practices in the test class.
 3.0      IDC Offshore  05/05/2016  Req-3826 changes      Added condition for Opportunity record type as part of Req-3826 changes.
 ***********************************************************************/
 
@isTest
private class RenewOpportunity_Batch_test {
    
    /** Setting the value of record type names in String variables which will be used in the test method **/
    public static String ACNRECTYPE = 'SHP Sales Broker';
    public static String PARENTACCOUNTTYPE = 'SHP Sales Employer';
    public static String CONTACTRECTYPE = 'SHP Sales Broker Contact';
        
    /*******************************************************************
     Purpose: method to create test data used by all test methods
     Parameters: N/A 
     Returns: void
     Throws [Exceptions]: N/A
     ********************************************************************/
    
    @testSetup 
    static void createTestData() {
     
        Account testAccount = new Account(RecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get(PARENTACCOUNTTYPE).RecordTypeId,
                                          Name='Test Account',
                                          Status__c= 'Contracted',
                                          NumberOfEmployees = 300);
     
        Database.insert(testAccount);
        
        Account testAccount1 = new Account(RecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get(PARENTACCOUNTTYPE).RecordTypeId,
                                          Name='TestAccount1',
                                          Status__c= 'Contracted',
                                          NumberOfEmployees = 300);
     
        Database.insert(testAccount1);
        
        Account testBrokerAccount = new Account(RecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByName.get(ACNRECTYPE).RecordTypeId,
                                          Name='Test Account SCN',
                                          Status__c= 'Contracted',
                                          Type = 'Broker',
                                          NumberOfEmployees = 300);
     
        Database.insert(testBrokerAccount);
        
        Id RecordTypeIdOfBroker = Schema.SObjectType.Account.RecordTypeInfosByName.get(ACNRECTYPE).RecordTypeId;
        Id RecordTypeIdOfAccount = Schema.SObjectType.Account.RecordTypeInfosByName.get(PARENTACCOUNTTYPE).RecordTypeId;
        
        Id IdofAccount = [SELECT Id FROM Account WHERE RecordTypeId = :RecordTypeIdOfAccount limit 1].Id;
        
        Id IdofBrokerAccount = [SELECT Id FROM Account WHERE RecordTypeId = :RecordTypeIdOfBroker limit 1].Id;
        
        Contact testContact = new Contact(RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get(CONTACTRECTYPE).RecordTypeId,
                                          LastName = 'Test contact',
                                          AccountId = IdofBrokerAccount,
                                          Broker_Agent_Status__c = 'Prospect',
                                          Type__c = 'Broker Rep'
                                          );
        
        Contact scnContact = new Contact(RecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get(CONTACTRECTYPE).RecordTypeId,
                                          LastName = 'SCNcontact',
                                          AccountId = IdofAccount,
                                          Broker_Agent_Status__c = 'Prospect',
                                          Type__c = 'Broker Rep'
                                          );                                
        Database.insert(testContact);
        Database.insert(scnContact);
        Id IdofContact = [SELECT Id FROM Contact limit 1].Id;
        
        List<Opportunity> OpplistInsert = new List<Opportunity>();
        
        List<Employer_Group_Data__c> SCNList = new List<Employer_Group_Data__c>();
        List<Medical_Plan__c> MedPlanList1 = new List<Medical_Plan__c>();
        List<Medical_Plan__c> MedPlanList2 = new List<Medical_Plan__c>();
        List<Opportunity> OpplistwithoutSCNInsert = new List<Opportunity>();
        
        for (integer i=0;i<20;i++){
          Opportunity testOpportunity = new Opportunity( Name = 'Test Opportunity SCN' + i,
                                                       Type = 'New Business',
                                                       AccountId = IdofAccount,
                                                       StageName = 'Closed Won',
                                                       Amount = 450,
                                                       CloseDate = Date.today()+25,
                                                       Plan_end_date__c = Date.today()+110,
                                                       Broker1__c = IdofBrokerAccount,
                                                     //  Broker_Rep1__c = IdofContact,
                                                       Current_Status__c = 'Information Requested',
                                                       Opp_Renewed__c =false,
                                                       //Added condition for opportunity record type as part of Req-3826 changes
                                                       RecordTypeID = System.label.SHP_Sales_Opportunity_Id,
                                                       Sales_Team__c = 'TSS');
                                                OpplistInsert.add(testOpportunity )   ;     
                                                       
        
        }
        
         for (integer i=0;i<20;i++){
          Opportunity testOpportunity = new Opportunity( Name = 'Test Opportunity SCN' + i,
                                                       Type = 'New Business',
                                                       AccountId = IdofAccount,
                                                       StageName = 'Closed Won',
                                                       Amount = 450,
                                                       CloseDate = Date.today()+25,
                                                       Plan_end_date__c = Date.today()+110,
                                                       Broker1__c = IdofBrokerAccount,
                                                     //  Broker_Rep1__c = IdofContact,
                                                       Current_Status__c = 'Information Requested',
                                                       Opp_Renewed__c =false,
                                                       //Added condition for opportunity record type as part of Req-3826 changes
                                                        RecordTypeID = System.label.SHP_Sales_Opportunity_Id,
                                                       Sales_Team__c = 'TSS');
                                                OpplistwithoutSCNInsert .add(testOpportunity )   ;     
                                                       
        
        }
      
        //Insert the list of opportunities                                                
        Database.insert(OpplistInsert);
        Database.insert(OpplistwithoutSCNInsert);
        
          for (integer i=0;i<20;i++){
           Employer_Group_Data__c SCN = new Employer_Group_Data__c();
           SCN.Member_accumulators_previous_Carrier__c = true;
           SCN.Opportunity__c = OpplistInsert[i].id;
           SCN.Opportunity_Account_Name__c = OpplistInsert[i].AccountId   ;
           SCN.Stage__c = 'Approved';
           SCN.BillingContact_Name__c = scnContact.Id;
           SCN.EDI_Vendor_Name__c = scnContact.Id;
           SCN.HREmployer_Portal_Name__c = scnContact.Id;
           SCN.HREmployer_Portal_Name1__c = scnContact.Id;
           SCN.HREnrollment_Name__c = scnContact.Id;
           SCN.Vendor_Contact_Name__c = scnContact.Id;
           SCNList.add(SCN) ;
          }
         
          //List of SCNS are being inserted for test data
         Database.insert( SCNList);
         
         for (integer i=0;i<20;i++)
         {
         Medical_Plan__c mplan =  new Medical_Plan__c();
         mplan.Sold_Case_Notification__c =SCNList[i].id;
         mplan.Acupuncture_Other__c = 'Acupunture 1';
         MedPlanList1.add(mplan);
         }
          Database.insert(MedPlanList1);
          
         for (integer i=0;i<20;i++)
         {
         Medical_Plan__c mplan =  new Medical_Plan__c();
         mplan.Sold_Case_Notification__c =SCNList[i].id;
         mplan.Acupuncture_Other__c = 'Acupunture 2';
         MedPlanList2.add(mplan);
         }
          Database.insert(MedPlanList2);

       /*********************************************************************** 
        Verifying the id values of records created above using system.assert() 
        Expected Result: id values should not be null 
        Actual Result: id values should not be null 
       ************************************************************************/
        system.assert(testAccount.id!=null);
        system.assert(testBrokerAccount.id!=null);
        system.assert(testContact.id!=null);          
             
    }
    
    /*******************************************************************
     Purpose: method to test the logic written in RenewOpportunity_Batch class for SCN and Medical Plan records 
              to create the new Opportuity for all those Opprtunities in Closed Won State
              whose Plan End Date is less than 120 Days from Today. The class creates the deep clone of opportunity 
              copying the latest approved SCN and medical plans of Old Opportunity to newly Created Opportunity. 
              Also Opportunities without SCN are clonned without SCN.
     Parameters: N/A 
     Returns: void
     Throws [Exceptions]: N/A
     ********************************************************************/
    
    public static testMethod void RenewOpportunity_Batchtest(){
       
        /** Instantiating the Medical Plan records list to be used in verifying class logic post successful run in system.assert() method **/  
        List<Medical_Plan__c> renewedMedPlanlist = new List<Medical_Plan__c>();
          
        Test.startTest();
        
        /**  Schedule the batch job using system.schedule() method **/
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        RenewOpportunity_Batch runBatch1 = new RenewOpportunity_Batch();
        String jobId = System.schedule('ScheduleApexClassTest',CRON_EXP,runBatch1 );
         
        /** Instantiating the batch class  **/
        RenewOpportunity_Batch runBatch = new RenewOpportunity_Batch();
        Id batchprocessid = Database.executeBatch(runBatch,200);
        Test.stopTest();
                       
        List<Opportunity> renewedOppList = new List<Opportunity>();
        List<Employer_Group_Data__c>  renewedSCNList = new List<Employer_Group_Data__c>();
            
        renewedOppList = [SELECT Id,(SELECT Id FROM Sold_Case_Notification__r) FROM Opportunity WHERE Opp_Renewed__c = true];
        renewedSCNList = [SELECT id,Stage__c,Opportunity__c,(SELECT id FROM Medical_Plans__r) FROM Employer_Group_Data__c WHERE Opportunity__r.Renewed_Opportunity__c = true];
        
        renewedMedPlanlist = [SELECT Id FROM Medical_Plan__c WHERE Sold_Case_Notification__c IN :renewedSCNList];
        
        /*********************************************************************** 
        Verifying the size of Medical Plan and SCN records 
        Expected Result: size for SCN is 20 and Medical plan is 40
        Actual Result: size for SCN is 20 and Medical plan is 40
        ************************************************************************/
       
        System.assertEquals(renewedSCNList.size(),20);
        System.assertEquals(renewedMedPlanlist.size(),40);
             
        
    }
    
    /*******************************************************************
     Purpose: method to test Negative Scenario in RenewOpportunity_Batch class for SCN and Medical Plan records 
              to create the new Opportunity for all those Opportunities in Closed Won State
              whose Plan End Date is less than 120 Days from Today. The class creates the deep clone of opportunity 
              copying the latest approved SCN and medical plans of Old Opportunity to newly Created Opportunity. 
              Also Opportunities without SCN are cloned without SCN.
     Parameters: N/A 
     Returns: void
     Throws [Exceptions]: N/A
     ********************************************************************/
    
    public static testMethod void RenewOpportunity_BatchtNegativeTest(){
       
        /** Instantiating the Medical Plan records list to be used in verifying class logic post successful run in system.assert() method **/  
        List<Medical_Plan__c> renewedMedPlanlist = new List<Medical_Plan__c>();
        list<Opportunity> lstOpp =[SELECT Id,Opp_Renewed__c FROM Opportunity WHERE Opp_Renewed__c = false];
        Test.startTest();
        for(Opportunity tempOpp : lstOpp){
        tempOpp.Opp_Renewed__c = true;
        }
        update lstOpp;
        Test.stopTest();
        
        
        /**  Schedule the batch job using system.schedule() method **/
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        RenewOpportunity_Batch runBatch1 = new RenewOpportunity_Batch();
        String jobId = System.schedule('ScheduleApexClassTest',CRON_EXP,runBatch1 );
         
        /** Instantiating the batch class  **/
        RenewOpportunity_Batch runBatch = new RenewOpportunity_Batch();
        Id batchprocessid = Database.executeBatch(runBatch,200);
        
                       
        List<Opportunity> renewedOppList = new List<Opportunity>();
            
        renewedOppList = [SELECT Id FROM Opportunity WHERE StageName = : System.Label.Renewed_Opportunity_Stage];
        
        /*********************************************************************** 
        Verifying Clone Opportunity
        Expected Result: size for Clone Opportunity is empty
        Actual Result: size for Clone Opportunity is empty
        ************************************************************************/
        System.assertEquals(renewedOppList.size(),0);   
    }
	
    
    /*******************************************************************
     Purpose: method to test the archive check box in opportunity object flag on contact
     Parameters: N/A 
     Returns: void
     Throws [Exceptions]: N/A
     ********************************************************************/
    
    public static testMethod void RenewOpportunity_BatchOpportunityArchiveTest(){
       Test.startTest();
        /** Instantiating the Medical Plan records list to be used in verifying class logic post successful run in system.assert() method **/  
        Contact conObj = [select id,LastName,Archive__c from Contact where LastName ='Test contact' LIMIT 1];
        conObj.archive__c = true;
        update conObj;
        
        list<Opportunity> lstOpp =[SELECT Id,Broker_Rep1__c,Account_Manager__c,GA_Contact__c FROM Opportunity WHERE Opp_Renewed__c = false];
        
        for(Opportunity tempOpp : lstOpp){
        	tempOpp.Broker_Rep1__c = conObj.Id;
        }
        try{
            update lstOpp;
        }catch(Exception e){
            
        }
        
        for(Opportunity tempOpp : lstOpp){
        	tempOpp.Account_Manager__c = conObj.Id;
        }
        try{
            update lstOpp;
        }catch(Exception e){
            
        }
        
        for(Opportunity tempOpp : lstOpp){
        	tempOpp.GA_Contact__c = conObj.Id;
        }
        try{
            update lstOpp;
        }catch(Exception e){
            
        }
        
        

        
        /**  Schedule the batch job using system.schedule() method **/
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        RenewOpportunity_Batch runBatch1 = new RenewOpportunity_Batch();
        String jobId = System.schedule('ScheduleApexClassTest',CRON_EXP,runBatch1 );
         
        /** Instantiating the batch class  **/
        RenewOpportunity_Batch runBatch = new RenewOpportunity_Batch();
        Id batchprocessid = Database.executeBatch(runBatch,200);
        Test.stopTest();
        
    }
    
     /*******************************************************************
     Purpose: method to test the archive check box in SCN object flag on contact
     Parameters: N/A 
     Returns: void
     Throws [Exceptions]: N/A
     ********************************************************************/
    
    public static testMethod void RenewOpportunity_BatchSCNArchiveTest(){
       Test.startTest();
        Contact conObj = [select id,LastName,Archive__c from Contact where LastName ='SCNcontact' LIMIT 1];
        conObj.archive__c = true;
        update conObj;
        
        

        
        /**  Schedule the batch job using system.schedule() method **/
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        RenewOpportunity_Batch runBatch1 = new RenewOpportunity_Batch();
        String jobId = System.schedule('ScheduleApexClassTest',CRON_EXP,runBatch1 );
         
        /** Instantiating the batch class  **/
        RenewOpportunity_Batch runBatch = new RenewOpportunity_Batch();
        Id batchprocessid = Database.executeBatch(runBatch,200);
        Test.stopTest();
                       
          
    }
    
    /*******************************************************************
     Purpose: method to test the lookup filter account ids in SCN is 
			  different with the opportunity account id
     Parameters: N/A 
     Returns: void
     Throws [Exceptions]: N/A
     ********************************************************************/
    
    public static testMethod void RenewOpportunity_BatchSCNTest(){
       Test.startTest();
        ID accountId = [select id from account where name ='TestAccount1' limit 1].ID;
        list<Opportunity> lstOpp =[SELECT Id,AccountId FROM Opportunity WHERE Opp_Renewed__c = false];
        for(Opportunity tempOpp : lstOpp){
            tempOpp.AccountId = accountId;
        }
        update lstOpp;
        
        
        
        /**  Schedule the batch job using system.schedule() method **/
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        RenewOpportunity_Batch runBatch1 = new RenewOpportunity_Batch();
        String jobId = System.schedule('ScheduleApexClassTest',CRON_EXP,runBatch1 );
         
        /** Instantiating the batch class  **/
        RenewOpportunity_Batch runBatch = new RenewOpportunity_Batch();
        Id batchprocessid = Database.executeBatch(runBatch,200);
        Test.stopTest();
         
    }
    
    
    
}