Sutter Health/src/objects/ActiveStatus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ActiveStatus</label>
</CustomObject>

Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Employee_Affiliate_Facility__c</fullName>
        <label>Employee Affiliate Facility</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Bargaining_Union__c</fullName>
        <label>Employee Bargaining Unit</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_EEO_SubCode__c</fullName>
        <label>Employee EEO SubCode</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Employment_Status__c</fullName>
        <label>Employee Employment Status</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Union_Affiliate__c</fullName>
        <label>Employee Union Affiliate</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Work_Email__c</fullName>
        <label>Employee Work Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Employee</fullName>
        <active>true</active>
        <description>Used for employee contact records.</description>
        <label>Employee</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/CS_ManageProfile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting containing Profile Names</description>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <description>Profile Name Strings</description>
        <label>Profile Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CS_ManageProfile</label>
</CustomObject>

Sutter Health/src/objects/PermissionSetFields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <label>FieldAPIName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldValue__c</fullName>
        <label>FieldValue</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PermissionSetFields</label>
</CustomObject>

Sutter Health/src/objects/Salesforce_Affiliates__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Affiliates going live with all of the Portal capabilities</description>
    <fields>
        <fullName>Affiliate_Name__c</fullName>
        <label>Affiliate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSalesforce_True__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isSalesforce True</label>
        <type>Checkbox</type>
    </fields>
    <label>Salesforce Affiliates</label>
</CustomObject>

Sutter Health/src/classes/VFC_OE_14Test.cls
@isTest
private class VFC_OE_14Test {
    static testMethod void testShowArticles() {
        try {
            VFC_OE_14.startDate = System.today() - 10;
            VFC_OE_14.today = System.today();
            VFC_OE_14.endDate = System.today() + 10;
            VFC_OE_14 controllerObj = new VFC_OE_14();
            
            VFC_OE_14.today = System.today();
            VFC_OE_14.endDate = System.today();
            controllerObj = new VFC_OE_14();
            
            VFC_OE_14.today = System.today()+10;
            VFC_OE_14.endDate = System.today();
            controllerObj = new VFC_OE_14();
            
            ID ProfileID = [Select id from Profile where name = 'Community Portal Manager'].id;
            
            List<User> adminUserLst = [select Id from User where Profile.Name = 'System Administrator' and
                                        UserRoleId != null]; 
            
             
            CS_ManageProfile__c csObj = new CS_ManageProfile__c();
            csObj.Name = 'Community_Portal_Manager';
            csObj.Profile_Name__c = 'Community Portal Manager';
            insert csObj; 
             
            CS_ManageProfile__c csObj1 = new CS_ManageProfile__c();
            csObj1.Name = 'Communities_Portal';
            csObj1.Profile_Name__c = 'Community Portal';
            insert csObj1;
            
            ActiveStatus__c obj1 = new ActiveStatus__c();
            obj1.Name = 'AF';
            insert obj1;
             
            Salesforce_Affiliates__c obj2 = new Salesforce_Affiliates__c();
            obj2.Name = 'Sutter Shared Services';
            obj2.Affiliate_Name__c = 'Sutter Shared Services';
            obj2.isSalesforce_True__c = true;
            insert obj2;
             
            PermissionSetFields__c pSCS1 = new PermissionSetFields__c();
            pSCS1.Name = 'AF';
            pSCS1.FieldAPIName__c = 'EMPLOYEE_EMPLOYMENT_STATUS__C';
            pSCS1.FieldValue__c = 'AF';
            insert pSCS1;
             
            PermissionSetFields__c pSCS3 = new PermissionSetFields__c();
            pSCS3.Name = 'Sutter Shared Services';
            pSCS3.FieldAPIName__c = 'Employee_Affiliate_Facility__c'.toUpperCase();
            pSCS3.FieldValue__c = 'Sutter Shared Services';
            insert pSCS3;
             
            PermissionSetFields__c pSCS2 = new PermissionSetFields__c();
            pSCS2.Name = 'SMT 29 LA';
            pSCS2.FieldAPIName__c = 'Employee_Bargaining_Union__c'.toUpperCase();
            pSCS2.FieldValue__c = 'SMT 29 LA';
            insert pSCS2;
            
            PermissionSetFields__c pSCS4 = new PermissionSetFields__c();
            pSCS4.Name = 'CNA';
            pSCS4.FieldAPIName__c = 'Employee_Union_Affiliate__c'.toUpperCase();
            pSCS4.FieldValue__c = 'CNA';
            insert pSCS4;
                         
            Account A1 = new Account(Name = 'Test Account');
            A1.ownerId = adminUserLst[0].id; 
            insert A1;
            
            
            system.runAs(adminUserLst[0]) {
                Test.startTest();
                Schema.DescribeSObjectResult descObj = Schema.SObjectType.Contact; 
                Map<String,Schema.RecordTypeInfo> rtMapByName = descObj.getRecordTypeInfosByName(); 
                Contact C1 = new Contact( AccountID = A1.id, FirstName = 'Test', LastName = 'User', 
                                           email = 'test-user@fakeemail.com' );
                C1.Employee_EEO_SubCode__c = '2';
                C1.Employee_Union_Affiliate__c = 'CNA';
                C1.Employee_Bargaining_Union__c = 'SMT 29 LA';
                C1.Employee_Employment_Status__c = 'AF';
                C1.Employee_Affiliate_Facility__c = 'Sutter Shared Services'; 
                C1.Employee_Work_Email__c = 'test-user@fakeemail.com';
                C1.recordtypeId = rtMapByName.get('Employee').getRecordTypeId();
                insert C1;
                
                Test.stopTest();
            }                        
                         
            User userObj = [select Id from User where email = 'test-user@fakeemail.com']; 
                         
            system.runAs(userObj) {
                controllerObj.gotoLink();
                controllerObj.OE_Recordcount();                 
            }  
                    
            
        } catch(Exception ex) {} 
    }
}