Sutter Health/src/objects/Communication_Log__c.object
<CustomObject>
    <description>Communication log is used to record the Outreach/call details when Outreach staff attempts to contact patient on Pre-visit plan / Gaps in Care.</description>
    <fields>
        <fullName>Call_result__c</fullName>
        <description>Call Result</description>
        <label>Call result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not available</fullName>
                </value>
                <value>
                    <fullName>No Answer/Busy</fullName>
                </value>
                <value>
                    <fullName>Left Message</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Reminder rule failed</fullName>
                </value>
                <value>
                    <fullName>Duplicate reminder</fullName>
                </value>
                <value>
                    <fullName>Delivery type mismatch</fullName>
                </value>
                <value>
                    <fullName>No email address on file</fullName>
                </value>
                <value>
                    <fullName>Missing or Invalid Number</fullName>
                </value>
                <value>
                    <fullName>Incomplete setup to send messages</fullName>
                </value>
                <value>
                    <fullName>Patient updates disabled</fullName>
                </value>
                <value>
                    <fullName>Duplicate update</fullName>
                </value>
                <value>
                    <fullName>Patient not accepting updates</fullName>
                </value>
                <value>
                    <fullName>Patient is not signed up for updates</fullName>
                </value>
                <value>
                    <fullName>Sent to Communication Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments_Spoke_with_Patient__c</fullName>
        <description>LEFT MESSAGE/SPOKE WITH PATIENT - comments</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <description>Contact Name</description>
        <inlineHelpText>Patient Name</inlineHelpText>
        <label>Patient Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department_ID__c</fullName>
        <label>Department ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dialed_Phone__c</fullName>
        <description>Dialed Phone Number</description>
        <label>Phone # dialed</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Documentation_Note__c</fullName>
        <description>Documentation Note (HNO)</description>
        <label>Documentation Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EPIC_Error_Id__c</fullName>
        <label>EPIC Error Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EPIC_Reference__c</fullName>
        <description>EPIC Reference Number</description>
        <label>EPIC Reference #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EPIC_Response_Message__c</fullName>
        <description>EPIC Response Message</description>
        <label>EPIC Response Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EPIC_Sync_Date__c</fullName>
        <description>EPIC Sync Date</description>
        <label>EPIC Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Encounter_Date__c</fullName>
        <description>Encounter Date</description>
        <label>Encounter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Patient_MRN__c</fullName>
        <description>Patient MRN</description>
        <label>Patient MRN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Type_I_CAL_90__c</fullName>
        <label>Phone Type (I CAL 90)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Pager</fullName>
                </value>
                <value>
                    <fullName>Home Fax</fullName>
                </value>
                <value>
                    <fullName>Other Fax</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>TTY</fullName>
                </value>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Work Phone</fullName>
                </value>
                <value>
                    <fullName>Video Phone</fullName>
                </value>
                <value>
                    <fullName>Walkie Talkie</fullName>
                </value>
                <value>
                    <fullName>Txt Reminder</fullName>
                </value>
                <value>
                    <fullName>JDM Comm</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_ID__c</fullName>
        <label>Provider ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Call__c</fullName>
        <defaultValue>&quot;201 - Health Maintenance&quot;</defaultValue>
        <description>Reason for Call</description>
        <label>Reason for Call</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_the_Patient__c</fullName>
        <label>Relationship to the Patient</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>On Call Provider</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Relative</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Significant Other</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                </value>
                <value>
                    <fullName>Niece/Nephew</fullName>
                </value>
                <value>
                    <fullName>Coworker/Associate</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>PCP</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Radiology</fullName>
                </value>
                <value>
                    <fullName>Guarantor</fullName>
                </value>
                <value>
                    <fullName>Carrier</fullName>
                </value>
                <value>
                    <fullName>Employer Group</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Interpreter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Communication Log</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Communication Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Provider_ID__c</fullName>
        <label>Provider ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for provider contact records.</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/AQRSEPICIntegrationController.cls
public class AQRSEPICIntegrationController
{
    
    public void communicationLogCreationInEpic(List<Communication_Log__c> lstCommLog) // need to check whether it is a single record or multiple
    {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        HTTPResponse response = new HTTPResponse();
        list<Communication_Log__c> commLogList = new list<Communication_Log__c>();
        commLogList = lstCommLog;
        List<communicationLogWrapper> lstCommLogWrapper = new List<communicationLogWrapper>();
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setEndpoint(''); //Epic url if token authentication
        request.setBody('');  //USer credential to connect      
        response = http.send(request);
        if(response.getStatusCode()== 200) // authentication success
        {
            request = new HttpRequest();
            http = new Http();
            request.setMethod('PUT');
            //authentication from above callout
            request.setEndpoint(''); // endpoint url
            
            for(Communication_Log__c cl: lstCommLog) 
            {
                communicationLogWrapper clw = new communicationLogWrapper('Gopika','123',cl.Patient_MRN__c,cl.Department_ID__c,cl.Provider_ID__c,cl.Contact_Name__c,cl.Relationship_to_the_Patient__c,cl.Dialed_Phone__c, cl.Phone_Type_I_CAL_90__c,cl.Comments_Spoke_with_Patient__c,cl.Call_result__c,null,cl.Documentation_Note__c,cl.Reason_for_Call__c,String.valueOf(cl.Encounter_Date__c));
                lstCommLogWrapper.add(clw);
            }
            if(!lstCommLogWrapper.isEmpty())
            {
                request.setBody(JSON.Serialize(lstCommLogWrapper));
                response = http.send(request);
                epicResponseWrapper responseWrapper= (epicResponseWrapper)JSON.deserialize(response.getBody(),epicResponseWrapper.class);
                // Map the EPIC error & Reponse(Exception handling) , update the communication logs 
                	for(Communication_Log__c clog: commLogList){
                		clog.EPIC_Error_Id__c = responseWrapper.ErrorID;
                		if(responseWrapper.ErrorID.contains('INVALID-USERID-<UserID>')){
                			clog.EPIC_Response_Message__c = 'User doesn\'t have active record in Epic';	
                		}else if(responseWrapper.ErrorID.contains('INVALID-PATIENT-ID-<PatientID>')){
                			clog.EPIC_Response_Message__c = 'Patient ID is not in Epic';
                		}else if(responseWrapper.ErrorID.contains('INVALID-SHMRN-<PatientSHMRN>')){
                			clog.EPIC_Response_Message__c = 'Patient doesn\'t have Sutter Health MRN';
                		}else if(responseWrapper.ErrorID.contains('INVALID-MATCH-PATIENTID/SHRMN-<PatientID>/<PatientSHMRN>')){
                			clog.EPIC_Response_Message__c = 'Sutter Health MRN does not belong to Patient ID';
                		}else if(responseWrapper.ErrorID.contains('INVALID-DEPT-ID-<EncounterDept>')){
                			clog.EPIC_Response_Message__c = 'Epic departmeint ID is not found';
                		}else if(responseWrapper.ErrorID.contains('INVALID-PROVIDER-ID-<ProviderID>')){
                			clog.EPIC_Response_Message__c = 'Epic provider ID is not found';
                		}else if(responseWrapper.ErrorID.contains('INVALID-CONTACT-RELATION-ID-<ContactRelation>')){
                			clog.EPIC_Response_Message__c = 'Epic relationship category list ID is invalid';
                		}else if(responseWrapper.ErrorID.contains('INVALID-CONTACT-PHONE-TYPE-ID-<ContactPhoneType>')){
                			clog.EPIC_Response_Message__c = 'Epic phone type cateogry list ID is invalid';
                		}else if(responseWrapper.ErrorID.contains('MISSING-CONTACT-PHONE')){
                			clog.EPIC_Response_Message__c = 'Missing phone number dialed';
                		}else if(responseWrapper.ErrorID.contains('INVALID-CONTACT-OUTCOME-ID-<ContactOutcome>')){
                			clog.EPIC_Response_Message__c = 'Epic contact outcome category list ID is invalid';
                		}else if(responseWrapper.ErrorID.contains('INVALID-REASON-FOR-VISIT-ID-<ReasonForVisit>')){
                			clog.EPIC_Response_Message__c = 'Epic reason for visit category list ID is invalid. This should never occur since you will be always sending 201.';
                		}else if(responseWrapper.ErrorID.contains('ENCOUNTER-NOT-FOUND')){
                			clog.EPIC_Response_Message__c = 'Check after shell encounter is created. This should not occur, but in case it can\'t find the shell encounter it just created.';
                		}else if(responseWrapper.ErrorID.contains('FAILED-TO-CREATE-CONTACT-RECORD')){
                			clog.EPIC_Response_Message__c = 'Error occurred while creating the person contacted record';
                		}else if(responseWrapper.ErrorID.contains('ERROR-OCCURRED-CREATING-REASON-FOR-VISIT')){
                			clog.EPIC_Response_Message__c = 'Error occurred while creating the reason for visit';
                		}else if(responseWrapper.ErrorID.contains('ERROR-OCCURRED-SAVING-NOTE')){
                			clog.EPIC_Response_Message__c = 'Error occurred saving the telephone note.';
                		}else if(responseWrapper.ErrorID.contains('ERROR-CLOSING-TELEPHONE-ENCOUNTER')){
                			clog.EPIC_Response_Message__c = 'Error occurred when closing the telephone encounter';
                		}else if(responseWrapper.ErrorID.contains('ENCOUNTER-DATE-MUST-BE-LESS-THAN-30-DAYS-OLD')){
                			clog.EPIC_Response_Message__c = 'Checking Encounter Date is valid';
                		}else if(responseWrapper.ErrorID.contains('ENCOUNTER-DATE-CANNOT-BE-IN-THE-FUTURE')){
                			clog.EPIC_Response_Message__c = 'Checking Encounter Date is valid';
                		}else {
                			clog.EPIC_Response_Message__c = responseWrapper.ErrorMessage;
                		}
		        		clog.EPIC_Reference__c = '';
		        		clog.EPIC_Sync_Date__c = system.today();
                	}
                	update commLogList;
            }
        }else{ // Log exception if Service is unavailable
        	for(Communication_Log__c cl: commLogList){
        		cl.EPIC_Error_Id__c = response.getStatusCode()+' Service Unavailable';
        		cl.EPIC_Reference__c = '';
        		cl.EPIC_Response_Message__c = response.getBody();  
        		cl.EPIC_Sync_Date__c = system.today();
        	}
        	update lstCommLog;
        }
        
    }
    
        
    public class communicationLogWrapper
    {
        public String UserID;
        public String PatientID;
        public String PatientSHMRN;
        public String EncounterDept;
        public String EncounterProviderID;
        public String ContactName;
        public String ContactRelation;
        public String ContactPhone;
        public String ContactPhoneType;
        public String ContactComment;
        public String ContactOutcome;
        public String NoteFormat;
        public String NoteText;
        public String ReasonForVisit;
        public String EncounterDate;
        public communicationLogWrapper(String cUserID, String cPatientID, String cPatientSHMRN, String cEncounterDept, String cEncounterProviderID, String cContactName, String cContactRelation, String cContactPhone, String cContactPhoneType, String cContactComment, String cContactOutcome, String cNoteFormat, String cNoteText, String cReasonForVisit, String cEncounterDate)
        {
            UserID = cUserID; 
            PatientID = cPatientID;
            PatientSHMRN =  cPatientSHMRN; 
            EncounterDept = cEncounterDept;
            EncounterProviderID = cEncounterProviderID;
            ContactName = cContactName;
            ContactRelation = cContactRelation;
            ContactPhone = cContactPhone;
            ContactPhoneType = cContactPhoneType;
            ContactComment = cContactComment;
            ContactOutcome = cContactOutcome;
            NoteFormat = cNoteFormat;
            NoteText = cNoteText;
            ReasonForVisit = cReasonForVisit;
            EncounterDate = cEncounterDate;   
        }
        
    }
    
    public class epicResponseWrapper
    {
        public String EpicReferenceID;
        public String ErrorID;
        public string ErrorMessage;
        public Boolean Success;
    }
}