Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Admin_Approval_Status_Received_On__c</fullName>
        <description>Used to capture the approval status replied date.</description>
        <label>Admin Approval Status Received On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Admin_Assistant_Approval_Status__c</fullName>
        <description>used to track provider admin assistant approval</description>
        <label>Admin Assistant Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Admin_Assistant_Email__c</fullName>
        <label>Delegate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Admin_Assistant__c</fullName>
        <label>Delegate Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Success_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tech Success Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/PDIAdminAssistantApprovalKeywords__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>used to check the approval key words in the provider replied email.</description>
    <label>PDIAdminAssistantApprovalKeywords</label>
</CustomObject>

Sutter Health/src/objects/SystemException__c.object
<CustomObject>
    <description>This object is used to store exceptions in custom development components for reporting.</description>
    <fields>
        <fullName>ExceptionMessage__c</fullName>
        <description>This is where the exception information is logged.</description>
        <label>ExceptionMessage</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>System Exception</label>
    <nameField>
        <displayFormat>Ex-{0000000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/PDIEmailHandlerProviderAssistantApproval.cls
/**  
*    Class Name: PDIEmailHandlerProviderAssistantApproval 
*    Date: 15-11-2016
*    Created By: IDC Offshore		
*    Description: Used to capture provider admin aasistant approval status reply from incoming email.
**/
global class PDIEmailHandlerProviderAssistantApproval implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        SystemException__c systemException = new SystemException__c();
        try{
            String strSubject = email.Subject;
            strSubject = strSubject.trim();
            String summaryId = strSubject.subString(strSubject.length()-18, strSubject.length());
            String strBody = email.plainTextBody;
            List<String> parts = strBody.split('\n');
            String strBodyLine1 =  parts[0];
            String approvedStatus;
            Contact_Validation_Summary__c providerToUpdate = new Contact_Validation_Summary__c();
            //querying to get the provider summary info to update the approval status
            providerToUpdate = [SELECT Id,Name, Admin_Assistant__c, Admin_Assistant_Email__c, 
                                Admin_Assistant_Approval_Status__c FROM Contact_Validation_Summary__c  WHERE Id = :summaryId];
            List<PDIAdminAssistantApprovalKeywords__c> keyWords = PDIAdminAssistantApprovalKeywords__c.getall().values();
            for(PDIAdminAssistantApprovalKeywords__c appStatus: keyWords){
                if(strBodyLine1.toUpperCase().trim().contains(appStatus.Name)){
                    approvedStatus = Label.CL580_PDIEmailApprovedText;
                }
            }
            if(String.isNotBlank(approvedStatus) && approvedStatus == Label.CL580_PDIEmailApprovedText){
                approvedStatus = Label.CL580_PDIEmailApprovedText;
                providerToUpdate.Admin_Assistant_Approval_Status__c = approvedStatus;
            }
            else{
                approvedStatus = Label.CL581_PDIEmailRejectedText;
                providerToUpdate.Admin_Assistant_Approval_Status__c = approvedStatus;
            }
            if(providerToUpdate != null){
                providerToUpdate.Admin_Approval_Status_Received_On__c = System.now();
                providerToUpdate.Tech_Success_Email__c = false;
                update providerToUpdate;
                String headerBody = Label.CL582_PDIEmailFromText + email.fromAddress +'\n'
                    + Label.CL583_PDIEmailApprovalSubject + email.Subject +'\n'
                    + Label.CL584_PDIEmailApprovalReceivedOn +  System.now().format() +'';
                Attachment attachment = new Attachment();
                attachment.Name = Label.CL585_PDIEmailApprovalStatusText +approvedStatus + ' (' + System.now().format() + ').PDF';
                attachment.Body = Blob.toPDF(email.HtmlBody);
                attachment.ParentId = summaryId;
                attachment.Description = headerBody;
                insert attachment;
            }
            return null;
        } 
        catch(Exception ex) {
            systemException.ExceptionMessage__c = ex.getMessage() + Label.CL218_rSlashN + ex.getStackTraceString() + Label.CL218_rSlashN + ex.getTypeName() + Label.CL218_rSlashN + System.now(); insert systemException; return null;
        }
    }
}