Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Assigned_Date__c</fullName>
        <label>Assigned Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <description>Used to capture provider validation closed date based on case.</description>
        <label>Closed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PDI_Campaign__c</fullName>
        <description>Used to indicate Campaign flag</description>
        <label>PDI Campaign</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Active_Status__c</fullName>
        <formula>Contact_Id__r.Provider_Active_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_FirstName__c</fullName>
        <formula>Contact_Id__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider FirstName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_LastName__c</fullName>
        <formula>Contact_Id__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider LastName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_NPI_F__c</fullName>
        <formula>Contact_Id__r.Provider_NPI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider NPI</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retired_Departed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Provider Service Status</description>
        <label>Retired / Departed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status field created as part of REQ 3611 PDV Call Center</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Validated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Validation-Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tech_Last_Verified_Date__c</fullName>
        <formula>IF( AND(NOT(ISBLANK( Last_Verified_Date__c )), (Last_Verified_Date__c  &gt;  ProviderInfoHistory__r.Last_Verified_Date__c)) , Last_Verified_Date__c  , ProviderInfoHistory__r.Last_Verified_Date__c)</formula>
        <label>Last Verified Date</label>
        <type>DateTime</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/PDIAutoAssignSelectedCriteria__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to store the selected criteria for auto assigning the records to agents</description>
    <fields>
        <fullName>Assign_Based_On__c</fullName>
        <description>Used to Store Filter criteria field</description>
        <label>Assign Based On</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Count_Per_Agent__c</fullName>
        <description>Used to store the Record Count selected on auto assign page.</description>
        <label>Record Count Per Agent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sorting_Order__c</fullName>
        <description>Used to store sorting order</description>
        <label>Sorting Order</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>PDI Auto Assign Selected Criteria</label>
</CustomObject>

Sutter Health/src/objects/SystemException__c.object
<CustomObject>
    <description>This object is used to store exceptions in custom development components for reporting.</description>
    <fields>
        <fullName>ExceptionMessage__c</fullName>
        <description>This is where the exception information is logged.</description>
        <label>ExceptionMessage</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>System Exception</label>
    <nameField>
        <displayFormat>Ex-{0000000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/BatchAutoAssignRecordsToAgents.cls
/*****************************************************
Class Name: BatchAutoAssignRecordsToAgents 
Created By: Nagarjuna Kaipu
Created Date: 13/04/2016
Description: This batch class is used to auto assign the non validated records to agents based selected criteria
*****************************************************/
global class BatchAutoAssignRecordsToAgents implements Database.Batchable<sObject>, Database.Stateful {
    private Map<Id, User> selectedUsers = new Map<Id, User>();
    private Integer recordCount ;
    private String selectedAssignBasedOn;
    private String selectedSortingOrder;
    /* Name: Start
*Input: Batchable Context
* Return Type: Database.QueryLocator
* Description: Used to get the list if records to pass to execute method
*/
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        //Gettting selected criteria field values from custom settings
        PDIAutoAssignSelectedCriteria__c selectedCriteria = 
            PDIAutoAssignSelectedCriteria__c.getInstance(Label.CL201_AutoAssignSelectedCriteria);
        
        recordCount = Integer.valueOf(selectedCriteria.Record_Count_Per_Agent__c);
        selectedAssignBasedOn = selectedCriteria.Assign_Based_On__c;
        selectedSortingOrder = selectedCriteria.Sorting_Order__c;
        //Querying the Non Validated Providers queue id from the queue object
        Group que = [Select Id, name from group where type = 'queue' 
                     and Name =: Label.CL211_PDIQueue Limit 1];
        //Querying Non-Validated records to assign to the agents
        String query = 'SELECT Id, Owner.Id, Name, Assigned_Date__c, Closed_Date__c, PDI_Campaign__C, Retired_Departed__c, Provider_Active_Status__c, ' 
            +'Status__c, Provider_FirstName__c, Provider_LastName__c, Provider_NPI_F__c, Tech_Last_Verified_Date__c FROM Contact_Validation_Summary__c'
            +' WHERE OwnerId = \''+que.Id+'\' AND  PDI_Campaign__C = \''
            +Label.CL176_PDI_Current_Campaign_Name+'\' AND'
            +' Retired_Departed__c != true AND Provider_Active_Status__c = true AND '
            +' Status__c = \''+Label.CL185_PDI_Non_Validated_Status+'\' ORDER BY '
            +selectedAssignBasedOn +' '
            +selectedSortingOrder+' NULLS LAST';
        return Database.getQueryLocator(query);
    }
    /* Name: Execute
*Input: List of Summary records
* Return Type: void
* Description:Used to auto assign the non validated provider records to agents based on the selected criteria
*/
    global void execute(Database.BatchableContext BC, List<Contact_Validation_Summary__c> nonValidatedRecList)
    {
        AutoAssignRecordsToAgentsController autoAssign = new AutoAssignRecordsToAgentsController();
        autoAssign.AssignToAgents(recordCount, nonValidatedRecList);
    }
    /* Name: finish
*Input: Batchable Context
* Return Type: void
* Description: Used to send email notification
*/
    global void finish(Database.BatchableContext BC)
    {
        SystemException__c systemException = new SystemException__c();
        try
        {
            // Get the AsyncApexJob that represents the Batch job using the Id from the BatchableContext 
            AsyncApexJob asynchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
                                      TotalJobItems, CreatedBy.Email, ExtendedStatus, CompletedDate
                                      from AsyncApexJob where Id = :bc.getJobId() LIMIT 1];        
            
            //below code will send an email to Administrator about the status
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            //Getting Orgwide email address
            OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = :Label.CL204_ProviderOrgWideEmail LIMIT 1];
            if ( owea.size() > 0 ) {
                mail.setOrgWideEmailAddressId(owea.get(0).Id);
            }   
            // Email the Batch Job's submitter that the Job is finished.
            String[] toAddresses = new String[] {asynchJob.CreatedBy.Email};
                mail.setToAddresses(toAddresses);
            mail.setSubject(Label.CL202_AutoAssignSubject + asynchJob.Status);
            mail.setPlainTextBody(Label.CL203_AutoAssignBody +asynchJob.CompletedDate);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(Exception ex) {
            systemException.ExceptionMessage__c = ex.getMessage() + Label.CL218_rSlashN + ex.getStackTraceString() + Label.CL218_rSlashN + ex.getTypeName() + Label.CL218_rSlashN + System.now(); insert systemException;
        }
    }
}