Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PDI_Campaign__c</fullName>
        <description>Used to indicate Campaign flag</description>
        <label>PDI Campaign</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practicing_Physician__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Provider Service Status</description>
        <label>Practicing Physician</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resigned_From_Sutter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive Provider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retired_Departed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Provider Service Status</description>
        <label>Retired / Departed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tech_Is_Campaign_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for campaign reprocess filter in provider campaign initiation batch.</description>
        <label>Is Campaign Done</label>
        <type>Checkbox</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/CS_ManageProfile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting containing Profile Names</description>
    <label>CS_ManageProfile</label>
</CustomObject>

Sutter Health/src/classes/PDICampaignInitiationHelper_Test.cls
@isTest
public class PDICampaignInitiationHelper_Test {
    static TestMethod void testCreateNewCampaignProviderRecords()
    {
        User testUser = Util01_PDIUtilTestData.PDITestUser();
        System.runAs(testUser)
        {
            List<CS_ManageProfile__c> mgrProfile = new List<CS_ManageProfile__c>();
            mgrProfile = Util01_PDIUtilTestData.createManageprofileSet();
            insert  mgrProfile;
            List<Contact> contactLst =  Util01_PDIUtilTestData.createContacts();
            insert contactLst;
            Map<Id, Contact> contactMap = new Map<Id, Contact>();
            for(Contact c: contactLst)
            {
                contactMap.put(c.Id, c);
            }
            List<Contact_Validation_Summary__c> sumList = [Select id, Contact_Id__r.Id From Contact_Validation_Summary__c Where Contact_Id__r.Id IN: contactMap.keySet() LIMIT 3];
            delete sumList;
            Contact_Validation_Summary__c summaryRecord = new Contact_Validation_Summary__c(
                    Provider_Name__c = 'NagaTest', Email__c = 'NagaTest111@test.com', Address_Type__c = 'Primary', Contact_Id__c = contactLst[0].Id,
                    Practicing_Physician__c = true, Resigned_From_Sutter__c = false, Retired_Departed__c = false, 
                    PDI_Campaign__c = '2015 Phase', Tech_Is_Campaign_Done__c = false);
            insert summaryRecord;
            Test.startTest();
            PDICampaignInitiationHelper.CreateNewCampaignProviderRecords(contactMap);
            Test.stopTest();
        }
        List<Contact_Validation_Summary__c> updatedList = [SELECT PDI_Campaign__c FROM Contact_Validation_Summary__c 
                                                           WHERE PDI_Campaign__c =: Label.CL176_PDI_Current_Campaign_Name];
        System.assertNotEquals(0, updatedList.size());
    }
    
}