Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_External_ID1__c</fullName>
        <description>External ID used to match a contact record to its equivalent record in a source system when updating and/or inserting.</description>
        <externalId>true</externalId>
        <label>Contact External ID 1</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Employee_ADID__c</fullName>
        <label>Employee ADID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Portal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Address__c</fullName>
        <label>Provider Correspondence Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_City__c</fullName>
        <label>Provider Correspondence City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Fax_Number__c</fullName>
        <label>Provider Correspondence Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_PostalCode__c</fullName>
        <label>Provider Correspondence PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_State__c</fullName>
        <label>Provider Correspondence State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Title__c</fullName>
        <label>Provider Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_of_E_mail__c</fullName>
        <label>Source of E-mail</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>PCRM Field -  Contains provider userame</description>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Title__c</fullName>
        <label>Provider Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Failed_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <label>Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_Successfully__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed Successfully</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Failed Contact</label>
    <nameField>
        <displayFormat>FCN-{0000}</displayFormat>
        <label>Failed Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failed Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Employee_ADID__c</fullName>
        <formula>Contact.Employee_ADID__c</formula>
        <label>Employee ADID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Address__c</fullName>
        <label>Provider Correspondence Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_City__c</fullName>
        <label>Provider Correspondence City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Phone__c</fullName>
        <description>Provider Correspondence Phone</description>
        <label>Provider Correspondence Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_PostalCode__c</fullName>
        <label>Provider Correspondence PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_State__c</fullName>
        <label>Provider Correspondence State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sutter Health/src/classes/HandleFailedContacts.cls
public with sharing class HandleFailedContacts {
    private list<failed_contacts__c> fcList = new list<failed_contacts__c>();
    private list<Id> contactIdList;
    private failed_contacts__c fcObj;
    
    public HandleFailedContacts() {
        fcList = new list<failed_contacts__c>();
        contactIdList = new list<Id>();
    }
    
    public void addToFailList(User p_userObj,Database.SaveResult  p_sr) {
        contactIdList.add(p_userObj.contactId);
        
        fcObj = new failed_contacts__c();
        fcObj.contact_id__c = String.valueOf(p_userObj.contactId);
        fcObj.first_name__c = p_userObj.firstName;
        fcObj.last_name__c = p_userObj.lastName;
        fcObj.username__c = p_userObj.username;
        fcObj.nickname__c = p_userObj.CommunityNickname;
        
        for(Database.Error err : p_sr.getErrors()) {
            fcObj.error_message__c = err.getMessage();
            fcObj.error_code__c = String.valueOf(err.getStatusCode());
        }
        
        fcList.add(fcObj);
    }
    

    
    public void insertFailList() {
        
        if(fcList.size() > 0)   insert fcList;
       
        
        /** REQ 3399 - Condition added in the query to skip for TeleForm Contacts **/
        //PDI - Wave1
        list<Contact_Validation_Summary__c> cvsList = [SELECT id FROM Contact_Validation_Summary__c WHERE Contact_Id__c IN :contactIdList 
                                                       And ((NOT Contact_Id__r.Source_of_E_Mail__c LIKE '%TLFM%')
                                                       And (Contact_Id__r.Employee_ADID__c = null))];
        
        /*@PDI-Wave1 Description: Commented below delete code as part of PDI-Wave1*/
        //if(cvsList.size() > 0)  delete cvsList; 
    }
    
    
    public void removeFromFailList(set<Id> p_contactIdSet) {
        list<failed_contacts__c> fcList = [SELECT id FROM failed_contacts__c WHERE contact_id__c IN :p_contactIdSet];
        

            for(failed_contacts__c temp : fcList)   temp.processed_successfully__c = true;
            if(fcList.size() > 0) update fcList;
    }
    
    
    
    
    public static void processAgain() {
        list<contact> conList = new list<contact>();
        list<Id> conIdList = new list<Id>();
        list<failed_contacts__c> fcList = [SELECT id, contact_id__c FROM failed_contacts__c limit 50000];
        Integer i = 1;
        
            
        for(failed_contacts__c temp : fcList)   conIdList.add(temp.contact_id__c);
            
        conList = [SELECT Id,Email,Provider_Name__c,FirstName,LastName,Provider_Title__c,MobilePhone,Provider_Correspondence_Address__c
                    ,Provider_Correspondence_City__c,Provider_Correspondence_State__c,Provider_Correspondence_PostalCode__c,Employee_ADID__c
                    ,Provider_Correspondence_Phone__c,Provider_Correspondence_Fax_Number__c,Contact_External_ID1__c,Contact.RecordType.Name 
                    FROM Contact WHERE id IN :conIdList AND Is_Portal_User__c = false];
                    
                    
        ManageCommunityUsers.CreateProviderUsers(conList);
            
        i = i + 1;
    }
}