Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <label>Member ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PCP_Effective_Date__c</fullName>
        <label>PCP Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PCP_Practitioner_Name__c</fullName>
        <label>PCP Practitioner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Used for member contact records.</description>
        <label>Member</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/PCP_Information__c.object
<CustomObject>
    <description>PCP Information stored for Member (Contact)</description>
    <fields>
        <fullName>Medical_Group_Affiliation__c</fullName>
        <label>Medical Group Affiliation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PCP Informations</relationshipLabel>
        <relationshipName>PCP_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PCP_Effective_date__c</fullName>
        <label>PCP Effective date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PCP_Member_HR_ID__c</fullName>
        <label>PCP Member HR ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Practitioner_First_Name__c</fullName>
        <label>PCP Practitioner First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Practitioner_HR_ID__c</fullName>
        <label>PCP Practitioner HR ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Practitioner_Last_Name__c</fullName>
        <label>PCP Practitioner Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Practitioner_Middle_Name__c</fullName>
        <label>PCP Practitioner Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Practitioner_Name__c</fullName>
        <label>PCP Practitioner Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Speciality__c</fullName>
        <label>PCP Speciality</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Specialty_HCC_ID__c</fullName>
        <label>PCP Specialty HCC ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Specialty_HR_ID__c</fullName>
        <label>PCP Specialty HR ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Specialty_Sub_HCC_ID__c</fullName>
        <label>PCP Specialty-Sub HCC ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Specialty_Sub_HR_ID__c</fullName>
        <label>PCP Specialty-Sub HR ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Supplier_Location_HR_ID__c</fullName>
        <label>PCP Supplier Location HR ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Supplier_Location_name__c</fullName>
        <label>PCP Supplier Location name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Supplier_NPI__c</fullName>
        <label>PCP Supplier NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Supplier_Name__c</fullName>
        <label>PCP Supplier Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Termination_Date__c</fullName>
        <label>PCP Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PCP_sub_Specialty__c</fullName>
        <label>PCP sub-Specialty</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPS_Epic_ID__c</fullName>
        <label>SPS Epic ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PCP Information</label>
    <nameField>
        <label>PCP Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PCP Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Potential_Quality_Issue__c.object
<CustomObject>
    <description>Req-3369</description>
    <fields>
        <fullName>Access_Availability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Access / Availability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assigned_RN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned RN</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Potential_Quality_Issue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ByPass_CMO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Bypasses CMO Approval</description>
        <label>Bypass CMO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comment_CMO__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_PRC__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_of_Events1__c</fullName>
        <label>Description of Events</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Medical_Director_Recommendations_Other__c</fullName>
        <label>Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Director_Recommendations__c</fullName>
        <label>Medical Director Recommendations</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Close – No issues identified</fullName>
                </value>
                <value>
                    <fullName>Close – Track and Trend</fullName>
                </value>
                <value>
                    <fullName>Credentialing Review Requested</fullName>
                </value>
                <value>
                    <fullName>Education Letter</fullName>
                </value>
                <value>
                    <fullName>Peer Review Requested</fullName>
                </value>
                <value>
                    <fullName>Reff to Foundation&apos;s Quality Committee</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_Director_Review_Summary1__c</fullName>
        <label>Medical Director Review Summary</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Member_DOB__c</fullName>
        <label>Member DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Potential Quality Issue (Member ID)</relationshipLabel>
        <relationshipName>Potential_Quality_Issue1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Medical_Group_Affiliation__c</fullName>
        <label>Member Medical Group Affiliation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <label>Member ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_CheckBox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PCP_Practioner_Name__c</fullName>
        <label>PCP Practioner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PQI_Referral_Date__c</fullName>
        <label>PQI Referral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PQI_Referred_By__c</fullName>
        <label>PQI Referred By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PQI_Required_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PQI Required Field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PQI_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>UM Review</fullName>
                </value>
                <value>
                    <fullName>MD Review</fullName>
                </value>
                <value>
                    <fullName>PRC Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>UM Rejected</fullName>
                </value>
                <value>
                    <fullName>MD Approved</fullName>
                </value>
                <value>
                    <fullName>MD Rejected</fullName>
                </value>
                <value>
                    <fullName>PRC Approved</fullName>
                </value>
                <value>
                    <fullName>PRC</fullName>
                </value>
                <value>
                    <fullName>UM Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PQI_indicator_Other__c</fullName>
        <label>Other</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Peer_Review_Credentialing_Outcome__c</fullName>
        <label>Peer  Review / Credentialing Outcome</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>805</fullName>
                </value>
                <value>
                    <fullName>Close – No Issues Identified</fullName>
                </value>
                <value>
                    <fullName>Close – Track and Trend</fullName>
                </value>
                <value>
                    <fullName>Credentialing Review Requested</fullName>
                </value>
                <value>
                    <fullName>Education Letter</fullName>
                </value>
                <value>
                    <fullName>Medical Board Referral</fullName>
                </value>
                <value>
                    <fullName>Peer Review Requested</fullName>
                </value>
                <value>
                    <fullName>Reff to Foundation&apos;s Quality Committee</fullName>
                </value>
                <value>
                    <fullName>Site Visit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Peer_Review_Other__c</fullName>
        <label>Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RN_Case_Review_Summary1__c</fullName>
        <label>RN Clinical Summary</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RN_Justification_of_Recommendation__c</fullName>
        <label>Justification of Recommendation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RN_Pertinent_criteria_guidelines_standa__c</fullName>
        <label>Pertinent criteria/guidelines/standards</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RN_Timeline_of_Key_Events__c</fullName>
        <label>Timeline of Key Events</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reason_for_Referral__c</fullName>
        <label>Reason for Referral</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Setting_other__c</fullName>
        <label>Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Settings__c</fullName>
        <label>Settings</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inpatient</fullName>
                </value>
                <value>
                    <fullName>Outpatient</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Laboratory</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Potential Quality Issue</label>
    <nameField>
        <displayFormat>PQI-{0000000000}</displayFormat>
        <label>PQI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Quality Issue</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sutter Health/src/classes/VFC41_Potential_Quality_Issue_test.cls
/**********************************************************************
 Name: VFC41_Potential_Quality_Issue_test
 Copyright © 2015 IDC Offshore
 ======================================================
 ======================================================
 Purpose:
 This is the test class for VFC05_Claim_Detail class
 ======================================================
 ======================================================
 History
 -------
 VERSION  AUTHOR        DATE        DETAIL                 Description
 1.0      IDC Offshore  14-Aug-2015 Development complete   Test Class for VFC41_Potential_Quality_Issue  and PQIUpdateQueue. This class tests for different scenarios that are handled in the code.
 2.0      IDC Offshore  14-Dec-2015  Class Optimization   Incorporated changes to implement best test practices in the test class.
 ***********************************************************************/
@isTest
private class VFC41_Potential_Quality_Issue_test {
        

    /*******************************************************************
    Purpose: This method is used to Test submit approval process from from vf page and When a user clicks on the Save button on Cutomer all value will get save in PQI object.
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/  
    static testMethod void CompletedAndSave_Test() {
        //Create test User
        user us=AP01_TestDataUtility.createUserPQI();
        /*********************************************************************** 
        Verifying the User has been created successfully
        Expected Result: user id is not null
        Actual Result: user id  is not null 
        ***********************************************************************/ 
        system.assert(us.id!=null);
        
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C ='Closed',
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/
        system.assert(newPotentialQualityIssue.id!=null);
        
        system.debug('!!!!newPotentialQualityIssue' +newPotentialQualityIssue);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.Completed();
        potentialQualityIssue.sendPRC();
        potentialQualityIssue.approveRecord();
        potentialQualityIssue.rejectRecord();
        potentialQualityIssue.autoPopulateMember();
        potentialQualityIssue.closeRecord();
        potentialQualityIssue.save();
        test.stopTest();
        list <Potential_Quality_Issue__c>  pqi = [SELECT Peer_Review_Credentialing_Outcome__c
                                                  FROM Potential_Quality_Issue__c
                                                  WHERE Id =:newPotentialQualityIssue.id ];
        
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c record list size
        Expected Result: Potential_Quality_Issue__c record list size should be 1
        Actual Result: Potential_Quality_Issue__c record list size should be 1 
        ***********************************************************************/ 
        system.assertEquals(pqi.size(),1 );
        
    }        
     /*******************************************************************
    Purpose: This method is used to Negative Testing submit approval process from from vf page and When a user clicks on the Save button on Cutomer all value will get save in PQI object.
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/  
    static testMethod void CompletedAndSave_NegativeTest() {
        
        user us=AP01_TestDataUtility.createUser();
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C ='PRC',
                                                                                                Comment_PRC__c ='Rejected',
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                                
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);
        
        system.debug('!!!!newPotentialQualityIssue' +newPotentialQualityIssue);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.showBlankVlaue = '';
        potentialQualityIssue.PQITrainingDocument = new SHP_Training_Document__kav();
        potentialQualityIssue.Completed();
        potentialQualityIssue.sendPRC();
        potentialQualityIssue.approveRecord();
        potentialQualityIssue.rejectRecord();
        potentialQualityIssue.autoPopulateMember();
        potentialQualityIssue.closeRecord();
        potentialQualityIssue.save();
        test.stopTest();
        
        
    }

    /*******************************************************************
    Purpose: This method is used to test submit approval process from from vf page  and send to PRC.
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/ 
    static testMethod void sendPRC_Test() {
        
        user us=AP01_TestDataUtility.createUser();  
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQINegative(assignedAccount);
        //create test Contact data for PCP Information custom console.
            PCP_Information__c pcp = new   PCP_Information__c ();
            pcp.Medical_Group_Affiliation__c = AP01_TestDataTokens.CONTACT_F_NAME ;
            pcp.Member_ID__c = ContactToInsert[0].id;
            pcp.PCP_Effective_date__c = system.today();
            pcp.PCP_Member_HR_ID__c = AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Practitioner_First_Name__c=AP01_TestDataTokens.EMPLOYEE_AFFILIATE_FACILITY ;
            pcp.PCP_Practitioner_HR_ID__c = AP01_TestDataTokens.MEMBER_ID_FIELD  ;
            pcp.PCP_Practitioner_Last_Name__c = AP01_TestDataTokens.MEMBER_HCC_ID ;
            pcp.PCP_Practitioner_Middle_Name__c = AP01_TestDataTokens.SUPPLIER_Tax_ID;
            pcp.PCP_Practitioner_Name__c = AP01_TestDataTokens.SUPPLIER_NPI;
            pcp.PCP_Speciality__c = AP01_TestDataTokens.VENDOR_ID;
            pcp.PCP_Specialty_HCC_ID__c= AP01_TestDataTokens.VENDOR_TaxID;
            pcp.PCP_Specialty_HR_ID__c= AP01_TestDataTokens.CONT_EMPLOYEE_ID ;
            pcp.PCP_Specialty_Sub_HCC_ID__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Specialty_Sub_HR_ID__c =AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_sub_Specialty__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_Location_HR_ID__c =AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_Location_name__c =AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_Name__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_NPI__c = AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Termination_Date__c=system.today();
            pcp.SPS_Epic_ID__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            insert pcp;
         
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (
                                                                                                Description_of_Events1__c ='<a href',
                                                                                                Medical_Director_Recommendations__c ='Other',
                                                                                                Medical_Director_Review_Summary1__c ='<a href',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = null,
                                                                                                Member_Medical_Group_Affiliation__c =null,
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='other',
                                                                                                PQI_Status__C ='New',
                                                                                                PQI_Referral_Date__c = null,
                                                                                                PQI_Referred_By__c =null,
                                                                                                Assigned_RN__c =null,
                                                                                                Reason_for_Referral__c =null,
                                                                                                RN_Timeline_of_Key_Events__c ='<a href',
                                                                                                RN_Case_Review_Summary1__c ='<a href',
                                                                                                RN_Justification_of_Recommendation__C ='<a href',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='<a href',
                                                                                                Peer_Review_Credentialing_Outcome__c ='Other',
                                                                                                Peer_Review_Other__c = null,
                                                                                                Medical_Director_Recommendations_Other__c =  null,
                                                                                                Setting_other__c = null,
                                                                                                Other_CheckBox__c = true,
                                                                                                PQI_indicator_Other__c = null,
                                                                                                PQI_Required_Field__C =false                                                                                                                                                                                              
                                                                                            );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);

        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);   
        potentialQualityIssue.autoPopulateMember();
        potentialQualityIssue.Completed();
        potentialQualityIssue.sendPRC();
        potentialQualityIssue.approveRecord();
        potentialQualityIssue.rejectRecord();
        potentialQualityIssue.autoPopulateMember();
        potentialQualityIssue.closeRecord();
        potentialQualityIssue.save();
        potentialQualityIssue.OtherValue();
        potentialQualityIssue.OtherValuePqiIndicator();
        potentialQualityIssue.isOtherMedical();
        test.stopTest();
    }
    /*******************************************************************
    Purpose: This method is used to testing populate member from contact object and PCP object.
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/ 
    static testMethod void autoPopulateMember_Test() {
        
        user us=AP01_TestDataUtility.createUser();  
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQINegative(assignedAccount);
        //create test Contact data for PCP Information custom console.
            PCP_Information__c pcp = new   PCP_Information__c ();
            pcp.Medical_Group_Affiliation__c = AP01_TestDataTokens.CONTACT_F_NAME ;
            pcp.Member_ID__c = ContactToInsert[0].id;
            datetime todayTimeAndDate = System.today(); 
            date CurrentDate = Date.newInstance(todayTimeAndDate.year(),todayTimeAndDate.month(),todayTimeAndDate.day());
            pcp.PCP_Effective_date__c = CurrentDate;
            pcp.PCP_Member_HR_ID__c = AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Practitioner_First_Name__c=AP01_TestDataTokens.EMPLOYEE_AFFILIATE_FACILITY ;
            pcp.PCP_Practitioner_HR_ID__c = AP01_TestDataTokens.MEMBER_ID_FIELD  ;
            pcp.PCP_Practitioner_Last_Name__c = AP01_TestDataTokens.MEMBER_HCC_ID ;
            pcp.PCP_Practitioner_Middle_Name__c = AP01_TestDataTokens.SUPPLIER_Tax_ID;
            pcp.PCP_Practitioner_Name__c = AP01_TestDataTokens.SUPPLIER_NPI;
            pcp.PCP_Speciality__c = AP01_TestDataTokens.VENDOR_ID;
            pcp.PCP_Specialty_HCC_ID__c= AP01_TestDataTokens.VENDOR_TaxID;
            pcp.PCP_Specialty_HR_ID__c= AP01_TestDataTokens.CONT_EMPLOYEE_ID ;
            pcp.PCP_Specialty_Sub_HCC_ID__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Specialty_Sub_HR_ID__c =AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_sub_Specialty__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_Location_HR_ID__c =AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_Location_name__c =AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_Name__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Supplier_NPI__c = AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            pcp.PCP_Termination_Date__c=CurrentDate;
            pcp.SPS_Epic_ID__c=AP01_TestDataTokens.CONT_EMPLOYEE_ID;
            insert pcp;
         
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (
                                                                                                Description_of_Events1__c ='<a href',
                                                                                                Medical_Director_Recommendations__c ='Other',
                                                                                                Medical_Director_Review_Summary1__c ='<a href',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = null,
                                                                                                Member_Medical_Group_Affiliation__c =null,
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='other',
                                                                                                PQI_Status__C ='New',
                                                                                                PQI_Referral_Date__c = null,
                                                                                                PQI_Referred_By__c =null,
                                                                                                Assigned_RN__c =null,
                                                                                                Reason_for_Referral__c =null,
                                                                                                RN_Timeline_of_Key_Events__c ='<a href',
                                                                                                RN_Case_Review_Summary1__c ='<a href',
                                                                                                RN_Justification_of_Recommendation__C ='<a href',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='<a href',
                                                                                                Peer_Review_Credentialing_Outcome__c ='Other',
                                                                                                Peer_Review_Other__c = null,
                                                                                                Medical_Director_Recommendations_Other__c =  null,
                                                                                                Setting_other__c = null,
                                                                                                Other_CheckBox__c = true,
                                                                                                PQI_indicator_Other__c = null,
                                                                                                PQI_Required_Field__C =false                                                                                                                                                                                              
                                                                                            );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);

        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);   
        potentialQualityIssue.autoPopulateMember();
        test.stopTest();
    }
    
    /*******************************************************************
    Purpose: This method is use to testing  for the validation in mandatory fields.
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/ 
    static testMethod void PQIRequired_Test() {
        
        user us=AP01_TestDataUtility.createUser();  
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQINegative(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (
                                                                                                Description_of_Events1__c ='<a href',
                                                                                                Medical_Director_Recommendations__c ='Other',
                                                                                                Medical_Director_Review_Summary1__c ='<a href',                                                                                      
                                                                                                Member_Name__c = null,
                                                                                                Member_Medical_Group_Affiliation__c =null,
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='other',
                                                                                                PQI_Status__C ='New',
                                                                                                PQI_Referral_Date__c = null,
                                                                                                PQI_Referred_By__c =null,
                                                                                                Assigned_RN__c =null,
                                                                                                Reason_for_Referral__c =null,
                                                                                                RN_Timeline_of_Key_Events__c ='<a href',
                                                                                                RN_Case_Review_Summary1__c ='<a href',
                                                                                                RN_Justification_of_Recommendation__C ='<a href',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='<a href',
                                                                                                Peer_Review_Credentialing_Outcome__c ='Other',
                                                                                                Peer_Review_Other__c = null,
                                                                                                Medical_Director_Recommendations_Other__c =  null,
                                                                                                Setting_other__c = null,
                                                                                                Other_CheckBox__c = true,
                                                                                                PQI_indicator_Other__c = null,
                                                                                                PQI_Required_Field__C =false                                                                                                                                                                                              
                                                                                            );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id !=null);

        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);   
        potentialQualityIssue.Completed();
        potentialQualityIssue.sendPRC();
        potentialQualityIssue.approveRecord();
        potentialQualityIssue.rejectRecord();
        potentialQualityIssue.autoPopulateMember();
        potentialQualityIssue.closeRecord();
        potentialQualityIssue.save();
        potentialQualityIssue.OtherValue();
        potentialQualityIssue.OtherValuePqiIndicator();
        potentialQualityIssue.isOtherMedical();
        test.stopTest();
    }
    
   /*******************************************************************
    Purpose:  This method is used to test approve record and this method is use for  Approve button and approve prc button
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/
    static testMethod void approveRecord_Test() {
        
        user us=AP01_TestDataUtility.createUserPQI();
        /*********************************************************************** 
        Verifying the User has been created successfully
        Expected Result: user id is not null
        Actual Result: user id  is not null 
        ***********************************************************************/ 
        system.assert(us.id!=null);
        
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C ='New',
                                                                                                bypass_cmo__c = true,
                                                                                                Comment_CMO__c =null,
                                                                                                Comment_PRC__c = null,
                                                                                                Comment_UM__c = null,
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.Completed();
        potentialQualityIssue.approveRecord();
        newPotentialQualityIssue.PQI_Status__C ='UM Review';
        update newPotentialQualityIssue;
        potentialQualityIssue.approveRecord();
        potentialQualityIssue.rejectRecord();
        test.stopTest();    
    }

    /*******************************************************************
    Purpose:  This method is used to test hit the approval process by the Vf page  for reject button
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: Yes
    ********************************************************************/
    static testMethod void updatequeueReject_Negative() {
        
        user us=AP01_TestDataUtility.createUserPQI();
        /*********************************************************************** 
        Verifying the User has been created successfully
        Expected Result: user id is not null
        Actual Result: user id  is not null 
        ***********************************************************************/ 
        system.assert(us.id!=null);
        
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C ='New',
                                                                                                bypass_cmo__c = false,
                                                                                                Comment_CMO__c =null,
                                                                                                Comment_PRC__c = null,
                                                                                                Comment_UM__c = null,
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.Completed();
        potentialQualityIssue.approveRecord();
        newPotentialQualityIssue.PQI_Status__C ='UM Review';
        update newPotentialQualityIssue;
        potentialQualityIssue.approveRecord();
        potentialQualityIssue.rejectRecord();
        PQIUpdateQueue objPQIUpdateQueue = new PQIUpdateQueue();
        objPQIUpdateQueue.updatequeueReject(null);
        test.stopTest();
        
        
    }
    /*******************************************************************
    Purpose:  This method is used to test hit the approval process by the Vf page  for reject button
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/
    static testMethod void approveRecord_NegativeTest() {
        user us=AP01_TestDataUtility.createUserPQI();
        /*********************************************************************** 
        Verifying the User has been created successfully
        Expected Result: user id is not null
        Actual Result: user id  is not null 
        ***********************************************************************/ 
        system.assert(us.id!=null);
        
        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C =System.Label.CL147_MD_Review,
                                                                                                Comment_CMO__c =null,
                                                                                                Comment_PRC__c = null,
                                                                                                Comment_UM__c = null,
                                                                                                bypass_cmo__c = false,
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.Completed();
        potentialQualityIssue.approveRecord();
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL148_MD_Approved;
        newPotentialQualityIssue.bypass_cmo__c = true;
        update newPotentialQualityIssue;
        ApexPages.StandardController sc4 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue4= new VFC41_Potential_Quality_Issue (sc4);
        potentialQualityIssue4.approveRecord();
        potentialQualityIssue.rejectRecord();
        test.stopTest();
    }
    
    /*******************************************************************
    Purpose:   This method is used to negative test submit approval process from from vf page.
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/
    static testMethod void CompletedapproveRecord_Test() {
        user us=AP01_TestDataUtility.createUserPQI();
        /*********************************************************************** 
        Verifying the User has been created successfully
        Expected Result: user id is not null
        Actual Result: user id  is not null 
        ***********************************************************************/ 
        system.assert(us.id!=null);

        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C ='PRC',
                                                                                                Comment_CMO__c =null,
                                                                                                Comment_PRC__c = null,
                                                                                                Comment_UM__c = null,
                                                                                                bypass_cmo__c = false,
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.Completed();
        potentialQualityIssue.approveRecord();
        potentialQualityIssue.rejectrecord();
        test.stopTest();
    }
   
     /*******************************************************************
    Purpose:   This method is used to test approve record and this method is use for  Reject button and Reject prc button
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/
    static testMethod void rejectrecord_Test() {
        
        user us=AP01_TestDataUtility.createUserPQI();
        /*********************************************************************** 
        Verifying the User has been created successfully
        Expected Result: user id is not null
        Actual Result: user id  is not null 
        ***********************************************************************/ 
        system.assert(us.id!=null);

        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C ='New',
                                                                                                Comment_CMO__c =null,
                                                                                                Comment_PRC__c = null,
                                                                                                Comment_UM__c = null,
                                                                                                bypass_cmo__c = false,
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.Completed();
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL146_UM_Review;
        update newPotentialQualityIssue;
        ApexPages.StandardController sc1 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue1= new VFC41_Potential_Quality_Issue (sc1);
        potentialQualityIssue1.rejectrecord();
        
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL147_MD_Review;
        update newPotentialQualityIssue;
        
        ApexPages.StandardController sc2 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue2= new VFC41_Potential_Quality_Issue (sc2);
        potentialQualityIssue2.rejectrecord();
        
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL154_PRC;
        update newPotentialQualityIssue;
        
        ApexPages.StandardController sc3 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue3= new VFC41_Potential_Quality_Issue (sc3);
        potentialQualityIssue3.rejectrecord();
        // comment is not null
        newPotentialQualityIssue.Comment_CMO__c ='test111';
        newPotentialQualityIssue.Comment_PRC__c = 'test111';
        newPotentialQualityIssue.Comment_UM__c = 'test111';
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL146_UM_Review;
        update newPotentialQualityIssue;
        ApexPages.StandardController sc4 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue4= new VFC41_Potential_Quality_Issue (sc4);
        potentialQualityIssue4.rejectrecord();
        
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL147_MD_Review;
        update newPotentialQualityIssue;
        ApexPages.StandardController sc5 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue5= new VFC41_Potential_Quality_Issue (sc5);
        potentialQualityIssue5.rejectrecord();
        
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL154_PRC;
        update newPotentialQualityIssue;
        ApexPages.StandardController sc6 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue6= new VFC41_Potential_Quality_Issue (sc6);
        potentialQualityIssue6.rejectrecord();
        
        test.StopTest();
    }
     /*******************************************************************
    Purpose:   This method is used to Negative test approve record and this method is use for  Reject button and Reject prc button
    Parameters: N/A 
    Returns: PageReference 
    Throws [Exceptions]: N/A
    ********************************************************************/
    static testMethod void rejectrecord_NegativeTest() {
        
        user us=AP01_TestDataUtility.createUserPQI();
        /*********************************************************************** 
        Verifying the User has been created successfully
        Expected Result: user id is not null
        Actual Result: user id  is not null 
        ***********************************************************************/ 
        system.assert(us.id!=null);

        Account assignedAccount =  AP01_TestDataUtility.createPortalAccount();
        /*********************************************************************** 
        Verifying the Account has been created successfully
        Expected Result: Account id is not null
        Actual Result: Account id  is not null 
        ***********************************************************************/ 
        system.assert(assignedAccount.id!=null);
        
        List<Contact> ContactToInsert = AP01_TestDataUtility.createContactListForPQI(assignedAccount);
        set<Id> setTestRecId = new set<Id>();
        for(Contact co : ContactToInsert){
            setTestRecId.add(co.id);
        }
        Potential_Quality_Issue__c   newPotentialQualityIssue = new Potential_Quality_Issue__c (Access_Availability__c =true,
                                                                                                Description_of_Events1__c ='Test Address',
                                                                                                Medical_Director_Recommendations__c ='test',
                                                                                                Medical_Director_Review_Summary1__c ='123123',
                                                                                                Member_ID__c =ContactToInsert[0].id,
                                                                                                Member_Name__c = 'test',
                                                                                                Member_Medical_Group_Affiliation__c ='Small',
                                                                                                Member_DOB__C =system.today(),
                                                                                                PCP_Practioner_Name__c ='Test',
                                                                                                Settings__c ='Office',
                                                                                                PQI_Status__C ='New',
                                                                                                Comment_CMO__c =null,
                                                                                                Comment_PRC__c = null,
                                                                                                Comment_UM__c = null,
                                                                                                bypass_cmo__c = false,
                                                                                                PQI_Referral_Date__c = system.today(),
                                                                                                PQI_Referred_By__c ='test',
                                                                                                Assigned_RN__c =us.id,
                                                                                                Reason_for_Referral__c ='test user',
                                                                                                RN_Timeline_of_Key_Events__c ='test rn',
                                                                                                RN_Case_Review_Summary1__c ='test summary',
                                                                                                RN_Justification_of_Recommendation__C ='test',
                                                                                                RN_Pertinent_criteria_guidelines_standa__c ='test critera',
                                                                                                Peer_Review_Credentialing_Outcome__c ='test',
                                                                                                PQI_Required_Field__C =true
                                                                                               );
        insert newPotentialQualityIssue;
        /*********************************************************************** 
        Verifying the Potential_Quality_Issue__c has been created successfully
        Expected Result: Potential_Quality_Issue__c id is not null
        Actual Result: Potential_Quality_Issue__c id  is not null 
        ***********************************************************************/ 
        system.assert(newPotentialQualityIssue.id!=null);
        ApexPages.StandardController sc = new ApexPages.StandardController(newPotentialQualityIssue );
        test.startTest();
        VFC41_Potential_Quality_Issue potentialQualityIssue= new VFC41_Potential_Quality_Issue (sc);
        potentialQualityIssue.Completed();
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL146_UM_Review;
        update newPotentialQualityIssue;
        ApexPages.StandardController sc1 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue1= new VFC41_Potential_Quality_Issue (sc1);
        potentialQualityIssue1.rejectrecord();
        
        newPotentialQualityIssue.PQI_Status__C = System.Label.CL147_MD_Review;
        newPotentialQualityIssue.Comment_CMO__c = 'test';
        update newPotentialQualityIssue;
        
        ApexPages.StandardController sc2 = new ApexPages.StandardController(newPotentialQualityIssue );
        VFC41_Potential_Quality_Issue potentialQualityIssue2= new VFC41_Potential_Quality_Issue (sc2);
        potentialQualityIssue2.rejectrecord();
      
        test.StopTest();
    }
}