Sutter Health/src/objects/Contact_Validation_Audit_Trail__c.object
<CustomObject>
    <description>Custom Object for tracking Contact fields initial and final value.</description>
    <fields>
        <fullName>Address_Change__c</fullName>
        <label>Address Change</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address_Modified__c</fullName>
        <label>Address Modified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secure_City__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure City</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Fax__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secure_Floor__c</fullName>
        <label>Secure Floor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone_Ext__c</fullName>
        <label>Secure Phone Ext</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secure_State__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secure_Street_Address__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Suite__c</fullName>
        <label>Secure Suite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Zip_Code__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Validation Update</label>
    <nameField>
        <displayFormat>Validation-{0}</displayFormat>
        <label>Provider Validation Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Validation Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/PDV_EAF_Validation_Audit_Trail__c.object
<CustomObject>
    <fields>
        <fullName>ADDRESS__c</fullName>
        <label>ADDRESS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Change__c</fullName>
        <label>Address Change</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address_Modified__c</fullName>
        <label>Address Modified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CITY__c</fullName>
        <label>CITY</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAX_NUMBER__c</fullName>
        <label>FAX NUMBER</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Floor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PHONE__c</fullName>
        <label>PHONE</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>STATE__c</fullName>
        <label>STATE</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suite__c</fullName>
        <label>Suite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP_CODE__c</fullName>
        <label>ZIP CODE</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EAF Validation Audit Trail</label>
    <nameField>
        <label>EAF Validation Audit Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAF Validation Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/SOCCaseDetail.cls
public without sharing class SOCCaseDetail {
    
    public string caseId;
    public Case caseObj {get;set;}
    public List<WRAddressCaseHistory> lstCaseAddressHistory {get;set;}
    string prefix;
   
    public  SOCCaseDetail() {
        caseObj = new Case();
        caseId = ApexPages.currentPage().getParameters().get('caseId');
        caseObj =  [select casenumber,Provider_Name__c,Provider_Type__c,PDV_Contact_Name__c,Contact_Number__c,Validated_or_not__c,Direct_Talk_to_Provider__c,
                            status,PDV_Escalation_Reason__c,SOC_Document_Status__c,Origin,Provider_Id_EAF_ID__c,Common_Subject_Lines__c,Communication_Preference_Changed_To_Fax__c,
                            subject,description,Close_Reason__c,CreatedBy.Name,Internal_Comments__c,MU_Escalation_Status__c,MU_Comments__c,contactId    
                            from case where Id = :caseId];
        if(caseObj.contactId != null) {
            prefix = '003';
        }                    
       fillCaseAddressHistory();                     
                   
    }
    
    public void fillCaseAddressHistory() {
        lstCaseAddressHistory = new List<WRAddressCaseHistory>();
        caseObj =  [select casenumber,Provider_Name__c,Provider_Type__c,PDV_Contact_Name__c,Contact_Number__c,Validated_or_not__c,Direct_Talk_to_Provider__c,
                                status,PDV_Escalation_Reason__c,SOC_Document_Status__c,Origin,Provider_Id_EAF_ID__c,Common_Subject_Lines__c,Communication_Preference_Changed_To_Fax__c,
                                subject,description,Close_Reason__c,CreatedBy.Name,Internal_Comments__c,MU_Escalation_Status__c,MU_Comments__c,
                                (Select ADDRESS__c, CITY__c, STATE__c, ZIP_CODE__c, PHONE__c, FAX_NUMBER__c, Suite__c, Floor__c, Address_Modified__c,lastmodifieddate,Address_Change__c,
                                    LastModifiedBy.Name From EAF_Validation_Audit_Trails__r order by LastModifiedDate desc), 
                                (Select Secure_City__c, Secure_Fax__c, Secure_Phone__c, Secure_State__c, Secure_Street_Address__c, Secure_Zip_Code__c, Secure_Suite__c, Secure_Floor__c,
                                Address_Change__c, Secure_Phone_Ext__c, Address_Modified__c,lastmodifieddate,LastModifiedBy.Name,CreatedBy.Name,Serial_Number__c From Provider_Validation_Updates__r  order by LastModifiedDate desc)     
                                from case where Id = :caseId];
        if(prefix=='003') {
                for(Contact_Validation_Audit_Trail__c obj : caseObj.Provider_Validation_Updates__r) {
                        WRAddressCaseHistory wrObj = new WRAddressCaseHistory();
                        wrObj.auditId = obj.id;
                        wrObj.addressModified = obj.Address_Modified__c;
                        //wrObj.strAddress = 'Modified By ' +obj.LastModifiedBy.Name + ': ' +obj.lastmodifieddate.format()+' '+'Address S#: '+obj.Serial_Number__c+' From '+ obj.Secure_Street_Address__c +' '+ obj.Secure_City__c+' To';//New Change
                        wrObj.strAddress  = obj.Address_Change__c;
                        wrObj.lastModifiedDate = obj.lastmodifieddate.format();
                        wrObj.strAddressModifiedBy = obj.CreatedBy.Name;
                        lstCaseAddressHistory.add(wrObj);
                }
        } else {
                for(PDV_EAF_Validation_Audit_Trail__c obj : caseObj.EAF_Validation_Audit_Trails__r) {
                        WRAddressCaseHistory wrObj = new WRAddressCaseHistory();
                        wrObj.auditId = obj.id;
                        wrObj.addressModified = obj.Address_Modified__c;
                        //wrObj.strAddress = 'Modified By ' +obj.LastModifiedBy.Name + ':' +obj.ADDRESS__c+' '+ obj.CITY__c;//New Change
                        wrObj.strAddress  = obj.Address_Change__c;
                        wrObj.lastModifiedDate = obj.lastmodifieddate.format();
                        wrObj.strAddressModifiedBy = obj.LastModifiedBy.Name;
                        lstCaseAddressHistory.add(wrObj);
                }
        }
    }
    
    public class WRAddressCaseHistory {
        public string auditId {get;set;}
        public string addressModified {get;set;}
        public string lastModifiedDate {get;set;}
        public string strAddress {get;set;}//New Change
        public string strAddressModifiedBy {get;set;}
    }
}