Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_External_ID1__c</fullName>
        <description>External ID used to match a contact record to its equivalent record in a source system when updating and/or inserting.</description>
        <externalId>true</externalId>
        <label>Contact External ID 1</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Deficiency_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value in this field will be used to populate the HIM Deficiency Communication preference</description>
        <label>Deficiency Provider?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ok_To_Text__c</fullName>
        <description>PDV</description>
        <label>Ok To Text</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Extension__c</fullName>
        <label>Phone Extension</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Communication Preferences – EHR</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Basket</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Access_Type__c</fullName>
        <description>EPIC Access Type field. The value in this field will be used to control the pick list values of communication preference fields</description>
        <label>Access Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Active_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Provider Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Address_Line_2__c</fullName>
        <label>Provider Address Line_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Admin_Assistant_Email__c</fullName>
        <description>Used to capture admin assistant email</description>
        <label>Delegate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Admin_Assistant_Phone__c</fullName>
        <label>Delegate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Admin_Assistant_Title__c</fullName>
        <description>Used to capture provider assistant title.</description>
        <label>Delegate Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Admin_Assistant__c</fullName>
        <description>Used to capture admin assistant name</description>
        <label>Delegate Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Communication_Preferences_HIM__c</fullName>
        <label>Communication Preferences – HIM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Basket Message</fullName>
                </value>
                <value>
                    <fullName>In Basket Letter</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Printed Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Address__c</fullName>
        <label>Provider Correspondence Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_City__c</fullName>
        <label>Provider Correspondence City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Fax_Number__c</fullName>
        <label>Provider Correspondence Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_PostalCode__c</fullName>
        <label>Provider Correspondence PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Correspondence_State__c</fullName>
        <label>Provider Correspondence State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_ID__c</fullName>
        <label>Provider ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_NPI__c</fullName>
        <label>Provider NPI</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Practicing_Physician__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Practicing Physician</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Resigned_From_Sutter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Resigned From Sutter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Retired_Departed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retired/Departed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Title__c</fullName>
        <label>Provider Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Teleform_Last_Validation_Date__c</fullName>
        <label>Teleform Last Validation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>PCRM Field -  Contains provider userame</description>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Admin_Assistant_Email__c</fullName>
        <label>Delegate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Admin_Assistant_Phone__c</fullName>
        <label>Delegate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Admin_Assistant_Title__c</fullName>
        <label>Delegate Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admin_Assistant__c</fullName>
        <label>Delegate Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communication_Preferences_HIM__c</fullName>
        <label>Communication Preferences – HIM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Basket Message</fullName>
                </value>
                <value>
                    <fullName>In Basket Letter</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Printed Letter (USPS)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deficiency_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value in this field is used to populate the &quot;Communication Preference - HIM Deficiency&quot; field.</description>
        <label>Deficiency Provider?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>New_Street_Address__c</fullName>
        <label>New Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ok_to_Text__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ok to Text</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PDI_Campaign__c</fullName>
        <description>Used to indicate Campaign flag</description>
        <label>PDI Campaign</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practicing_Physician__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Provider Service Status</description>
        <label>Practicing Physician</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Communication_Method__c</fullName>
        <label>Communication Preferences – EHR</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Basket</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProviderInfoHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Old Provider Summary</label>
        <referenceTo>Contact_Validation_Summary__c</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Provider_Information_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Access_Type__c</fullName>
        <label>Provider Access Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Active_Status__c</fullName>
        <formula>Contact_Id__r.Provider_Active_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_ID__c</fullName>
        <label>Provider ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Last_Login_Date__c</fullName>
        <label>Provider Last Login Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Title__c</fullName>
        <label>Provider Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resigned_From_Sutter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive Provider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retired_Departed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Provider Service Status</description>
        <label>Retired / Departed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secure_City__c</fullName>
        <label>Secure City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Street_Address__c</fullName>
        <label>Secure Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status field created as part of REQ 3611 PDV Call Center</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Validated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Validation-Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/PDICampaignInitiationHelper.cls
/*****************************************************
Class Name: PDICampaignInitiationHelper 
Created By: Nagarjuna Kaipu
Created Date: 21/06/2016
Description: This class is used to create the new campaign initiation records
References: ManageContactDatabase Class
*****************************************************/
public class PDICampaignInitiationHelper {
    /*
Method Name: CreateNewCampaignProviderRecords
Description: Used to create new campaign records as part of MDM full file for updated records.
Params: Contacts map
return type: Void
*/
    public static Void CreateNewCampaignProviderRecords(Map<Id, Contact> newContactMap)
    {
        String CommunicationPreferencesHIM;
        Id oldSummaryId;
        Datetime providerLastLoginDate;
        Decimal serialNumber;
        String newStreetAddress;
        List<Contact_Validation_Summary__c> cvsList = new List<Contact_Validation_Summary__c>(); 
        List<Contact_Validation_Summary__c> summaryContacts = new List<Contact_Validation_Summary__c>();
        List<Contact> providerContacts = new List<Contact>();
        Map<Id,List<Contact_Validation_Summary__c>> mapContactRelatedSummary = new Map<id,List<Contact_Validation_Summary__c>>();
        Map<id,Contact> mapSummaryCreateContacts = new Map<id,Contact>();
        
        
        mapSummaryCreateContacts = newContactMap;
        System.debug('mapSummaryCreateContacts1 are: '+mapSummaryCreateContacts);
        summaryContacts = [select Contact_Id__c,Address_Type__c from Contact_Validation_Summary__c where Contact_Id__c in: mapSummaryCreateContacts.keyset() and  Address_Type__c =: Label.CL303_PDIPrimary and PDI_Campaign__c =: Label.CL176_PDI_Current_Campaign_Name ];     
        System.debug('summaryContacts are: '+summaryContacts);
        for(Contact_Validation_Summary__c tempsummary:summaryContacts){  
            mapSummaryCreateContacts.remove(tempsummary.Contact_Id__c); 
        }
        System.debug('mapSummaryCreateContacts are: '+mapSummaryCreateContacts);
        //Querying updated contact field values
        providerContacts =  [select Id, Name, Preferred_Communication_Method__c,Ok_To_Text__c,Provider_Name__c,Provider_Address_Line_2__c,
                             Provider_Title__c,Email,MobilePhone,Provider_Correspondence_Address__c,Provider_Admin_Assistant_Phone__c,
                             Provider_Correspondence_City__c,Provider_Correspondence_State__c,Provider_Correspondence_PostalCode__c,
                             Provider_Correspondence_Phone__c,Provider_Correspondence_Fax_Number__c, Provider_Active_Status__c, Provider_Retired_Departed__c,
                             Provider_Resigned_From_Sutter__c, Provider_Practicing_Physician__c, Provider_Communication_Preferences_HIM__c,
                             Provider_ID__c,Provider_NPI__c,Provider_Admin_Assistant__c,Provider_Admin_Assistant_Email__c,
                             Provider_Access_Type__c,Provider_Type__c,Deficiency_Provider__c,Phone_Extension__c,Provider_Admin_Assistant_Title__c,
                             Contact_External_ID1__c,Username__c,Teleform_Last_Validation_Date__c,
                             (select Id, Contact_Id__c, ProviderInfoHistory__c, Provider_Last_Login_Date__c, New_Street_Address__c, Serial_Number__c, Address_Type__c from Summarys__r Where PDI_Campaign__c =: Label.CL175_PDI_Old_Campaign_Name and Address_Type__c =: Label.CL303_PDIPrimary Limit 1)
                             from contact 
                             where id in: mapSummaryCreateContacts.keyset() and Provider_Active_Status__c = true];
        
        //Querying Non Validate Queue Id
        List<Group> nonValidatedProviderQueue = [select Id from Group where Name = 'Non Validated Providers' and Type = 'Queue' limit 1];
        if(!providerContacts.isEmpty()) {  
            for(Contact tempCon : providerContacts) {
                if(tempCon.Summarys__r.Size()>0)
                {
                    oldSummaryId = tempCon.Summarys__r[0].Id;
                    providerLastLoginDate = tempCon.Summarys__r[0].Provider_Last_Login_Date__c;
                    serialNumber = tempCon.Summarys__r[0].Serial_Number__c;
                    newStreetAddress = tempCon.Summarys__r[0].New_Street_Address__c;
                }
                if(tempCon.Provider_Communication_Preferences_HIM__c!=null && tempCon.Provider_Communication_Preferences_HIM__c.containsIgnoreCase('Printed Letter')){
                    CommunicationPreferencesHIM = 'Printed Letter (USPS)';
                }
                else
                {
                    CommunicationPreferencesHIM = tempCon.Provider_Communication_Preferences_HIM__c;
                }
                
                if('true'.equalsIgnoreCase(Label.CL375_PDIAllowInactiveProvider) && tempCon.Provider_Resigned_From_Sutter__c == true){
                    tempCon.Provider_Practicing_Physician__c = true;
                    tempCon.Provider_Resigned_From_Sutter__c = false;
                }
                
                cvsList.add(new Contact_Validation_Summary__c(
                    ProviderInfoHistory__c = oldSummaryId
                    , Provider_Name__c = tempCon.Provider_Name__c
                    , Provider_Title__c = tempCon.Provider_Title__c
                    , Provider_ID__c = tempCon.Provider_ID__c
                    , Contact_ID__c = tempCon.id
                    , Username__c = tempCon.Username__c
                    , Name = tempCon.Name
                    , Email__c = tempCon.Email
                    //Replacing 1 from mobile phone
                    , Mobile_Phone__c = String.isNotBlank(tempCon.MobilePhone) && tempCon.MobilePhone.SubString(0,1).Contains('1') ? 
                    tempCon.MobilePhone.SubString(1, tempCon.MobilePhone.Length()): tempCon.MobilePhone
                    , Ok_To_Text__c = String.isNotBlank(tempCon.Ok_To_Text__c)? Boolean.valueOf(tempCon.Ok_To_Text__c) : false
                    
                    , Address_Type__c = Label.CL303_PDIPrimary
                    , Serial_Number__c = serialNumber
                    , New_Street_Address__c = tempCon.Provider_Correspondence_Address__c
                    , Address_Line_2__c = tempCon.Provider_Address_Line_2__c
                    , Secure_Street_Address__c = tempCon.Provider_Correspondence_Address__c
                    , Secure_City__c = tempCon.Provider_Correspondence_City__c
                    , Secure_State__c = tempCon.Provider_Correspondence_State__c
                    , Secure_Zip_Code__c = tempCon.Provider_Correspondence_PostalCode__c
                    , Secure_Phone__c = String.isNotBlank(tempCon.Provider_Correspondence_Phone__c) && tempCon.Provider_Correspondence_Phone__c.SubString(0,1).Contains('1') ? 
                    tempCon.Provider_Correspondence_Phone__c.SubString(1, tempCon.Provider_Correspondence_Phone__c.Length()): tempCon.Provider_Correspondence_Phone__c
                    , Secure_Phone_Ext__c = tempCon.Phone_Extension__c
                    , Secure_Fax__c = String.isNotBlank(tempCon.Provider_Correspondence_Fax_Number__c) && tempCon.Provider_Correspondence_Fax_Number__c.SubString(0,1).Contains('1') ? 
                    tempCon.Provider_Correspondence_Fax_Number__c.SubString(1, tempCon.Provider_Correspondence_Fax_Number__c.Length()): tempCon.Provider_Correspondence_Fax_Number__c
                    , Tech_Phone_Number__c = String.isNotBlank(tempCon.Provider_Correspondence_Phone__c) ? tempCon.Provider_Correspondence_Phone__c.replaceAll('[^0-9]','') : null
                    , Preferred_Communication_Method__c = tempCon.Preferred_Communication_Method__c
                    , Communication_Preferences_HIM__c = CommunicationPreferencesHIM 
                    , Provider_Access_Type__c = tempCon.Provider_Access_Type__c 
                    , Provider_Type__c = tempCon.Provider_Type__c
                    , Deficiency_Provider__c = tempCon.Deficiency_Provider__c
                    , PDI_Campaign__c = Label.CL176_PDI_Current_Campaign_Name
                    , Retired_Departed__c = tempCon.Provider_Retired_Departed__c 
                    , Resigned_From_Sutter__c = tempCon.Provider_Resigned_From_Sutter__c 
                    , Practicing_Physician__c = tempCon.Provider_Practicing_Physician__c 
                    
                    , Admin_Assistant__c = tempCon.Provider_Admin_Assistant__c 
                    , Admin_Assistant_Email__c = tempCon.Provider_Admin_Assistant_Email__c 
                    , Admin_Assistant_Phone__c = String.isNotBlank(tempCon.Provider_Admin_Assistant_Phone__c) && tempCon.Provider_Admin_Assistant_Phone__c.SubString(0,1).Contains('1') ? 
                    tempCon.Provider_Admin_Assistant_Phone__c.SubString(1, tempCon.Provider_Admin_Assistant_Phone__c.Length()): tempCon.Provider_Admin_Assistant_Phone__c
                    , Admin_Assistant_Title__c = tempCon.Provider_Admin_Assistant_Title__c
                    
                    , Status__c = 'Non-Validated'
                    , Provider_Last_Login_Date__c = providerLastLoginDate
                    , OwnerId = nonValidatedProviderQueue.size()>0 ? nonValidatedProviderQueue[0].id : UserInfo.getUserId()
                    
                ));
            }
            
            List<Id> successIds = new List<Id>();
            List<Id> IdstoUpdate = new List<Id>();
            List<Contact_Validation_Summary__c> successListToUpdate = new List<Contact_Validation_Summary__c>();
            
            if(!cvsList.isEmpty())
            {
                Database.SaveResult[] newCampRecs = Database.insert(cvsList, false);
                for(Database.SaveResult dsr : newCampRecs){
                    if(dsr.isSuccess()){
                        successIds.add(dsr.getId());
                    }
                }
                
                
                if(!successIds.isEmpty())
                {
                    for(Contact_Validation_Summary__c cvsIds: [SELECT ProviderInfoHistory__c FROM Contact_Validation_Summary__c WHERE Id IN: successIds LIMIT 2000])
                    {
                        IdstoUpdate.add(cvsIds.ProviderInfoHistory__c);
                    }
                    successListToUpdate = [SELECT Id FROM Contact_Validation_Summary__c WHERE Id IN: IdstoUpdate LIMIT 2000];
                    for(Contact_Validation_Summary__c campUpdate: successListToUpdate)
                    {
                        campUpdate.Tech_Is_Campaign_Done__c = true;
                    }
                    update successListToUpdate;
                    successIds.clear();
                    IdstoUpdate.clear();
                    successListToUpdate.clear();
                } 

            }
            
        }      
    }
}