Sutter Health/src/objects/Contact_Script__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Resources for Customer Service Agents; step-by-step instructions to resolve inquiries</description>
    <label>Contact Script</label>
    <pluralLabel>Contact Scripts</pluralLabel>
</CustomObject>

Sutter Health/src/objects/SH_History__c.object
<CustomObject>
    <fields>
        <fullName>SH_Article_Id__c</fullName>
        <label>Article Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SH_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SH_Historys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>History</label>
    <nameField>
        <displayFormat>H - {00000}</displayFormat>
        <label>History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/SH_HistoryTest.cls
@isTest
/*
    This class is used to cover the SH_History class
    ==========================================================
    Name                    Date                       version
    ==========================================================
    Prashant Kumar          05/10/2015                   1.0
    ==========================================================  
*/
private class SH_HistoryTest {
    //this method is used to cover the validateHistory method
    static testmethod void ValidateHistory() {
        Contact_Script__kav objArticle = Sh_commontest.CreateArticleData('TestarticleTitle','TestarticleTitle');
        string articleId = objArticle.knowledgeArticleId ;

        Test.startTest();

        User objUser = SH_CommonTest.CreateCommunityUser();
        SH_History__c oHistory = new SH_History__c();
        oHistory.SH_Summary__c='Test';
        oHistory.SH_Title__c='Test';
        oHistory.SH_User__c=objUser.id;
        oHistory.SH_Article_Id__c= articleId ;
        insert oHistory;
        
        SH_History.ArticleHistory objAh=new SH_History.ArticleHistory(oHistory);
        Test.stopTest();
        system.runAs(objUser)
        {
            SH_History objHistory = new SH_History();
        }
    }
}