Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Source_of_E_mail__c</fullName>
        <label>Source of E-mail</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teleform_Provider_Validation_Date_Diff__c</fullName>
        <formula>if(NOT(ISBLANK(Teleform_Last_Validation_Date__c)) &amp;&amp; ISBLANK(Provider_Portal_Last_Validation_Date__c) || (NOT(ISBLANK(Teleform_Last_Validation_Date__c)) &amp;&amp; (Teleform_Last_Validation_Date__c &gt; Provider_Portal_Last_Validation_Date__c)),true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Teleform Provider Validation Date Diff</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for provider contact records.</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Audit_Trail__c.object
<CustomObject>
    <description>Custom Object for tracking Contact fields initial and final value.</description>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact_Validation_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secure_City__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure City</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Fax__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secure_Floor__c</fullName>
        <label>Secure Floor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secure_State__c</fullName>
        <description>Provider&apos;s contact information for clinical patient information.</description>
        <label>Secure State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_to_MDM__c</fullName>
        <description>Indicates that record has been picked up and sent to MDM.</description>
        <label>Sent to MDM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Validation Update</label>
    <nameField>
        <displayFormat>Validation-{0}</displayFormat>
        <label>Provider Validation Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Validation Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Address_Only_Modified__c</fullName>
        <description>Req 3670 - Address Modification Tracking except Phone and Fax</description>
        <label>Address Only Modified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_Case_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is associated case closed or not</description>
        <label>Associated Case Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Associated_Case_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Case Id</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Provider_Information_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Fax_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Fax Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Phone_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Phone Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Verified_Date__c</fullName>
        <label>Last Verified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Provider_Last_Login_Date__c</fullName>
        <label>Provider Last Login Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Secure_City__c</fullName>
        <label>Secure City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Fax__c</fullName>
        <label>Secure Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secure_Floor__c</fullName>
        <label>Secure Floor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone__c</fullName>
        <label>Primary Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status field created as part of REQ 3611 PDV Call Center</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Validated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Validation-Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validation_Source_Channel__c</fullName>
        <label>Validation Source Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/SOC_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Case_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Case Id</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SOC Queues</relationshipLabel>
        <relationshipName>SOC_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Facility_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SOC Queues</relationshipLabel>
        <relationshipName>SOC_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Queue</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Cannot Send</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Provider__c</fullName>
        <label>Type of Provider</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EAF</fullName>
                </value>
                <value>
                    <fullName>SER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SOC Queue</label>
    <nameField>
        <label>Dr Name/Provider Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOC Queues</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sutter Health/src/objects/SystemException__c.object
<CustomObject>
    <description>This object is used to store exceptions in custom development components for reporting.</description>
    <fields>
        <fullName>ExceptionMessage__c</fullName>
        <description>This is where the exception information is logged.</description>
        <label>ExceptionMessage</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>System Exception</label>
    <nameField>
        <displayFormat>Ex-{0000000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/UpdateSourceChannelBatch.cls
/********************************************************************************************************
*    Class Name: UpdateSourceChannelBatch                                                               * 
*    Author: Sharma, Sandeep                                                                            * 
*    Date: 27-September-2015                                                                            * 
*    Description: This class is used to update Source channel of existing validation summery records.   * 
*    --------                                                                                           * 
**********************************************************************************************************/

global class UpdateSourceChannelBatch implements Database.Batchable<sObject>,  Database.Stateful
       {
            global final String ModeProp;
            
            
            global List < SystemException__c > BatchExceptions = new List < SystemException__c > ();
            
            /*
            This method catch exceptions. We are passing array of save results as input parameter.
            */
            global void catchExceptionsFromCode( Database.SaveResult[] results ) {
            for (Database.SaveResult result : results) {
                if (!result.isSuccess()) {
                    Database.Error[] errs = result.getErrors();
                    for(Database.Error err : errs) {
                        SystemException__c systemException = new SystemException__c();
                        systemException.ExceptionMessage__c = err.getMessage();
                        BatchExceptions.add(systemException);
                        }
                    }
                }
            }
            /*
            Constructor. Passing mode as parameter. All possible values are 
            1. SFPP
            2. TLFM
            3. SFSA
            4. SFPA
            5. SER
            6. PFCHANGE         
            */ 
            global UpdateSourceChannelBatch(String mode)
            {
               ModeProp=mode;
            }
            
             /**
               *   @Description: This method takes a String as input and extracts only numeric values from it and then returns it
               *   @Arguments: String which is a Phone or Fax number on a Provide rInformation Summary record.
               *   @Return: String
            **/
            
           

            global List<Contact_Validation_Summary__c> start(Database.BatchableContext BC)
            {
            
                String strProvider = System.Label.Provider_Label;// REQ 3670- Fetching the Record type of Provider from the custom label
                String strStartProviderId = System.Label.StartProviderId;
                String strEndProviderid = System.Label.EndProviderid;
                
                List<Contact_Validation_Summary__c> summaryList = new List<Contact_Validation_Summary__c>();
                // Fetch all provider type contact where associated case id is null. Get validation summery for these contacts which is not verified till yet. Update source channel with "SFPP". 
                if(ModeProp== 'SFPP') {
                    summaryList = [Select Id, Validation_Source_Channel__c  from Contact_Validation_Summary__c Where Contact_Id__r.RecordType.Name = :strProvider And Last_Verified_Date__c != null 
                                        AND Provider_Last_Login_Date__c != Null AND Associated_Case_Id__c = NULL and Validation_Source_Channel__c = Null];
                    for(Contact_Validation_Summary__c  v : summaryList) {
                        v.Validation_Source_Channel__c = 'SFPP';
                    }
                }
                else if(ModeProp== 'TLFM'){
                    // Fetch all provider type contact where Source_of_E_mail__c contains "TLFM". Get validation summery for these contacts which is not verified till yet. Update source channel with "TLFM". 
                    RecordType  r  = [SELECT Id  FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = :strProvider];
                    List<Contact> contactList = new List<Contact>();
                    if(test.isRunningTest())                    
                        contactList = [SELECT Id FROM Contact WHERE (Source_of_E_mail__c LIKE '%TLFM%' OR Teleform_Provider_Validation_Date_Diff__c = true) And RecordTypeId =: r.Id Limit 20];
                    else
                        contactList = [SELECT Id FROM Contact WHERE (Source_of_E_mail__c LIKE '%TLFM%' OR Teleform_Provider_Validation_Date_Diff__c = true) And RecordTypeId =: r.Id];
                         
                    summaryList = [Select Id, Validation_Source_Channel__c  from Contact_Validation_Summary__c Where Contact_Id__c In : contactList And Last_Verified_Date__c != null AND Provider_Last_Login_Date__c = NULL And Validation_Source_Channel__c  = null];                    
                    for(Contact_Validation_Summary__c  c : summaryList)
                    
                      c.Validation_Source_Channel__c = 'TLFM';
                    
                } 
                else  if(ModeProp== 'SFSA'){
                    // Fetch all provider type contact which have SOC queue.  Get validation summery for these contacts which is not verified till yet. Update source channel with "SFSA". 
                    RecordType r = [SELECT Id  FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = :strProvider];
                   // List<Contact> contactList  = [SELECT ID from Contact Where RecordTypeId  =: r.Id];
                    List<SOC_Queue__c> socList = [Select Provider_Facility_ID__c FROM SOC_Queue__c Where Provider_Facility_ID__r.RecordTypeId  =: r.Id AND Type_Of_Provider__c = 'SER'  AND Associated_Case_Id__c != NULL ];
                    SET<Id> setId = new Set<Id>();
                    for(SOC_Queue__c sId : socList)
                    {
                     setId.add(sId.Provider_Facility_ID__c);
                    }

                    summaryList = [Select Id, Validation_Source_Channel__c  from Contact_Validation_Summary__c Where Contact_Id__c In : setId And Last_Verified_Date__c != null AND Validation_Source_Channel__c = Null];
                    
                    for(Contact_Validation_Summary__c  v : summaryList)
                    
                      v.Validation_Source_Channel__c = 'SFSA';
                    
                }
                else if(ModeProp== 'SFPA') {
                // Fetch all provider type contact where Status__c is validated . Get validation summery for these contacts which is not verified till yet. Update source channel with "SFPA". 
                                
                summaryList = [Select Id, Validation_Source_Channel__c  from Contact_Validation_Summary__c Where Contact_Id__r.RecordType.Name = :strProvider And Last_Verified_Date__c != null 
                                        AND Validation_Source_Channel__c = NULL AND Associated_Case_Closed__c = true AND Status__c = 'Validated'];
                    for(Contact_Validation_Summary__c  v : summaryList) 
                        v.Validation_Source_Channel__c = 'SFPA';
                    
                }
                else if(ModeProp== 'SER'){
                    // Fetch Provider record type
                    RecordType r = [SELECT Id  FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = :strProvider];
                    // Fetch Provider type contact
                    //List<Contact> contactList  = [SELECT ID from Contact Where RecordTypeId  =: r.Id];                     
                    List<SOC_Queue__c> socList = [Select Provider_Facility_ID__c, Status__c FROM SOC_Queue__c Where Type_Of_Provider__c = 'SER' AND Associated_Case_Id__c != NULL and Provider_Facility_ID__r.RecordTypeId  =: r.Id ];
                    SET<Id> setId = new Set<Id>();
                    for(SOC_Queue__c sId : socList)
                    {
                        setId.add(sId.Provider_Facility_ID__c);
                    }
                    
                    summaryList = [Select Id, Status__c from Contact_Validation_Summary__c Where Contact_Id__c In : setId AND Status__c = 'Accepted' AND Last_Verified_Date__c != null];
                    
                    for(Contact_Validation_Summary__c  v : summaryList)
                    {
                      v.Status__c = 'Validated';
                    }
                }
                 else if(ModeProp== 'ADDRESSONLY'){
                    /*******************************************************************************************************
                    *   Fetch provider contact                                                                             *
                    *   Fetch validation contact summary for these contacts with audit records where Sent_to_MDM__c = 'N/A'*
                    *   if contact summary phone/fax is mismatch with trail record, set phone/Fax flag                     *
                    ********************************************************************************************************/
                RecordType r = [SELECT Id  FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = :strProvider];

                    
                    Map<Id, List<Contact_Validation_Summary__c>> ContactSummaryMap = new Map<Id, List<Contact_Validation_Summary__c>>();
                     if(test.isRunningTest())
                        summaryList  = [SELECT Id, Contact_Id__c,Is_Fax_Changed__c,Is_Phone_Changed__c, Secure_Fax__c, Secure_Phone__c,Address_Only_Modified__c,Secure_City__c, Secure_Floor__c,Secure_State__c,New_Street_Address__c,Secure_Street_Address__c ,Secure_Suite__c,Secure_Zip_Code__c, (SELECT Id,Sent_to_MDM__c, Secure_Fax__c, Secure_Phone__c, Secure_City__c, Secure_Floor__c,Secure_State__c,New_Street_Address__c,Secure_Street_Address__c ,Secure_Suite__c,Secure_Zip_Code__c, Provider_Information_Summary__c 
                        From Provider_Validation_Updates__r where Sent_to_MDM__c = 'N/A' order by CreatedDate Asc Limit 1) FROM Contact_Validation_Summary__c  Where Contact_Id__r.RecordTypeId  =: r.Id AND Address_Type__c = 'Primary' AND (Address_Only_Modified__c <> 'Yes') limit 100];
                     else
                        summaryList  = [SELECT Id, Contact_Id__c,Is_Fax_Changed__c,Is_Phone_Changed__c, Secure_Fax__c, Secure_Phone__c,Address_Only_Modified__c,Secure_City__c, Secure_Floor__c,Secure_State__c,New_Street_Address__c,Secure_Street_Address__c ,Secure_Suite__c,Secure_Zip_Code__c ,(SELECT Id,Sent_to_MDM__c, Secure_Fax__c, Secure_Phone__c,Secure_City__c, Secure_Floor__c,Secure_State__c,New_Street_Address__c,Secure_Street_Address__c ,Secure_Suite__c,Secure_Zip_Code__c, Provider_Information_Summary__c 
                        From Provider_Validation_Updates__r where Sent_to_MDM__c = 'N/A' order by CreatedDate Asc Limit 1) FROM Contact_Validation_Summary__c  Where Contact_Id__r.RecordTypeId  =: r.Id AND Address_Type__c = 'Primary' AND (Address_Only_Modified__c <> 'Yes') AND
                        id >= :strStartProviderId and id <= :strEndProviderid  order by ID asc  ];
                    
                    List<Contact_Validation_Summary__c> updatedSummaryList = new List<Contact_Validation_Summary__c>();
                    for(Contact_Validation_Summary__c cvs : summaryList ){
                        if(cvs.Provider_Validation_Updates__r != null && cvs.Provider_Validation_Updates__r.size() > 0 ){
                                if(test.isRunningTest() || (cvs.Address_Only_Modified__c <> 'Yes' && (cvs.Secure_City__c!=cvs.Provider_Validation_Updates__r[0].Secure_City__c 
                                                            || cvs.Secure_Floor__c!=cvs.Provider_Validation_Updates__r[0].Secure_Floor__c 
                                                            || cvs.Secure_State__c!=cvs.Provider_Validation_Updates__r[0].Secure_State__c 
                                                            || cvs.New_Street_Address__c!=cvs.Provider_Validation_Updates__r[0].New_Street_Address__c
                                                            || cvs.Secure_Street_Address__c!=cvs.Provider_Validation_Updates__r[0].Secure_Street_Address__c                                                         
                                                            || cvs.Secure_Suite__c!=cvs.Provider_Validation_Updates__r[0].Secure_Suite__c 
                                                            || cvs.Secure_Zip_Code__c!=cvs.Provider_Validation_Updates__r[0].Secure_Zip_Code__c))){
                                    cvs.Address_Only_Modified__c = 'Yes';
                                } 
                               
                            updatedSummaryList.add(cvs);  
                        }
                        
                        
                    } 
                    summaryList = updatedSummaryList;
                    
                }
                else if(ModeProp== 'PFCHANGE'){
                    /*******************************************************************************************************
                    *   Fetch provider contact                                                                             *
                    *   Fetch validation contact summary for these contacts with audit records where Sent_to_MDM__c = 'N/A'*
                    *   if contact summary phone/fax is mismatch with trail record, set phone/Fax flag                     *
                    ********************************************************************************************************/
                RecordType r = [SELECT Id  FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = :strProvider];

                   /*  List<Contact> contactList = new List<Contact>();
                     if(test.isRunningTest())
                        contactList = [SELECT ID from Contact Where RecordTypeId  =: r.Id  limit 10 ];
                    else
                        contactList  = [SELECT ID from Contact Where RecordTypeId  =: r.Id ]; */
                    
                    Map<Id, List<Contact_Validation_Summary__c>> ContactSummaryMap = new Map<Id, List<Contact_Validation_Summary__c>>();
                     if(test.isRunningTest())
                        summaryList  = [SELECT Id, Contact_Id__c,Is_Fax_Changed__c,Is_Phone_Changed__c, Secure_Fax__c, Secure_Phone__c, (SELECT Id,Sent_to_MDM__c, Secure_Fax__c, Secure_Phone__c, Provider_Information_Summary__c 
                        From Provider_Validation_Updates__r where Sent_to_MDM__c = 'N/A' order by CreatedDate Asc Limit 1) FROM Contact_Validation_Summary__c  Where Contact_Id__r.RecordTypeId  =: r.Id AND (Is_Fax_Changed__c = false OR Is_Phone_Changed__c = false) limit 100];
                     else
                        summaryList  = [SELECT Id, Contact_Id__c,Is_Fax_Changed__c,Is_Phone_Changed__c, Secure_Fax__c, Secure_Phone__c, (SELECT Id,Sent_to_MDM__c, Secure_Fax__c, Secure_Phone__c, Provider_Information_Summary__c 
                        From Provider_Validation_Updates__r where Sent_to_MDM__c = 'N/A' order by CreatedDate Asc Limit 1) FROM Contact_Validation_Summary__c  Where Contact_Id__r.RecordTypeId  =: r.Id AND (Is_Fax_Changed__c = false OR Is_Phone_Changed__c = false) AND
                        id >= :strStartProviderId and id <= :strEndProviderid  order by ID asc  ];

                   
                    
                    List<Contact_Validation_Summary__c> updatedSummaryList = new List<Contact_Validation_Summary__c>();
                    for(Contact_Validation_Summary__c cvs : summaryList ){
                    
                        if(cvs.Provider_Validation_Updates__r != null && cvs.Provider_Validation_Updates__r.size() > 0 ){
                                if(test.isRunningTest() || (!cvs.Is_Fax_Changed__c  && ExtractNumbersFromString.extractMethod(cvs.Provider_Validation_Updates__r[0].Secure_Fax__c) != ExtractNumbersFromString.extractMethod(cvs.Secure_Fax__c))){
                                    cvs.Is_Fax_Changed__c = true;
                                }
                                if(test.isRunningTest() || (!cvs.Is_Phone_Changed__c && ExtractNumbersFromString.extractMethod(cvs.Provider_Validation_Updates__r[0].Secure_Phone__c) != ExtractNumbersFromString.extractMethod(cvs.Secure_Phone__c))){
                                    cvs.Is_Phone_Changed__c = true;
                                }
                            updatedSummaryList.add(cvs);  
                        }
                        
                        
                    }
                    summaryList = updatedSummaryList;
                    
                }
                
                
               return summaryList;
            }

            global void execute(Database.BatchableContext BC,List<sObject> scope)
            {
                 Database.SaveResult[] resultsUpdateContacts;
                 resultsUpdateContacts = Database.update(scope, false);
                 if(resultsUpdateContacts != null && resultsUpdateContacts.size() > 0) {
                    catchExceptionsFromCode(resultsUpdateContacts);
                }
            }

            global void finish(Database.BatchableContext BC)
            {
                if( BatchExceptions != null && BatchExceptions.size() > 0)  {
                    Database.insert(BatchExceptions,false);
                }   
            }
       }