Sutter Health/src/objects/Contact_Script__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Resources for Customer Service Agents; step-by-step instructions to resolve inquiries</description>
    <label>Contact Script</label>
    <pluralLabel>Contact Scripts</pluralLabel>
</CustomObject>

Sutter Health/src/objects/SH_Home_Page_Headliner__c.object
<CustomObject>
    <fields>
        <fullName>SH_Is_Publish__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish</label>
        <type>Checkbox</type>
    </fields>
    <label>Home Page Headliner</label>
    <nameField>
        <displayFormat>HP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Page Headliners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/SH_ToggleWebServiceTest.cls
@isTest
private class SH_ToggleWebServiceTest 
{
    static testMethod void ValidateToggleWebService() 
    {
    	//Headliner data
		Contact_Script__kav objContactScript1 = SH_CommonTest.CreateArticleData('Nokia SMD Article', 'www-Nokia-com');
		SH_Home_Page_Headliner__c objHeadliner = SH_CommonTest.CreateHomePageHeadliner('Article Nokia', 'Description', 1, 'Article', true, true, String.valueOf(objContactScript1.KnowledgeArticleId).substring(0,15), '');
		
		SH_ToggleWebService.togglePublishChk(null, 'SH_Is_Publish__c', objHeadliner.Id);
		SH_ToggleWebService.togglePublishChk('SH_Homekjkj_Page_Headliner__c', 'SH_Is_Publish__c', objHeadliner.Id);
        SH_ToggleWebService.togglePublishChk('SH_Home_Page_Headliner__c', 'SH_Is_Publish__c', objHeadliner.Id);
    }
}