Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Provider_Active_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Provider Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Admin_Assistant_Email__c</fullName>
        <description>Used to capture admin assistant email</description>
        <label>Delegate Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Admin_Assistant_Email__c</fullName>
        <label>Delegate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Admin_Assistant_Phone__c</fullName>
        <label>Delegate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Admin_Assistant__c</fullName>
        <label>Delegate Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PDI_Campaign__c</fullName>
        <description>Used to indicate Campaign flag</description>
        <label>PDI Campaign</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Active_Status__c</fullName>
        <formula>Contact_Id__r.Provider_Active_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Active Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Admin_Emails_Are_Same__c</fullName>
        <description>PDI: True if Provider Email is the same as Delegate Email.</description>
        <formula>IF( Email__c == Admin_Assistant_Email__c , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>True if Provider Email is the same as Delegate Email.</inlineHelpText>
        <label>Provider Admin Emails Are Same</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status field created as part of REQ 3611 PDV Call Center</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Validated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Validation-Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/CS_ManageProfile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting containing Profile Names</description>
    <label>CS_ManageProfile</label>
</CustomObject>

Sutter Health/src/classes/BatchPDIAdminAssistantApprovalEmail_Test.cls
/*****************************************************
Class Name: BatchPDIAdminAssistantApprovalEmail_Test
Created By: Nagarjuna Kaipu
Created Date: 15/11/2016
Description: test class for BatchPDIAdminAssistantApprovalEmail class
******************************************************/
@isTest
public class BatchPDIAdminAssistantApprovalEmail_Test {
    static testmethod void PDIAdminAssistantApprovalEmailTest() {
        Contact c = Util01_PDIUtilTestData.createContact();
        User testUser = Util01_PDIUtilTestData.PDITestUser();
        System.runAs(testUser)
        {
            c.Provider_Admin_Assistant_Email__c = 'nagarjuna.kaipu@accenture.com';
            Test.startTest();
            insert c;
            List<CS_ManageProfile__c> mgrProfile = new List<CS_ManageProfile__c>();
            mgrProfile = Util01_PDIUtilTestData.createManageprofileSet();
            insert  mgrProfile;
        }
  
        BatchPDIAdminAssistantApprovalEmail emailBatch = new BatchPDIAdminAssistantApprovalEmail();
        emailBatch.query = 'SELECT Id, Contact_Id__c, Admin_Assistant__c, Admin_Assistant_Email__c, Admin_Assistant_Phone__c, Email__c,'
            +' PDI_Campaign__c, Provider_Active_Status__c, Status__c, Provider_Admin_Emails_Are_Same__c FROM Contact_Validation_Summary__c'
            +' WHERE Email__c != null' 
            +' AND Admin_Assistant_Email__c != null' 
            +' AND PDI_Campaign__c = \''+Label.CL176_PDI_Current_Campaign_Name+'\''
            +' AND Status__c != \''+Label.CL187_PDI_Validated_Status+'\' Limit 10000';
        Database.executeBatch(emailBatch, 1);
        List<Contact_Validation_Summary__c> sumList = new List<Contact_Validation_Summary__c>();
        //Querying the inserted summary record to check the assertion
        sumList = [SELECT Id, Contact_Id__c, Admin_Assistant__c, Admin_Assistant_Email__c, Admin_Assistant_Phone__c, Email__c, 
                   PDI_Campaign__c, Provider_Active_Status__c, Status__c, Provider_Admin_Emails_Are_Same__c FROM Contact_Validation_Summary__c 
                   Where Admin_Assistant_Email__c = 'nagarjuna.kaipu@accenture.com' Limit 1];
        System.assertEquals(sumList[0].Admin_Assistant_Email__c, 'nagarjuna.kaipu@accenture.com');
        Test.stopTest();
    }
}