Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>PDI_Campaign__c</fullName>
        <description>Used to indicate Campaign flag</description>
        <label>PDI Campaign</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone__c</fullName>
        <label>Primary Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/BatchUpdateDuplicateProvidersQueue_Test.cls
/**********************************************************************
Class Name   : BatchUpdateDuplicateProvidersQueue_Test
Date Created : 28/07/2016
Created By   : Kishore
Description  : Test class
Referenced/Used in : Used to test BatchUpdateDuplicateProvidersQueue
**********************************************************************/
@isTest
public class BatchUpdateDuplicateProvidersQueue_Test {
    
    static TestMethod void createSummaryTestRecords()
    {
        User testUser = Util01_PDIUtilTestData.PDITestUser();
        String queueId = null;
        System.runAs(testUser)
        {
            Group g1 = new Group(Name='PDIDuplicatePhoneNumberQueue', type='Queue');
            insert g1;
            QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Contact_Validation_Summary__c');
            insert q1;
            queueId = q1.Id;            
            List<Contact_Validation_Summary__c> summaryList = Util01_PDIUtilTestData.createDuplicatePhoneSummaryRecords();
        }
        Test.startTest();
        BatchUpdateDuplicateProvidersQueue summaryBatch = new BatchUpdateDuplicateProvidersQueue();
        Database.executeBatch(summaryBatch);
        Test.stopTest();
        List<Contact_Validation_Summary__c> updatedList = [SELECT Provider_Name__c, Owner.Name, OwnerId, Secure_Phone__c,
                                                           PDI_Campaign__c FROM Contact_Validation_Summary__c 
                                                           WHERE Secure_Phone__c =: '(565) 765-7688'];
        System.assertNotEquals(0, updatedList.size());
    }

}