Sutter Health/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Provider_ID__c</fullName>
        <label>Provider ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for provider contact records.</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Contact_Validation_Summary__c.object
<CustomObject>
    <description>PCRM Project Object</description>
    <fields>
        <fullName>Address_Modified__c</fullName>
        <label>Address Modified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Attn_To__c</fullName>
        <label>Attn To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Information Summaries</relationshipLabel>
        <relationshipName>Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Verified_Date__c</fullName>
        <label>Last Verified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Names_Changes_Suggested__c</fullName>
        <label>Names Changes Suggested</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_FullName__c</fullName>
        <formula>UPPER(Provider_FirstName__c +&apos; &apos;+ Provider_MiddleName__c +&apos;, &apos;+ Provider_LastName__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider FullName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_ID__c</fullName>
        <label>Provider ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_City__c</fullName>
        <label>Secure City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Fax__c</fullName>
        <label>Secure Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secure_Floor__c</fullName>
        <label>Secure Floor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone_Ext__c</fullName>
        <label>Secure Phone Ext</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Phone__c</fullName>
        <label>Primary Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secure_State__c</fullName>
        <label>Secure State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MP</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secure_Street_Address__c</fullName>
        <label>Secure Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Suite__c</fullName>
        <label>Secure Suite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure_Zip_Code__c</fullName>
        <label>Secure Zip Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Provider Information Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Information Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/ProviderValidationReport_New.cls
global class ProviderValidationReport_New implements Database.Batchable<sObject> {

    
     global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Address_Modified__c,Address_Type__c,Attn_To__c,Id,Contact_Id__r.LastName,Contact_Id__r.FirstName,LastModifiedBy.Name,Last_Verified_Date__c,Name,Names_Changes_Suggested__c,Provider_ID__c,Provider_Name__c,Provider_FullName__c,Secure_City__c,Secure_Fax__c,Secure_Floor__c,Secure_Phone_Ext__c,Secure_Phone__c,Secure_State__c,Secure_Street_Address__c,Secure_Suite__c,Secure_Zip_Code__c FROM Contact_Validation_Summary__c WHERE Last_Verified_Date__c = YESTERDAY and Address_Type__c = \'Secondary\' ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Contact_Validation_Summary__c> clist)
   {

string header = 'Provider ID, Provider Name , Secure Street Address, Secure Suite,Secure Floor,Secure City,Secure State,Secure Zip Code,Secure Phone,Secure Fax,Attn To,Names Changes Suggested,Last Modified By: Full Name,Last Verified date,Address Modified \n';
string finalstr = header ;
for(Contact_Validation_Summary__c a: clist)
{
     //  string FullName = (a.Contact_Id__r.LastName + ', '+a.Contact_Id__r.FirstName);
    //   FullName = FullName.toUpperCase();
       string recordString = '"'+a.Provider_ID__c+'","'+a.Provider_FullName__c+'","'+a.Secure_Street_Address__c+'","'+a.Secure_Suite__c+'","'+a.Secure_Floor__c+'","'+a.Secure_City__c+'","'+a.Secure_State__c+'","'+a.Secure_Zip_Code__c+'","'+a.Secure_Phone__c+'","'+a.Secure_Fax__c+'","'+a.Attn_To__c+'","'+a.Names_Changes_Suggested__c+'","'+a.LastModifiedBy.Name+'","'+a.Last_Verified_date__c +'","'+a.Address_Modified__c +'"\n';
       finalstr = finalstr +recordString;
}
OrgWideEmailAddress orgWideAddressId = [select id,Address from OrgWideEmailAddress where DisplayName='Sutter Provider Hub' limit 1];
Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
blob csvBlob = Blob.valueOf(finalstr);
string csvname= 'ProviderValidationReport.csv';
csvAttc.setFileName(csvname);
csvAttc.setBody(csvBlob);
Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
string temp = Label.ProviderReportEmailids;
List<String> emails= temp.split(',');
String[] toAddresses = new list<string> ();
toAddresses.addAll(emails);
String subject ='Provider Validation Report';
email.setSubject(subject);
email.setOrgWideEmailAddressId(orgWideAddressId.id);
email.setToAddresses( toAddresses );
email.setHtmlBody('Hi.<br/><br/> Please find attached Provider Validation Report. <br/><br/> Regards<br/>Sutter Provider Hub');
email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});

   }
   
global void finish(Database.BatchableContext BC)
    {
    }   
   

}