Sutter Health/src/objects/Custom_Benefit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Grid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan to Customize</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SHP_Benefit_Grid__c.Market_Segment__c</field>
                <operation>equals</operation>
                <value>Large Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SHP_Benefit_Grid__c</referenceTo>
        <relationshipLabel>Custom Benefit Plans</relationshipLabel>
        <relationshipName>Custom_Benefit_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inpatient__c</fullName>
        <label>Inpatient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Related_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Related to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Benefit Plans</relationshipLabel>
        <relationshipName>Custom_Benefit_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available for Sale - Approved</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Rejected by BPA Team</fullName>
                </value>
                <value>
                    <fullName>Soft Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected by Executive Group</fullName>
                </value>
                <value>
                    <fullName>Submitted to Executive Group</fullName>
                </value>
                <value>
                    <fullName>Pending with BPA Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Benefit Plan</label>
    <nameField>
        <label>Custom Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Benefit Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Grid_to_Metadata_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HR_Grid to Metadata Mapping</label>
</CustomObject>

Sutter Health/src/objects/SHP_Benefit_Grid__c.object
<CustomObject>
    <description>This Object is Used to capture the information related to Benefit Grid Data.</description>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved by DMHC - Available for Sale</fullName>
                </value>
                <value>
                    <fullName>Not Approved by DMHC - Not Available for Sale</fullName>
                </value>
                <value>
                    <fullName>Pending Approval by DMHC - Available for Sale</fullName>
                </value>
                <value>
                    <fullName>Pending Approval by DMHC - Not Available for Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/CreateBenefitPlanInMetadata_Test.cls
/* 
     Class Name: CreateBenefitPlanInMetadata_Test 
     Author: IDC Offshore
     Date: 06-Dec-2016
     Description: Test class for CreateBenefitPlanInMetadata Trigger.
*/
@isTest
private class CreateBenefitPlanInMetadata_Test {
	private static testMethod void testCustomBenefitPlanAproval(){  
        Test.StartTest();
        List<Grid_to_Metadata_Mapping__c> ls = Test.loadData(Grid_to_Metadata_Mapping__c.sObjectType, 'GridAPIMappingCSV');
        
        List<SHP_Benefit_Grid__c> SHPBenefitGrid = HighRoads_TestDataUtility.insertBenefitGrid();
        insert SHPBenefitGrid;
        
        Account acc = HighRoads_TestDataUtility.insertAccount();
        insert acc;
        
        Custom_Benefit_Plan__c cplan = new Custom_Benefit_Plan__c();
        cplan.Name = 'Test Custom Plan';
        cplan.Benefit_Grid__c = SHPBenefitGrid[0].id;
        cplan.Plan_Related_to_Account__c = acc.id;
        insert cplan;
        
        cplan.Plan_Status__c = 'Soft Approved';
        update cplan;
        
        cplan.Inpatient__c = '20$';
        update cplan;
        
        cplan.Plan_Status__c = 'Available for Sale - Approved';
        update cplan;
        
      	Test.StopTest();
    }
}