Sutter Health/src/objects/Document_Generation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Document Generation Requests</relationshipLabel>
        <relationshipName>Document_Generation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <label>Request Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Sign_Off__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold Sign Off</label>
        <referenceTo>Sold_Sign_Off__c</referenceTo>
        <relationshipLabel>Document Generation Requests</relationshipLabel>
        <relationshipName>Document_Generation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Before_Cancellation__c</fullName>
        <label>Status Before Cancellation</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Document Generation Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>Document Generation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Generation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Sold_Sign_Off__c.object
<CustomObject>
    <label>Sold Sign Off</label>
    <nameField>
        <displayFormat>SSO-{000000}</displayFormat>
        <label>Sold Sign Off  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sold Sign Offs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/HighRoads_DGRequestForCancellation.cls
/************************************************************************************************************************
Class Name : HighRoads_DGRequestForCancellation
Author     : IDC Offshore
Date       : 12/1/2016
Description: Req - 3980 This is used to restrict the user to cancel the document generation
History:
VERSION    AUTHOR              DATE        DETAIL
1.0        IDC-Offshore      12/1/2016     Req - 3980 This is used to restrict the user to cancel the document generation
2.0        Deloitte          19/04/2017    SHP29 Modified the if condition for BPA - Ability to Cancel DGR object when "Approved by Sales"
3.0        Deloitte          01/05/2017    Added a generic method(named cancelRequest) to handle the similar code used at multiple places
****************************************************************************************************************************/
global class HighRoads_DGRequestForCancellation {
    
    /**
* Method Name : cancelDocGenRequest
* Parameters  : ID recordId
* Description : To cancel/modify the request
* Req no      : 3980
* Return type : String - success or failure message
**/
    webservice static String cancelDocGenRequest(ID recordId){
        Savepoint sp = Database.setSavepoint();
        try{
            //fetching the admin queue
            Group grp = [select id from group where developername=:HighRoads_Constants.BPA_ADMIN_QUEUE  and type=:HighRoads_Constants.QUEUE limit 1];
            //fetching the sales profile name
            String profileName = [select Name from Profile where id=:UserInfo.getProfileId() LIMIT 1].Name;
            //fetching the sso and opportunity values and new and old status
            Document_Generation_Request__c docgenObj = [select Id,OwnerId,Sold_Sign_Off__c,Opportunity__c,Request_Status__c,Status_Before_Cancellation__c
                                                        from Document_Generation_Request__c where Id=:recordId LIMIT 1];
            
           
            //if sold sign off is not null then it is large group
            //  SHP29: Added "SHP Benefit Plan Administration" Profile to the below IF condition so that Users of this profile get DGR Cancellation access                                                        
            if((docgenObj.Sold_Sign_Off__c != NULL || (docgenObj.Sold_Sign_Off__c == NULL && docgenObj.Opportunity__c != NULL)) && ((profileName == HighRoads_Constants.SHP_SALES_PROFILE && docgenObj.OwnerId == grp.Id) || UserInfo.getUserId() == docgenObj.OwnerId || profileName == HighRoads_Constants.SHP_Benefit_Plan_Administration)){
                if(docgenObj.Sold_Sign_Off__c != NULL) {
                    cancelRequest(docgenObj.Sold_Sign_Off__c, 'Sold_Sign_Off__c', docgenObj);
                }
                else {
                    cancelRequest(docgenObj.Opportunity__c, 'Opportunity', docgenObj);
                }
                return System.Label.HR223_RequestCancelSuccess;
            }
            else{
                return System.Label.HR222_RequestCancellationError;      
            }
        }catch(Exception ex){Database.rollback(sp); System.debug(ex.getTypeName() + HighRoads_Constants.HYPHEN + ex.getCause() + HighRoads_Constants.COLON + ex.getMessage());}return System.Label.HR224_ErrorOccurredInCancelRequest;
    }
    /*
        Method Name        :    cancelRequest
        Description        :    Updates the "Request Status" field value of Doc Gen req. record to "Request Cancelled"
        Return Type        :    void
        Param count        :    3
        Parameters         :    recId         ==> Parent recordId of Doc gen Req.(could be either of SSO Id and Opportunity Id)
                                ObjectName    ==> sObject Type of the Parent (Ex: Sold_Sign_Off__c, if SSO)
                                docGenObj     ==> Doc Gen Req record, which is cancelled        
    */
    //    SHP29: This method is used to update the Status on the Document Generation Request object to "Cancelled"
    static void cancelRequest(Id recId, String ObjectName, Document_Generation_Request__c docGenObj) {
        
       if (docGenObj.Request_Status__c == System.Label.HR221_RequestCancelled){ 
            docGenObj.Request_Status__c = docGenObj.Status_Before_Cancellation__c; 
        } 
        else { 
            docGenObj.Status_Before_Cancellation__c = docGenObj.Request_Status__c; 
            docGenObj.Request_Status__c = System.Label.HR221_RequestCancelled; 
        } 
     // The status on the DGR is updated to Cancelled 
        update docGenObj;
 
    }
    
}