Sutter Health/src/objects/Incumbent_Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Incumbent_Carrier__c</fullName>
        <description>Req 3389</description>
        <label>Incumbent Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AETNA</fullName>
                </value>
                <value>
                    <fullName>ANTHEM</fullName>
                </value>
                <value>
                    <fullName>BLUE SHIELD</fullName>
                </value>
                <value>
                    <fullName>CAL CHOICE</fullName>
                </value>
                <value>
                    <fullName>CALPERS</fullName>
                </value>
                <value>
                    <fullName>CHINESE COMMUNITY HEALTH PLAN</fullName>
                </value>
                <value>
                    <fullName>CIGNA</fullName>
                </value>
                <value>
                    <fullName>HEALTH NET</fullName>
                </value>
                <value>
                    <fullName>SELF FUNDED</fullName>
                </value>
                <value>
                    <fullName>UNITED</fullName>
                </value>
                <value>
                    <fullName>WHA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>KAISER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RFP Form/Incumbent Carrier</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Incumbent Carrier No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFP Form/Incumbent Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/SHMMN_Incumbent_Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>SHMMN Employer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SHMMN Incumbent Carrier</relationshipLabel>
        <relationshipName>SHMMN_Incumbent_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contain__c</fullName>
        <label>%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Incumbent_Carrier__c</fullName>
        <label>Incumbent Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aetna</fullName>
                </value>
                <value>
                    <fullName>Anthem</fullName>
                </value>
                <value>
                    <fullName>Blue Shield</fullName>
                </value>
                <value>
                    <fullName>Cal Choice</fullName>
                </value>
                <value>
                    <fullName>Calpers</fullName>
                </value>
                <value>
                    <fullName>Chinese Community Health Plan</fullName>
                </value>
                <value>
                    <fullName>Cigna</fullName>
                </value>
                <value>
                    <fullName>Health Net</fullName>
                </value>
                <value>
                    <fullName>Kaiser</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Self Funded</fullName>
                </value>
                <value>
                    <fullName>Shp</fullName>
                </value>
                <value>
                    <fullName>United Health Care</fullName>
                </value>
                <value>
                    <fullName>Wha</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Product__c</fullName>
        <label>Sub Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>HSA</fullName>
                </value>
                <value>
                    <fullName>Indemnity</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SHMMN Incumbent Carrier</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>SHMMN Incumbent Carrier Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHMMN Incumbent Carrier</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/SHMMN_SHMMNIncumebnt_Test.cls
/**********************************************************************
  Name: SHMMN_SHMMNIncumebnt_Test
  Copyright © 2015 IDC Offshore
  ======================================================
  ======================================================
  Purpose:
  This is the test class for SHMMN_SHMMNIncumebnt class            
  ======================================================
  ======================================================
  History
  -------
  VERSION  AUTHOR        DATE        DETAIL                 Description
  1.0      IDC Offshore  05/03/2015 Development complete   This class is defined to test functionality of SHMMN_SHMMNIncumebntd class.  
  ***********************************************************************/
  /*******************************************************************
    Purpose: method to create test data used by all test methods
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/
@isTest
Private class SHMMN_SHMMNIncumebnt_Test 
{
  Static Void createTestData()
  {
        Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordTypeId = recType;
        insert acc;
        System.assert(acc.id!=null);
        SHMMN_Incumbent_Carrier__c inc = new SHMMN_Incumbent_Carrier__c();
        inc.Incumbent_Carrier__c = 'AETNA';
        inc.Sub_Product__c = 'EPO';
        inc.Account__c = acc.id;
        insert inc; 
        System.assert(inc.id!=null);
  }
/*******************************************************************
    Purpose: method to check positive scenario of SHMMN Incumbent Carrier save
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/  
  static testmethod void saveSHMMNInc_Test()
  {
     Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     //Assert to test account is inserted
     System.assert(tempAcc!=null);
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Incumbent_Carrier__c = 'AETNA';
     tempInc.Sub_Product__c = 'EPO';
     tempInc.Account__c = tempAcc.id;
     insert tempInc;
     //Assert to test SHMMN Incumbent Carrier record is inserted
     System.assert(tempInc!=null);
     ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(tempInc);
     Apexpages.currentpage().getparameters().put('id' , tempInc.id);
     SHMMN_SHMMNIncumebnt vfc = new SHMMN_SHMMNIncumebnt (controller); 
     Test.startTest();
     vfc.saveIncumbentCarriers();
     vfc.decreaseList();
     vfc.increaseList();
     Test.stopTest();
  }
  /*******************************************************************
    Purpose: method to check negative scenario of SHMMN Incumbent Carrier save where % is greater than 100
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/ 
  static testmethod void saveSHMMNIncSum_Test()
  {
     Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     //Assert to test account is inserted
     System.assert(tempAcc!=null);
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Incumbent_Carrier__c = 'AETNA';
     tempInc.Sub_Product__c = 'EPO';
     tempInc.Account__c = tempAcc.id;
     tempInc.Contain__c = 120;
     insert tempInc;     
     ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(tempInc);
     Apexpages.currentpage().getparameters().put('id' , tempInc.id);
     SHMMN_SHMMNIncumebnt vfc = new SHMMN_SHMMNIncumebnt (controller); 
     Test.startTest();
     vfc.saveIncumbentCarriers();
     //Assert to test SHMMN Incumbent Carrier record is not inserted
     System.assert(Apexpages.hasMessages(),true);
     vfc.decreaseList();
     vfc.increaseList();
     Test.stopTest();
  }
 /*******************************************************************
    Purpose: method to check negative scenario of duplicate check for SHMMN Incumbent Carrier
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/  
  static testmethod void saveSHMMNIncDup_Test()
  {
     Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     //Assert to test account is inserted
     System.assert(tempAcc!=null);
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Incumbent_Carrier__c = 'AETNA';
     tempInc.Sub_Product__c = 'EPO';
     tempInc.Account__c = tempAcc.id;
     tempInc.Contain__c = 120;
     insert tempInc;
     //Assert to test SHMMN Incumbent Carrier record is inserted
     System.assert(tempInc!=null);
     SHMMN_Incumbent_Carrier__c tempSMInc = new SHMMN_Incumbent_Carrier__c();
     tempSMInc.Incumbent_Carrier__c = 'AETNA';
     tempSMInc.Sub_Product__c = 'EPO';
     tempSMInc.Account__c = tempAcc.id;
     tempSMInc.Contain__c = 120;
     insert tempSMInc;

     ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(tempInc);
     Apexpages.currentpage().getparameters().put('id' , tempInc.id);
     SHMMN_SHMMNIncumebnt vfc = new SHMMN_SHMMNIncumebnt (controller); 
     Test.startTest();
     vfc.saveIncumbentCarriers();
     //Assert to test SHMMN Incumbent Carrier record is not inserted
     System.assert(Apexpages.hasMessages(),true);
     vfc.decreaseList();
     vfc.increaseList();
     Test.stopTest();
  }
/*******************************************************************
    Purpose: method to check multiple incumbent carrier from page
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/ 
  static testmethod void saveSHMMNIncMultiple_Test()
  {
     
     Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     //Assert to test account is inserted
     System.assert(tempAcc!=null);    
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Incumbent_Carrier__c = 'AETNA';
     tempInc.Sub_Product__c = 'EPO';
     tempInc.Account__c = tempAcc.id;    
     insert tempInc;
     //Assert to test SHMMN Incumbent Carrier record is inserted
     System.assert(tempInc!=null);
     SHMMN_Incumbent_Carrier__c tempSMInc = new SHMMN_Incumbent_Carrier__c();
     tempSMInc.Incumbent_Carrier__c = 'AETNA';
     tempSMInc.Sub_Product__c = 'PPO';
     tempSMInc.Account__c = tempAcc.id;
     insert tempSMInc;
     //Assert to test SHMMN Incumbent Carrier record is inserted
     System.assert(tempSMInc!=null);
     SHMMN_Incumbent_Carrier__c tempSMInc1 = new SHMMN_Incumbent_Carrier__c();
     tempSMInc1.Incumbent_Carrier__c = 'AETNA';
     tempSMInc1.Sub_Product__c = 'POS';
     tempSMInc1.Account__c = tempAcc.id;
     insert tempSMInc1;
     //Assert to test SHMMN Incumbent Carrier record is inserted
     System.assert(tempSMInc1!=null);
     ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(tempInc);
     Apexpages.currentpage().getparameters().put('id' , tempInc.id);
     SHMMN_SHMMNIncumebnt vfc = new SHMMN_SHMMNIncumebnt (controller);
     Test.startTest();
     vfc.increaseList();
     vfc.decreaseList();
     Test.stopTest();
     
  }
  /*******************************************************************
    Purpose: method to check wrapper class for Incumbent Carrier
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/ 
  static testmethod void saveSHMMNWrapper_Test()
  {
     try
     {
     Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     //Assert to test account is inserted
     System.assert(tempAcc!=null);     
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Incumbent_Carrier__c = 'AETNA';
     tempInc.Sub_Product__c = 'EPO';  
     insert tempInc;
     //Assert to test SHMMN Incumbent Carrier record is inserted
     System.assert(tempInc!=null);
     Test.startTest();
     SHMMN_SHMMNIncumebnt.incumbentWrapper incWrapper1 = new SHMMN_SHMMNIncumebnt.incumbentWrapper(tempAcc);  
     tempInc.Account__c = tempAcc.id;    
     update tempInc;
     SHMMN_Incumbent_Carrier__c tempSMInc = new SHMMN_Incumbent_Carrier__c();
     tempSMInc.Incumbent_Carrier__c = 'AETNA';
    // tempSMInc.Sub_Product__c = 'PPO';
     tempSMInc.Account__c = tempAcc.id;
     insert tempSMInc;
     SHMMN_SHMMNIncumebnt.incumbentWrapper incWrapper = new SHMMN_SHMMNIncumebnt.incumbentWrapper(tempAcc,tempSMInc); 
     ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(tempInc);
     Apexpages.currentpage().getparameters().put('id' , tempInc.id);
     SHMMN_SHMMNIncumebnt vfc = new SHMMN_SHMMNIncumebnt (controller);
     
     vfc.increaseList();
     vfc.decreaseList();
     vfc.saveIncumbentCarriers();
     Test.stopTest();
     }
     catch(exception e)
     {
        System.assert(e.getMessage() != null); 
     }
     
  }
 /*******************************************************************
    Purpose: method to create list of Incumbent carrier if there is no existing Incumbent on the selected account
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/  
   static testmethod void saveSHMMNWrapperWithNoINC_Test()
  {
     try
     {
      Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Account__c = tempAcc.id;
     ApexPages.StandardController  controller = new ApexPages.StandardController(tempInc );
     SHMMN_SHMMNIncumebnt   vfc = new SHMMN_SHMMNIncumebnt (controller);
     
     }
     catch(exception e)
     {
        System.assert(e.getMessage() != null); 
     }
     
  }
  
  /*******************************************************************
    Purpose: method to create list of Incumbent carrier if there is no existing Incumbent on the selected account
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/  
   static testmethod void saveSHMMNWrapperWithNoINC_Test1()
  {
     try
     {
      Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Account__c = tempAcc.id;
     ApexPages.StandardController  controller = new ApexPages.StandardController(tempInc );
     SHMMN_SHMMNIncumebnt   vfc = new SHMMN_SHMMNIncumebnt (controller);
     vfc.increaseList();
     vfc.decreaseList();
     vfc.saveIncumbentCarriers();
     }
     catch(exception e)
     {
        System.assert(e.getMessage() != null); 
     }
     
  }
  
  /*******************************************************************
    Purpose: method to create list of Incumbent carrier if there is one existing Incumbent on the selected account
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/  
   static testmethod void saveSHMMNWrapperWithINC_Test1()
  {
     try
     {
      Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SHMMN Employer').getRecordTypeId();
     Account tempAcc = new Account();
     tempAcc.Name = 'Test Account 1';
     tempAcc.RecordTypeId = recType;
     insert tempAcc;
     SHMMN_Incumbent_Carrier__c tempInc = new SHMMN_Incumbent_Carrier__c();
     tempInc.Account__c = tempAcc.id;
     insert tempInc;
     ApexPages.StandardController  controller = new ApexPages.StandardController(tempInc );
     SHMMN_SHMMNIncumebnt   vfc = new SHMMN_SHMMNIncumebnt (controller);
     vfc.saveIncumbentCarriers();
     }
     catch(exception e)
     {
        System.assert(e.getMessage() != null); 
     }
     
  } 
}