Sutter Health/src/objects/Incumbent_Carrier__c.object
<CustomObject>
    <fields>
        <fullName>Incumbent_Carrier__c</fullName>
        <description>Req 3389</description>
        <label>Incumbent Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AETNA</fullName>
                </value>
                <value>
                    <fullName>ANTHEM</fullName>
                </value>
                <value>
                    <fullName>BLUE SHIELD</fullName>
                </value>
                <value>
                    <fullName>CAL CHOICE</fullName>
                </value>
                <value>
                    <fullName>CALPERS</fullName>
                </value>
                <value>
                    <fullName>CHINESE COMMUNITY HEALTH PLAN</fullName>
                </value>
                <value>
                    <fullName>CIGNA</fullName>
                </value>
                <value>
                    <fullName>HEALTH NET</fullName>
                </value>
                <value>
                    <fullName>SELF FUNDED</fullName>
                </value>
                <value>
                    <fullName>UNITED</fullName>
                </value>
                <value>
                    <fullName>WHA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>KAISER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Child_Record_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Child Record Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_of_Quotes_Requested__c</fullName>
        <label># of Quotes Requested</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RFP Form/Incumbent Carriers</relationshipLabel>
        <relationshipName>Incumbent_Carriers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Market_Check__c</fullName>
        <defaultValue>&quot;Renewal&quot;</defaultValue>
        <label>Reason for Market Check</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Instuctions__c</fullName>
        <label>Special Instuctions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted to Underwriting</fullName>
                </value>
                <value>
                    <fullName>Approved by Underwriting</fullName>
                </value>
                <value>
                    <fullName>Rejected by Underwriting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategy_Statement__c</fullName>
        <label>Strategy Statement</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tiered_Rates__c</fullName>
        <label>Tiered Rates</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RFP Form/Incumbent Carrier</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Incumbent Carrier No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFP Form/Incumbent Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Is_Child_Record_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Child Record Created?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/RFP_IncumbentCarrierTriggerHelper.cls
/**
 * Class Name  : RFP_IncumbentCarrierTriggerHelper
 * Description : 1 To create/update the Benefit Plan Association with RFP Form details
 * 				 2.To create a quote on RFP approval.
 * 				 3.To check the mandatory fields before submitting for approval 
 * Created By  : IDC offshore
 * Created Date : 12/8/2016
 **/
public class RFP_IncumbentCarrierTriggerHelper {
	public static boolean isAfterInsert = true;
    public static boolean isAfterUpdate = true;
    public static boolean isBeforeUpdate = true;
    /**
     * Method Name : copyPlansToProposal
     * Description : 1. Copy the plans from Opportunity while creating 
					 2. Updating the opportunity when rfp is created.
     * Parameters  : List<Incumbent_Carrier__c> newList
     * Return type : void
     * 
     **/
    public void copyPlansToProposal(List<Incumbent_Carrier__c> newList){
        Map<ID,ID> oppRFPMap = new Map<ID,ID>();
        List<Opportunity> rfpCreatedOppList = new List<Opportunity>();
        Id rfpRecordTypeId = Schema.SObjectType.Incumbent_Carrier__c.getRecordTypeInfosByName().get(System.Label.HR21_RFPFormRecordType).getRecordTypeId();
        for(Incumbent_Carrier__c rfp : newList){
            if(rfp.recordTypeId == rfpRecordTypeId){
                oppRFPMap.put(rfp.Opportunity__c,rfp.id);
                Opportunity opp = new Opportunity(id=rfp.Opportunity__c);
                opp.Is_Child_Record_Created__c = true;
                rfpCreatedOppList.add(opp);
            }
        }
        if(!oppRFPMap.isEmpty() && HighRoads_CopyOppPlansToRFPANDSCN.isRFPAfterInsert){
            HighRoads_CopyOppPlansToRFPANDSCN rfp = new HighRoads_CopyOppPlansToRFPANDSCN();
            rfp.copyOppPlansToRFP(oppRFPMap);
            HighRoads_CopyOppPlansToRFPANDSCN.isRFPAfterInsert = false;
        }
        
        if(rfpCreatedOppList != NULL && !rfpCreatedOppList.isEmpty()){
            Update rfpCreatedOppList;
        }
    }
    /**
     * Method Name : checkMandatoryFieldsforApproval
     * Description : 1. Check the mandatory fields while submitting for approval 
       				 2. Updating is child record creation field when rfp is approved.
     * Parameters  : Map<ID,Incumbent_Carrier__c> newMap,Map<ID,Incumbent_Carrier__c> oldMap
     * Return type : void
     * 
     **/
    public void checkMandatoryFieldsforApproval(Map<ID,Incumbent_Carrier__c> newMap,Map<ID,Incumbent_Carrier__c> oldMap){
        Id rfpRecordTypeId = Schema.SObjectType.Incumbent_Carrier__c.getRecordTypeInfosByName().get(System.Label.HR21_RFPFormRecordType).getRecordTypeId();
        for(Incumbent_Carrier__c rfp : newMap.values()){
            if(rfp.recordTypeId == rfpRecordTypeId && oldMap.get(rfp.id).Stage__c != newMap.get(rfp.id).Stage__c &&
               rfp.Stage__c.equalsIgnoreCase(System.Label.HR75_ApprovedbyUnderwriting)){
                   rfp.Is_Child_Record_Created__c = true;
               }
            if(rfp.recordTypeId == rfpRecordTypeId && oldMap.get(rfp.id).Stage__c != newMap.get(rfp.id).Stage__c &&
               rfp.Stage__c.equalsIgnoreCase(System.Label.HR85_Submitted_to_Underwriting)){
                   if( String.isBlank(String.valueOf(rfp.No_of_Quotes_Requested__c) )){
                       rfp.addError(System.Label.HR183_NoOfQuotesMandatory);
                   }else if(String.isBlank(rfp.Reason_for_Market_Check__c )){
                       rfp.addError(System.Label.HR184_ReasonForMarketMandatory);
                       
                   }else if(String.isBlank(rfp.Tiered_Rates__c)){
                       rfp.addError(System.Label.HR185_TieredRatesMandatory);
                      
                   }else if(String.isBlank(rfp.Strategy_Statement__c)){
                       rfp.addError(System.Label.HR186_StrategyStatementMandatory);
                      
                   }else if(String.isBlank(rfp.Special_Instuctions__c)){
                       rfp.addError(System.Label.HR187_SepcialInstructionsMandatory);
                   } 
            }
        }
    }
    /**
     * Method Name : createProposalOnApproval
     * Description : 1. To create quote on approval of RFP 
	 *				 2. Calling helper method to create Proposal on approval of RFP
     * Parameters  : Map<ID,Incumbent_Carrier__c> newMap,Map<ID,Incumbent_Carrier__c> oldMap
     * Return type : void
     * 
     **/
    public void createProposalOnApproval(Map<ID,Incumbent_Carrier__c> newMap,Map<ID,Incumbent_Carrier__c> oldMap){
        Id rfpRecordTypeId = Schema.SObjectType.Incumbent_Carrier__c.getRecordTypeInfosByName().get(System.Label.HR21_RFPFormRecordType).getRecordTypeId();
        Set<ID> rfpIds = new Set<ID>();
        for(Incumbent_Carrier__c rfp : newMap.values()){
            if(rfp.recordTypeId == rfpRecordTypeId && oldMap.get(rfp.id).Stage__c != newMap.get(rfp.id).Stage__c &&
               rfp.Stage__c.equalsIgnoreCase(System.Label.HR75_ApprovedbyUnderwriting)){
                   rfpIds.add(rfp.Id);
               }     
        }
        if(!rfpIds.isEmpty()){
            HighRoads_AutoCreateRecordsOnApproval createQuoteObj = new HighRoads_AutoCreateRecordsOnApproval();
            createQuoteObj.createQuote(rfpIds);
        }
    }
}