Sutter Health/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Additional_Buy_Ups__c</fullName>
        <description>Req-3358</description>
        <label>Proposal Scenario</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TR</fullName>
                </value>
                <value>
                    <fullName>Slice</fullName>
                </value>
                <value>
                    <fullName>Triple Option</fullName>
                </value>
                <value>
                    <fullName>TR &amp; Slice</fullName>
                </value>
                <value>
                    <fullName>Slice &amp; Triple Option</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Child_Record_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Child Record Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NTE_Offered__c</fullName>
        <label>NTE Offered %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan_Effective_Date__c</fullName>
        <label>Plan Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RFP_Due_Date__c</fullName>
        <label>RFP Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Subscribers__c</fullName>
        <label># of Subscribers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Is_Child_Record_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Child Record Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <formula>Text(RFP_Form__r.Opportunity__r.StageName)</formula>
        <label>Opportunity Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFP_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>RFP Form</label>
        <referenceTo>Incumbent_Carrier__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted to Sales</fullName>
                </value>
                <value>
                    <fullName>Approved by Sales</fullName>
                </value>
                <value>
                    <fullName>Rejected by Sales</fullName>
                </value>
                <value>
                    <fullName>Pending Actuarial Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/HighRoads_ProposalTriggerHelper.cls
/**
 * Class Name  : HighRoads_ProposalTriggerHelper
 * Description : 1. To create a Sold Sign Off on Proposal approval.
 *               2. To check the mandatory fields before approving the Proposal these fields are required while creating the Sold Sign Off.
 *               3. To check the atleast one attachment exists for the Proposal before submtting for approval
 *               4. To Create one more proposal if the existing proposal is rejected.
 * Created Date: 12/8/2016
 * Created By  : IDC offshore
 **/
public class HighRoads_ProposalTriggerHelper {
    //to avoid recursion
    public static boolean isBeforeUpdate = true;
    public static boolean isAfterUpdate = true;
    /**
     * Method Name : checkMandatoryBeforeSubmit
     * Description : To check the mandatory fields before approving the Proposal these fields are required while creating the Sold Sign Off.
     *               To check the atleast one attachment exists for the Proposal before submtting for approval
     *               To Create one more proposal if the existing proposal is rejected.
     *               To create a Sold Sign Off on Proposal approval.
     * Parameters  : Map<ID,Proposal__c> newMap,Map<ID,Proposal__c> oldMap
     * Return type : void
     **/
    public void checkMandatoryBeforeSubmit(Map<ID,Proposal__c> newMap,Map<ID,Proposal__c> oldMap){
        Set<ID> submittedQuotes = new Set<ID>();
        Map<ID,ID> attachmentQuoteMap = new Map<ID,ID>();
        Set<ID> rejectedQuoteRFPIds = new Set<ID>();
        Set<ID> approvedQuoteIds = new Set<ID>();
        //Fecting all the attachments for the proposals
        for(Attachment attObj : [select id,ParentId from Attachment where ParentId IN :newMap.keySet()]){
            attachmentQuoteMap.put(attObj.ParentId, attObj.Id);
        }
        
        for(Proposal__c quote : newMap.Values()){
            if(oldMap.get(quote.id).Stage__c != newMap.get(quote.id).Stage__c &&
               quote.Stage__c.equalsIgnoreCase(System.Label.HR76_ApprovedbySales)){
                   if(quote.Opportunity_Stage__c == System.Label.CL_35_SM_ClosedWon){
                       approvedQuoteIds.add(quote.Id);
                   }else{
                       quote.addError(System.Label.HR189_OppClosedWonORNot);
                   }
                   quote.Is_Child_Record_Created__c = true;
               }else if(oldMap.get(quote.id).Stage__c != newMap.get(quote.id).Stage__c &&
               quote.Stage__c.equalsIgnoreCase(System.Label.HR213_SubmittedtoSales)){
                   //If there no attachment for the proposal, throwing error message to add the attachmetns
                   if(attachmentQuoteMap.get(quote.Id) == NULL){
                       newMap.get(quote.Id).addError(System.Label.HR214_QuoteAttachmentMandatoryBeforeSubmitting);
                   }
               }else if(oldMap.get(quote.id).Stage__c != newMap.get(quote.id).Stage__c &&
                        quote.Stage__c.equalsIgnoreCase(System.Label.HR191_RejectedBySales)){
                            rejectedQuoteRFPIds.add(quote.RFP_Form__c);
                }
        }
        
        for(Proposal__c quote : [select ID,Opportunity_ID__r.RFP_Due_Date__c,Opportunity_ID__r.of_Subscribers__c , 
                                 Opportunity_ID__r.Additional_Buy_Ups__c , Opportunity_ID__r.Plan_Effective_Date__c ,
                                 Opportunity_ID__r.NTE_Offered__c,Stage__c from Proposal__c where id IN:newMap.keySet() ]){
                                     if(quote.Opportunity_ID__r.RFP_Due_Date__c == NULL){
                                         newMap.get(quote.Id).addError(System.Label.HR206_RFPDueDateMandatory);
                                     }else if(quote.Opportunity_ID__r.of_Subscribers__c == NULL){
                                         newMap.get(quote.Id).addError(System.Label.HR205_NoOfSubscribersMandatory,false);
                                     }else if(quote.Opportunity_ID__r.Additional_Buy_Ups__c == NULL){
                                         newMap.get(quote.Id).addError(System.Label.HR207_ProposalScenarioMandatory);
                                     }else if(quote.Opportunity_ID__r.Plan_Effective_Date__c == NULL){
                                         newMap.get(quote.Id).addError(System.Label.HR208_PlanEffectiveDateMandatory);
                                     }
                                     //else if(quote.Opportunity_ID__r.NTE_Offered__c == NULL){
                                       //  newMap.get(quote.Id).addError(System.Label.HR209_NTEOfferedMandatory);
                                     //}
        }
        //To create a Sold Sign Off on Proposal approval.
        if(!approvedQuoteIds.isEmpty() && HighRoads_AutoCreateRecordsOnApproval.isQuoteAfterUpdate){
            HighRoads_AutoCreateRecordsOnApproval createSSOObj = new HighRoads_AutoCreateRecordsOnApproval();
            createSSOObj.createSSO(approvedQuoteIds);
            HighRoads_AutoCreateRecordsOnApproval.isQuoteAfterUpdate = false;
        }
        //To Create one more proposal if the existing proposal is rejected.
        if(!rejectedQuoteRFPIds.isEmpty() && HighRoads_AutoCreateRecordsOnApproval.isQuoteAfterUpdateRejected){
            HighRoads_AutoCreateRecordsOnApproval createQuoteObj = new HighRoads_AutoCreateRecordsOnApproval();
            createQuoteObj.createQuote(rejectedQuoteRFPIds);
            HighRoads_AutoCreateRecordsOnApproval.isQuoteAfterUpdateRejected = false;
        }
    }
}