Sutter Health/src/objects/PDV_EAF_Facility__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>EAF Facilities</relationshipLabel>
        <relationshipName>EAF_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EAF Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAF Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/PDV_EAF_Validation_Audit_Trail__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>EAF Validation Audit Trails</relationshipLabel>
        <relationshipName>EAF_Validation_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EAF_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EAF Facility</label>
        <referenceTo>PDV_EAF_Facility__c</referenceTo>
        <relationshipLabel>EAF Validation Audit Trails</relationshipLabel>
        <relationshipName>EAF_Validation_Audit_Trails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EAF Validation Audit Trail</label>
    <nameField>
        <label>EAF Validation Audit Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EAF Validation Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/PDIEAFCaseDetailController_Test.cls
/*****************************************************
Class Name: PDIEAFCaseDetailController_Test
Created By: Nagarjuna Kaipu
Created Date: 15/11/2016
Description: test class for PDIEAFCaseDetailController class
******************************************************/
@isTest
public class PDIEAFCaseDetailController_Test {
    //Merhod to test the case insertion along with address log history
    static testmethod void test_Facility_Case_Detail() {
        User socUser = Util01_PDIUtilTestData.createSOCUser();
        User PDIUser = Util01_PDIUtilTestData.PDITestUser2();
        PDV_EAF_Facility__c eafFac = Util01_PDIUtilTestData.createEAFFacility();
        PDV_EAF_Validation_Audit_Trail__c eafAudit = Util01_PDIUtilTestData.createEAFAudit();
        Case eafCase =  Util01_PDIUtilTestData.facilityInquiryCase();
        Test.startTest();
        System.runAs(PDIUser){
            insert eafCase;
            eafFac.Case__c = eafCase.Id;
            insert eafFac;
            eafAudit.EAF_Facility__c = eafFac.Id;
            eafAudit.Case__c = eafCase.Id;
            insert eafAudit;
            PageReference pageRef = Page.PDIEAFCaseDetail;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('caseId', eafCase.id);
            PDIEAFCaseDetailController objCtlr = new PDIEAFCaseDetailController();
            //Checking audit history insertion related to case
            system.assertEquals(objCtlr.auditChangeHistory.size()>0, true);
        }
        Test.stopTest();
    }
}