Sutter Health/src/objects/Potential_Quality_Issue__c.object
<CustomObject>
    <description>Req-3369</description>
    <fields>
        <fullName>Access_Availability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Access / Availability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Admit_within_3_days_of_ER__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admit within 3 days of ER</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assessment_Treatment_Diagnosis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assessment/Treatment/Diagnosis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ByPass_CMO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Bypasses CMO Approval</description>
        <label>Bypass CMO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PQI_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>UM Review</fullName>
                </value>
                <value>
                    <fullName>MD Review</fullName>
                </value>
                <value>
                    <fullName>PRC Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>UM Rejected</fullName>
                </value>
                <value>
                    <fullName>MD Approved</fullName>
                </value>
                <value>
                    <fullName>MD Rejected</fullName>
                </value>
                <value>
                    <fullName>PRC Approved</fullName>
                </value>
                <value>
                    <fullName>PRC</fullName>
                </value>
                <value>
                    <fullName>UM Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_PQI_Indicators__c</fullName>
        <description>To store the Labels of The PQI Indicators Selected</description>
        <label>Selected PQI Indicators</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Potential Quality Issue</label>
    <nameField>
        <displayFormat>PQI-{0000000000}</displayFormat>
        <label>PQI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Quality Issue</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sutter Health/src/classes/populateSelectedPQIIndicators_Test.cls
/**  
*     Class Name: populateSelectedPQIIndicators_Test
*     Author: IDC Offshore
*     Date: 07-Augast-2014
*     Project Name: CRM - SFT - Sutter Health
*     Description: This test insert the PQI records and checks for the PQI indicators are properly Populted.
*     
*    History
*    --------
*
*    VERSION    AUTHOR         DATE        DETAIL 
*       
**/
@isTest
public class populateSelectedPQIIndicators_Test {
    Public Static Final String ERRMSG = 'Cannot update the record without assigning it to yourself from the queue';
    
    
    /**    
    *@author IDC Team    
    *@date 07/08/2015    
    *@description This Test Method is used to check the the Value Set for the Selected PQI Indicators by trigger is correct.
    *@param     
    *@return     
    */
    static testMethod void  testSelectedPQI() {
        List<Potential_Quality_Issue__c> pqiListToInsert = new List<Potential_Quality_Issue__c>();
        List<Potential_Quality_Issue__c> pqiListExtracted = new List<Potential_Quality_Issue__c>();
        
        for (Integer i = 0; i<100;i++ ) {
            Potential_Quality_Issue__c pqi = new Potential_Quality_Issue__c( Access_Availability__c = true ,
                                                                         Admit_within_3_days_of_ER__c = true,
                                                                         ByPass_CMO__c = false,
                                                                         Assessment_Treatment_Diagnosis__c= true
                                                                        );
            pqiListToInsert.add(pqi);
        }
        
        Test.startTest();
        Database.insert(pqiListToInsert);
        Test.stopTest();
        
        pqiListExtracted = [SELECT Id, Name , Selected_PQI_Indicators__c FROM Potential_Quality_Issue__c WHERE ID IN:pqiListToInsert ];
        
        
        for( Integer i=0;i<100;i++) {
            String indicatorValues = pqiListExtracted[i].Selected_PQI_Indicators__c;
            System.debug('@@SUSH@@'+indicatorValues+'@@@SUSH&&' + indicatorValues.contains('Access / Availability'));
            System.assertEquals(true, indicatorValues.contains('Access / Availability'));
            System.assertEquals(true, indicatorValues.contains('Admit within 3 days of ER'));
            System.assertEquals(true, indicatorValues.contains('Assessment/Treatment/Diagnosis'));
        }
    }

    /**    
    *@author IDC Team    
    *@date 07/08/2015    
    *@description This Test Method is used to check for the validation error for the PQI is correct.
    *@param     
    *@return     
    */
    static testMethod void testValidation() {
        List<Potential_Quality_Issue__c> pqiListToInsert = new List<Potential_Quality_Issue__c>();
        List<Potential_Quality_Issue__c> pqiListExtracted = new List<Potential_Quality_Issue__c>();
        Id QualityId = [Select Id FROM Group WHERE DeveloperName = 'Quality'].Id;

        
        for (Integer i = 0; i<100;i++ ) {
            Potential_Quality_Issue__c pqi = new Potential_Quality_Issue__c( Access_Availability__c = true ,
                                                                         Admit_within_3_days_of_ER__c = true,
                                                                         ownerId = QualityId,
                                                                         PQI_Status__c = 'New',
                                                                         ByPass_CMO__c = false,
                                                                         Assessment_Treatment_Diagnosis__c= true
                                                                        );
            pqiListToInsert.add(pqi);
        }
        
        Database.insert(pqiListToInsert);
        // Assert to check Potential_Quality_Issue__c records created successfully
        system.assert(pqiListToInsert.size()>0);
        
        for(Potential_Quality_Issue__c pqi:pqiListToInsert){
            pqi.PQI_Status__c = 'Closed';
        }
        
        Test.startTest();
        Database.SaveResult[] srList = Database.update(pqiListToInsert, false);
        Test.stopTest();
        
        
    }
}