Sutter Health/src/objects/Safety_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Affiliate__c</fullName>
        <label>Affiliate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABSMC-Ashby</fullName>
                </value>
                <value>
                    <fullName>ABSMC-Herrick</fullName>
                </value>
                <value>
                    <fullName>ABSMC-Summit</fullName>
                </value>
                <value>
                    <fullName>CPMC-California</fullName>
                </value>
                <value>
                    <fullName>CPMC-Davies</fullName>
                </value>
                <value>
                    <fullName>CPMC-Pacific</fullName>
                </value>
                <value>
                    <fullName>CPMC-St. Luke&apos;s</fullName>
                </value>
                <value>
                    <fullName>Eden Medical Center</fullName>
                </value>
                <value>
                    <fullName>Kahi Mohala, A Behavioral Healthcare System</fullName>
                </value>
                <value>
                    <fullName>Memorial Hospital, Los Banos</fullName>
                </value>
                <value>
                    <fullName>Memorial Medical Center, Modesto</fullName>
                </value>
                <value>
                    <fullName>Menlo Park Surgical Hospital</fullName>
                </value>
                <value>
                    <fullName>Mills-Peninsula Health Servies</fullName>
                </value>
                <value>
                    <fullName>Novato Community Hospital</fullName>
                </value>
                <value>
                    <fullName>Sutter Amador Hospital</fullName>
                </value>
                <value>
                    <fullName>Sutter Auburn Faith Hospital</fullName>
                </value>
                <value>
                    <fullName>Sutter Coast Hospital</fullName>
                </value>
                <value>
                    <fullName>Sutter Center for Psychiatry</fullName>
                </value>
                <value>
                    <fullName>Sutter Davis</fullName>
                </value>
                <value>
                    <fullName>Sutter Delta Medical Center</fullName>
                </value>
                <value>
                    <fullName>Sutter Lakeside Hospital &amp; Center for Health</fullName>
                </value>
                <value>
                    <fullName>Sutter Maternity &amp; Surgey Center of Santa Cruz</fullName>
                </value>
                <value>
                    <fullName>Sutter Medical Center, Modesto</fullName>
                </value>
                <value>
                    <fullName>Sutter Roseville Medical Center</fullName>
                </value>
                <value>
                    <fullName>Sutter Medical Center, Sacramento</fullName>
                </value>
                <value>
                    <fullName>Sutter Santa Rosa Regional Hospital</fullName>
                </value>
                <value>
                    <fullName>Sutter Solano Medical Center</fullName>
                </value>
                <value>
                    <fullName>Sutter Tracy Community Hospital</fullName>
                </value>
                <value>
                    <fullName>Palo Alto Medical Foundation</fullName>
                </value>
                <value>
                    <fullName>Sutter Pacific Medical Foundation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category_of_Event__c</fullName>
        <label>Category of Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Procedural</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Patient Protection</fullName>
                </value>
                <value>
                    <fullName>Care management</fullName>
                </value>
                <value>
                    <fullName>Product or Device</fullName>
                </value>
                <value>
                    <fullName>Criminal</fullName>
                </value>
                <value>
                    <fullName>Teamwork Failures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Causes__c</fullName>
        <label>Causes</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_of_Event__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Wrong Body Part</fullName>
                </value>
                <value>
                    <fullName>Wrong Patient</fullName>
                </value>
                <value>
                    <fullName>Wrong Procedure</fullName>
                </value>
                <value>
                    <fullName>Unintended Retention of a Foreign Object</fullName>
                </value>
                <value>
                    <fullName>Post Procedure Death of Healthy Patient</fullName>
                </value>
                <value>
                    <fullName>Other Procedural</fullName>
                </value>
                <value>
                    <fullName>Electric Shock</fullName>
                </value>
                <value>
                    <fullName>Burn</fullName>
                </value>
                <value>
                    <fullName>Fall</fullName>
                </value>
                <value>
                    <fullName>Restraints/Bedrails</fullName>
                </value>
                <value>
                    <fullName>Gas Administration Event</fullName>
                </value>
                <value>
                    <fullName>Other Environmental</fullName>
                </value>
                <value>
                    <fullName>Infant Discharged to Wrong Person</fullName>
                </value>
                <value>
                    <fullName>Patient Elopement</fullName>
                </value>
                <value>
                    <fullName>Suicide or Attempted Suicide</fullName>
                </value>
                <value>
                    <fullName>Inappropriate Discharge</fullName>
                </value>
                <value>
                    <fullName>Medication Error</fullName>
                </value>
                <value>
                    <fullName>Blood Product Administration Event</fullName>
                </value>
                <value>
                    <fullName>Maternal/Perinatal Death or Disability</fullName>
                </value>
                <value>
                    <fullName>Pressure Ulcer</fullName>
                </value>
                <value>
                    <fullName>Hospital Acquired Infection (HAI)</fullName>
                </value>
                <value>
                    <fullName>Delay in Diagnosis or Treatment</fullName>
                </value>
                <value>
                    <fullName>Other Care</fullName>
                </value>
                <value>
                    <fullName>Contaminated Drugs, Devices, or Biologics</fullName>
                </value>
                <value>
                    <fullName>Device Malfunction or Use Not as Intended</fullName>
                </value>
                <value>
                    <fullName>Intravascular Air Embolism</fullName>
                </value>
                <value>
                    <fullName>Non-Licensed Individual Orders Care</fullName>
                </value>
                <value>
                    <fullName>Abduction</fullName>
                </value>
                <value>
                    <fullName>Sexual Assault</fullName>
                </value>
                <value>
                    <fullName>Physical Assault</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Event__c</fullName>
        <label>Type of Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Near Miss/Good Catch [Error occurred but didn’t reach patient]</fullName>
                </value>
                <value>
                    <fullName>Precursor Event [Error reached patient, but no or minimal harm]</fullName>
                </value>
                <value>
                    <fullName>Serious Event [Error reach patient and moderate to severe harm]</fullName>
                </value>
                <value>
                    <fullName>Teamwork Failures</fullName>
                </value>
                <value>
                    <fullName>Safety Improvement Opportunity [No error occurred--YET, but one could!]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Safety Reporting</label>
    <nameField>
        <displayFormat>SRN-{000000000}</displayFormat>
        <label>Safety Reporting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Safety Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/Safety_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>This is easier to use</fullName>
                </value>
                <value>
                    <fullName>About the same to use</fullName>
                </value>
                <value>
                    <fullName>More difficult to use</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Safety_Reporting__c</fullName>
        <label>Safety Reporting</label>
        <referenceTo>Safety_Reporting__c</referenceTo>
        <relationshipLabel>Safety Survey&apos;s</relationshipLabel>
        <relationshipName>Safety_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Suggestions__c</fullName>
        <label>Suggestions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Safety Survey</label>
    <nameField>
        <displayFormat>SafetySurvey-{000000000}</displayFormat>
        <label>Safety Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Safety Survey&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sutter Health/src/classes/SafetyCare_CC.cls
/**********************************************************************
Name: SafetyCare_CC()
======================================================
======================================================
Purpose: Custom Controller for SafetyCare.page
-------	
======================================================
======================================================
History
-------
VERSION AUTHOR DATE DETAIL Description
1.0 Brian Lee 03/23/2016 INITIAL DEVELOPMENT CSR:
***********************************************************************/
public with sharing class SafetyCare_CC {
	public Safety_Reporting__c safetyCare {get;set;}
	public boolean completed {get;private set;}
	public boolean surveySaved {get;private set;}
	public Safety_Survey__c safetySurvey {get;set;}
	public static final list<String> eventOptions {get;}
	public static final list<String> categoryOptions {get;}
	//Populate option lists with picklist options, picklists displayed on page as radio options
	static{
		eventOptions = new list<String>();
		Schema.DescribeFieldResult fieldResult = Safety_Reporting__c.Type_of_Event__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
   		for(Schema.PicklistEntry f : ple){
      		eventOptions.add(f.getValue());
   		}
   		categoryOptions = new list<String>();
		fieldResult = Safety_Reporting__c.Category_of_Event__c.getDescribe();
		ple = fieldResult.getPicklistValues();
   		for(Schema.PicklistEntry f : ple){
      		categoryOptions.add(f.getValue());
   		}
	}       

	
	public SafetyCare_CC() {
		this.safetyCare = new Safety_Reporting__c();
		this.completed = false;
		this.surveySaved = false;
	}
/*******************************************************************
Purpose: Insert the Safety_Reporting__c record provided required fields have information and flag as completed
Parameters: None
Returns: None
Throws [Exceptions]: None, Exceptions caught and displayed in message box
********************************************************************/
    public void SaveAndComplete(){
    	try{
    		//validate require fields
    		boolean sCareDone = true;
    		if(String.isBlank(safetyCare.Affiliate__c)){
    			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Location is required'));
    			sCareDone = false;
    		}
    		if(String.isBlank(safetyCare.Type_of_Event__c)){
    			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Event Type is required'));
    			sCareDone = false;
    		}
    		if(String.isBlank(safetyCare.Category_of_Event__c)){
    			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Event Category is required'));
    			sCareDone = false;
    		}
    		if(String.isBlank(safetyCare.Causes__c)){
    			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Finding is required'));
    			sCareDone = false;
    		}
    		if(String.isBlank(safetyCare.Username__c)){
    			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Your Name is required'));
    			sCareDone = false;
    		}  
    		if(sCareDone){
	    		insert safetyCare;
	    		safetySurvey = new Safety_Survey__c(Safety_Reporting__c = safetyCare.id);
	    		safetyCare = null; 
	    		this.completed = true;
    		}
    	}
    	catch(exception e){
    		ApexPages.addMessages(e);
    	}
    }
/*******************************************************************
Purpose: Calls SaveSurvey to insert Survey and refreshed page for new SafetyCare entry
Parameters: None
Returns: PageReference to current page and requests redirect
Throws  None
********************************************************************/    
    public PageReference SaveAndNew(){
    	SaveSurvey();
    	PageReference thisPage = ApexPages.currentPage(); 
    	thisPage.setRedirect(true);
    	return thisPage;
    }
/*******************************************************************
Purpose: Insert the Safety_Survey__c if filled out and flag survey completed 
Parameters: None
Returns: None
Throws [Exceptions]: None, Exceptions caught and displayed in page message box
********************************************************************/    
    public void SaveSurvey(){
    	if(safetySurvey != null){
    		try{
	    		//insert survey is question one or suggestions have been entered.
	    		if(!String.isBlank(safetySurvey.Question_1__c) || !String.isBlank(safetySurvey.Suggestions__c)){
		    		insert safetySurvey;
	    		}
	    		safetySurvey = null;
		    	this.surveySaved = true;
    		}
    		catch(exception e){
    			ApexPages.addMessages(e);
    		}
    	}
    }		
}