Sutter Health/src/objects/SH_Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom  setting used to hold common setting that were used in community site. EG: mashape key(for word correction)</description>
    <fields>
        <fullName>SH_Home_Page_Slider_Interval__c</fullName>
        <defaultValue>8000</defaultValue>
        <description>homeSliderInterval in ms (4000 ms for 4 s)</description>
        <inlineHelpText>homeSliderInterval in ms (4000 ms for 4 s)</inlineHelpText>
        <label>Home Page Slider Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

Sutter Health/src/objects/SH_Home_Page_Headliner__c.object
<CustomObject>
    <fields>
        <fullName>SH_Article_Link__c</fullName>
        <description>For Developer, Admins only</description>
        <inlineHelpText>For Developer, Admins only</inlineHelpText>
        <label>SH_ArticleID_Transform_CODE</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Content_Image_Url__c</fullName>
        <label>Content Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Content_Link__c</fullName>
        <description>This field is used to store internal or external url (must be fully qualified url)</description>
        <inlineHelpText>This field is used to store internal or external url (must be fully qualified url)</inlineHelpText>
        <label>Content Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Content_Target__c</fullName>
        <description>This field is used to open the link in same tab (_self) or in different tab (_blank)</description>
        <inlineHelpText>This field is used to open the link in same tab (_self) or in different tab (_blank)</inlineHelpText>
        <label>Content Target</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>_self</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>_blank</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SH_Content_Type__c</fullName>
        <label>Content Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Article</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Tool</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SH_Headliner_description__c</fullName>
        <description>This is the description of the title of the headliner image. This description will be visible at the front end portal</description>
        <label>Headliner description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SH_Is_Preview__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preview</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Is_Publish__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Order_of_display__c</fullName>
        <label>Order of display</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SH_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Home Page Headliner</label>
    <nameField>
        <displayFormat>HP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Page Headliners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/SH_HomePage_carousel__c.object
<CustomObject>
    <fields>
        <fullName>SH_Article_Link__c</fullName>
        <description>For Developer, Admins only</description>
        <inlineHelpText>For Developer, Admins only</inlineHelpText>
        <label>SH_ArticleID_Transform_CODE</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Carousel_description__c</fullName>
        <description>This is the description of the title of the headliner image. This description will be visible at the front end portal</description>
        <label>Carousel description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SH_Content_Link__c</fullName>
        <description>This field is used to store internal or external url (must be fully qualified url)</description>
        <inlineHelpText>This field is used to store internal or external url (must be fully qualified url)</inlineHelpText>
        <label>Content Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Content_Target__c</fullName>
        <description>This field is used to open the link in same tab (_self) or in different tab (_blank)</description>
        <inlineHelpText>This field is used to open the link in same tab (_self) or in different tab (_blank)</inlineHelpText>
        <label>Content Target</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>_self</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>_blank</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SH_Content_Type__c</fullName>
        <label>Content Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Article</fullName>
                </value>
                <value>
                    <fullName>Tool</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SH_Icon__c</fullName>
        <label>Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Is_Preview__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preview</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Is_Publish__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Order_of_display__c</fullName>
        <label>Order of display</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SH_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Home Page Carousel</label>
    <nameField>
        <displayFormat>HP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Page Carousels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/classes/SH_Landing.cls
/*
    This class is used to create the Coursel on page
    ==========================================================
    Name                    Date                       version
    ==========================================================
    Alok Verma        7/15/2015                        1.0
    ==========================================================  
*/
public class SH_Landing extends SH_BaseController 
{
    //public members
    public list<ContentWrapper> lstHeadliner {get;set;}
    public list<ContentWrapper> lstCarousel {get;set;}
    public set<String> setToolId = new set<String>();
    //added on 05-Nov-2015 for setting home page slider animation homeSliderInterval
    public integer homeSliderInterval {get;set;}

    /*
        constructor
        ===================================================================
        Name                    Date                       version
        ===================================================================
        Prashant Kumar        7/15/2015                        1.0
        ===================================================================
        Param: none
        ===================================================================
        Output :  none
        ===================================================================
    */
    public SH_Landing() {
        BreadCrumbs = new list<SH_BreadCrumb>{new SH_BreadCrumb('Home', 'sh_landing')};
        Initialize();
        BindData();
    }
    
    /*
        This method is used to initialize the variables
        ===================================================================
        Name                    Date                       version
        ===================================================================
        Prashant Kumar        7/15/2015                        1.0
        ===================================================================
        Param: none
        ===================================================================
        Output :  none
        =================================================================== 
    */    
    private void Initialize() {
        lstHeadliner = new list<ContentWrapper>();
        lstCarousel = new list<ContentWrapper>();
        //added on 05-Nov-2015 for setting home page slider animation 
        SH_Community_Settings__c objCommSetting = SH_Community_Settings__c.getValues('Setting-1');
        homeSliderInterval = (objCommSetting != null && objCommSetting.SH_Home_Page_Slider_Interval__c != null) ? integer.valueOf(objCommSetting.SH_Home_Page_Slider_Interval__c) : 8000;
    }
    
    
    /*
        This method is used Fetch Data needed to render on Page
        ===================================================================
        Name                    Date                       version
        ===================================================================
        Prashant Kumar        7/15/2015                        1.0
        ===================================================================
        Param: none
        ===================================================================
        Output :  none
        ===================================================================
    */
    private void BindData() 
    {
        list<SH_Home_Page_Headliner__c> LstSH_Home_Page_Headliner = isPreview ? [select id,SH_Headliner_description__c,SH_Title__c,SH_Content_Image_Url__c,
                                                SH_Article_Link__c,SH_Content_Type__c, SH_Content_Link__c,SH_Content_Target__c 
                                                from SH_Home_Page_Headliner__c where SH_Is_Preview__c = true order by SH_Order_of_display__c asc limit 5]
                                                : [select id,SH_Headliner_description__c,SH_Title__c,SH_Content_Image_Url__c,SH_Article_Link__c,
                                                SH_Content_Type__c,SH_Content_Link__c,SH_Content_Target__c  
                                                from SH_Home_Page_Headliner__c where SH_Is_Publish__c= true order by SH_Order_of_display__c asc limit 5];
        
        list<SH_HomePage_Carousel__c> LstSH_Home_Page_carousel = isPreview ? [select id,SH_Carousel_description__c,SH_Title__c,SH_Icon__c,SH_Article_Link__c,
                                                SH_Content_Type__c,SH_Content_Link__c,SH_Content_Target__c  
                                                from SH_HomePage_Carousel__c where SH_Is_Preview__c= true order by SH_Order_of_display__c asc limit 10]
                                             : [select id,SH_Carousel_description__c,SH_Title__c,SH_Icon__c,SH_Article_Link__c,
                                                SH_Content_Type__c,SH_Content_Link__c,SH_Content_Target__c 
                                               from SH_HomePage_Carousel__c where SH_Is_Publish__c= true order by SH_Order_of_display__c asc limit 10];
        
        if(LstSH_Home_Page_Headliner.size() > 0) {
            for(SH_Home_Page_Headliner__c objHeadliner : LstSH_Home_Page_Headliner) {
                if(string.isNotBlank(objHeadliner.SH_Content_Type__c) && objHeadliner.SH_Content_Type__c.equalsIgnoreCase('Tool') && string.isNotBlank(objHeadliner.SH_Article_Link__c))
                    setToolId.add(objHeadliner.SH_Article_Link__c);
            }
        }
        
        if(LstSH_Home_Page_carousel.size() > 0) {
            for(SH_HomePage_Carousel__c objCarousel : LstSH_Home_Page_carousel) {
                if( string.isNotBlank(objCarousel.SH_Content_Type__c) && objCarousel.SH_Content_Type__c.equalsIgnoreCase('Tool') && string.isNotBlank(objCarousel.SH_Article_Link__c))
                    setToolId.add(objCarousel.SH_Article_Link__c);    
            }
        }
        
        setToolsMap(setToolId);
        lstHeadliner = GetContentWrapper(LstSH_Home_Page_Headliner, false);
        lstCarousel = GetContentWrapper(LstSH_Home_Page_carousel, false);
    }
}