Sutter Health/src/objects/SH_Menu_Item__c.object
<CustomObject>
    <fields>
        <fullName>SH_Icon__c</fullName>
        <label>Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SH_Is_Preview__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preview</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Is_Publish__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Order_of_Display__c</fullName>
        <label>Order of Display</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Menu Item</label>
    <nameField>
        <label>Menu Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menu Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sutter Health/src/objects/SH_Sub_Menu_Item__c.object
<CustomObject>
    <fields>
        <fullName>SH_Is_Preview__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preview</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Is_Publish__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SH_Menu_Item__c</fullName>
        <label>Menu Item</label>
        <referenceTo>SH_Menu_Item__c</referenceTo>
        <relationshipLabel>Sub Menu Items</relationshipLabel>
        <relationshipName>Sub_Menu_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SH_Order_of_Display__c</fullName>
        <label>Order of Display</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Menu Item</label>
    <nameField>
        <label>Sub Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Menu Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sutter Health/src/classes/SH_MenuItem.cls
/*
    This class is used to create the dynamic MenuItem on page
    ==========================================================
    Name                    Date                       version
    ==========================================================
    Prashant Kumar        7/14/2015                        1.0
    ==========================================================  
*/
public class SH_MenuItem 
{
    //Class level variables
    Public String strTestImage {get; set;}
    public list<SH_Menu_Item__c> lstMenuItem {get; set;}
    public boolean Preview {get;set;}
    
    //Constructor
    public SH_MenuItem()
    {
        Initialize();
        BindData();   
    }
    
    public void Initialize()
    {
        lstMenuItem = new list<SH_Menu_Item__c>();
    }
    
    /*
        This method is used to bind the menue data on page
        ==========================================================
        Name                    Date                       version
        ==========================================================
        Prashant Kumar        7/14/2015                        1.0
        ==========================================================  
    */
    //issue with preview need to check, comment by ALok
    public void BindData()
    {
         Preview = false;
         lstMenuItem = !Preview ? [select Id, Name, SH_Icon__c,
                             (select id , Name from Sub_Menu_Items__r where SH_Is_Publish__c = true 
                              order by SH_Order_of_Display__c asc)     
                         from SH_Menu_Item__c
                         where SH_Is_Publish__c = true 
                         order by SH_Order_of_Display__c asc]
                         : [select Id, Name, SH_Icon__c,
                             (select id , Name from Sub_Menu_Items__r where SH_Is_Publish__c = true 
                              order by SH_Order_of_Display__c asc)     
                         from SH_Menu_Item__c
                         where SH_Is_Preview__c = true 
                         order by SH_Order_of_Display__c asc];   

    }
    
    
    
}