Sutter Health/src/objects/Site_Metric_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings used for import Google Analytics data for a Force.com Site</description>
    <fields>
        <fullName>Table_Id__c</fullName>
        <description>Google Table Id for Site, ie. ga:123456</description>
        <inlineHelpText>Google Table Id for Site, ie. ga:123456</inlineHelpText>
        <label>Table Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Events__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Track Events</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Sessions__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Track Sessions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Events__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tracking Events</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Sessions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tracking Sessions</label>
        <type>Checkbox</type>
    </fields>
    <label>Site Metric Settings</label>
</CustomObject>

Sutter Health/src/classes/GoogleAnalyticsImporterEvent.cls
/**  
*    Class Name: GoogleAnalyticsImporter 
*    Author: Saket
*    Date: 14-August-2014
*    Description: Schedular class for Google Anaytics
*    History
*    --------
**/
global with sharing class GoogleAnalyticsImporterEvent implements Schedulable
 {
        public static string jobname = 'Google Analytic importer' ;
        public static String sched = '0 0 01 * * ?'; // schedule time 1 a.m. Every day to fetch previous days data (manually scheduled as apex job so not needed)
        boolean AllorTodayDataSession ; // false all data is fetched starting from 06 may,true will fetch only todays data. 
        boolean AllorTodayDataEvent ; // false all data is fetched starting from 06 may,true will fetch only todays data. 
    global void execute(SchedulableContext SC) {
    
        System.debug('Starting Scheduled job @ ' + Date.today());
         Site_Metric_Settings__c settings;
        
        try {
            settings = [Select s.Table_Id__c,Track_Sessions__c,Tracking_Sessions__c,Track_Events__c,Tracking_Events__c From Site_Metric_Settings__c s where s.Name = :System.Label.CL52_Google_Analytics Limit 1];
            
            AllorTodayDataSession = settings.Tracking_Sessions__c ;
            AllorTodayDataEvent = settings.Tracking_Events__c ;
        } catch (QueryException ex) {
            System.debug(Logginglevel.WARN, 'No Site Metric Settings with Name = ' + System.Label.CL52_Google_Analytics + '; stopping import');
            
        } 
        
        ImportGoogleAnalytics diw = new ImportGoogleAnalytics();
        If (settings.Track_Events__c == true) // If events are to be tracked then run the methods
        {
        ImportGoogleAnalytics.callEventMethods(AllorTodayDataEvent);
        settings.Tracking_Events__c = true;
        }
        
        //GoogleAnalyticsImporter GoogleImp = new GoogleAnalyticsImporter();
    // system.schedule(jobname, sched ,GoogleImp);
        update settings;
        System.debug('Finished Scheduled job1 @ ' + Date.today()); 
    }
}