Sutter Health/src/objects/SurveyQuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>SurveyTaker__c</fullName>
        <label>SurveyTaker</label>
        <referenceTo>SurveyTaker__c</referenceTo>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>Response-{0000000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sutter Health/src/objects/SurveyTaker__c.object
<CustomObject>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sutter Health/src/classes/SurveyTest.cls
@isTest
private class SurveyTest {
  
 private static Testmethod void testUpdateSurveyName() {
 
      SurveyTestingUtil tu = new SurveyTestingUtil();
      PageReference pageRef = Page.takeSurvey;
      Test.setCurrentPageReference(pageRef); 
      System.currentPageReference().getParameters().put('id', tu.surveyId);
      
      ///Apexpages.Standardcontroller stc; 
      
      List<SurveyTaker__c>  st = new List<SurveyTaker__c>();
      
      insert st;
      
      for(SurveyTaker__c s:st){
      
      ApexPages.StandardController stc = new ApexPages.standardController(s);
      
      ViewSurveyController vsc = new ViewSurveyController(stc);
      vsc.surveyName = 'new name';
      vsc.submitResults();
      
       
      system.assert(vsc.updateSurveyName() == null);
      }
  }

    private static Testmethod void testupdateSurveyThankYouAndLink() {
        try{
        SurveyTestingUtil tu = new SurveyTestingUtil();
        Apexpages.currentPage().getParameters().put('id',tu.surveyId);  
        Apexpages.Standardcontroller stc; 
        ViewSurveyController vsc = new ViewSurveyController(stc);
        vsc.surveyThankYouText = 'new stuff';
        vsc.surveyThankYouURL = 'more new stff';
        List<SurveyQuestionResponse__c>  sqr = new List<SurveyQuestionResponse__c>();
        
        system.assert(vsc.updateSurveyThankYouAndLink()==null);
        }catch(Exception ex) {}
    }
    
    private static Testmethod void testViewSurveyController() {
        SurveyTestingUtil tu = new SurveyTestingUtil();
        Apexpages.currentPage().getParameters().put('id',tu.surveyId);  
        Apexpages.Standardcontroller stc;   
        ViewSurveyController vsc = new ViewSurveyController(stc);
        vsc.init();
        System.assert(vsc.allQuestionsSize == 4);
        System.assert(tu.surveyId != null);
        //vsc.qResponse vsc1 = new vsc.qResponse(stc);
        
        vsc.submitResults();
        vsc.updateSurveyName();
        vsc.refreshQuestionList();
        vsc.resultPage();
        
       
        
    }
    
    }